### ISSUE TITLE
Missing feature to get default domain from V3 api endpoint

### ISSUE THREAD

**Issue by theghost5800** [cloudfoundry/cf-java-client#1004]
There is not a method to call this v3 api endpoint - https://v3-apidocs.cloudfoundry.org/version/3.76.0/index.html#get-default-domain to get default domain. As I can see in the docs of v2 api - https://apidocs.cloudfoundry.org/12.0.0/ Domains resource is deprecated and we should adopt v3 API.

**Comment by twoseat** [comment]
Thanks for the report, @theghost5800. I'm not sure how soon I'll be able to get to this change, so I'd encourage you to submit a PR if you're able as that will greatly speed up the process.
