### ISSUE TITLE
Missing V3 domains resource

### ISSUE THREAD

**Issue by LittleBaiBai** [cloudfoundry/cf-java-client#1008]
The whole `domains` resource is marked as `Deprecated` in v2 api doc (https://apidocs.cloudfoundry.org/12.2.0/#domains--deprecated-) and the client code. But there is no usable v3 code to call the V3 `domains` endpoints - (http://v3-apidocs.cloudfoundry.org/version/3.77.0/index.html#domains).

**Comment by LittleBaiBai** [comment]
@twoseat I'm happy to submit a PR for it if this is something you'd like to include in CFJC.

**Comment by twoseat** [comment]
I'd be very happy to accept a PR! Let me know if you need any pointers.

**Comment by enchobelezirev** [comment]
Hello @LittleBaiBai,

Is there some estimations when the domains support will be ready?

**Comment by twoseat** [comment]
Thanks for the contribution @LittleBaiBai!
