### ISSUE TITLE
CF-InvalidAuthToken(1000): Invalid Auth Token issue with latest version

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#1023]
hi ,
with latest CF-java-client :
`compile 'org.cloudfoundry:cloudfoundry-client-reactor:4.0.1.RELEASE'`
`compile 'org.cloudfoundry:cloudfoundry-operations:4.0.1.RELEASE'`
`compile 'io.projectreactor:reactor-core:3.3.0.RELEASE'`
`compile group: 'io.projectreactor.netty', name: 'reactor-netty', version: '0.9.1.RELEASE'`

we are getting `org.cloudfoundry.client.v2.ClientV2Exception: CF-InvalidAuthToken(1000): Invalid Auth Token`  very often.

it seems it is similar to issue : [old issue](https://github.com/cloudfoundry/cf-java-client/issues/569)

**Comment by skmedishetty** [comment]
@parasuramln  are you able to resolve the issue.
Looks when there is timeout continuously while getting token..  application is ending up with IOException broken link.

**Comment by chefhoobajoob** [comment]
@parasuramln : why was this closed? we are seeing this same issue consistently in 4.0, especially with long-running deployments.

**Comment by chefhoobajoob** [comment]
fwiw, updating to 4.5 seems to have addressed the issue (so far, anyway)

**Comment by twoseat** [comment]
@chefhoobajoob It was closed due to changes that were made around token handling, the results of which you're seeing in 4.5. It's still possible that you will see related issues, so please open new issues if you spot anything.

**Comment by chefhoobajoob** [comment]
will do - thanks @twoseat
