### ISSUE TITLE
org.cloudfoundry.client.v3.ClientV3Exception: CF-ResourceNotFound(10010): App not found

### ISSUE THREAD

**Issue by rahul-raj** [cloudfoundry/cf-java-client#1038]
I was trying to write a Java code to start/stop/restart the application using the given instance name.

Here is the code that I have written:
https://gist.github.com/rahul-raj/31deba3bef8ed5f142fd5734096a39e5

And CF configuration here:
https://gist.github.com/rahul-raj/a06a1aba4f89b78e2c218caaa9da2189

Here are the dependencies added in pom.xml :
https://gist.github.com/rahul-raj/be9d4386999e106fcab4e9f29e5a4373

But I'm getting the below error while running the code (Spring boot):
`org.cloudfoundry.client.v3.ClientV3Exception: CF-ResourceNotFound(10010): App not found`

Note that the application `curl-test` is already existing in CF space. It was stopped manually (`cf stop` command) to test my code. 

Here is the complete stacktrace:
https://gist.github.com/rahul-raj/26bc042fbaf04ae3aefbaaeb7f4fe7e2

Also, note that my CF app instance is not starting up when I code as below:
`cloudFoundryClient.applicationsV3().start(request);`

Application is still in `STOPPED` state.

Please check this... Thank you!

**Comment by twoseat** [comment]
`curl-test` isn't your application's id, it's the application's name. You should try using the `operations` layer, as in [this integration test](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java#L1029-L1032)

**Comment by rahul-raj** [comment]
I just changed it to use CloudFoundryOperations layer this time.

```
 StartApplicationRequest request = StartApplicationRequest.builder()
                .name("curl-test")
                .build();
        cloudFoundryOperations.applications().start(request);
```
The application is not getting started up. Still no luck.

Updated source:
https://gist.github.com/rahul-raj/31deba3bef8ed5f142fd5734096a39e5

**Comment by twoseat** [comment]
Assuming that this is all your code, the obvious problem is that you're treating it as an imperative API, when it's actually reactive. Take a look at the first code sample [here](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-apis) for inspiration. In fact I'd start by demonstrating that this exact sample works in your setup.

**Comment by rahul-raj** [comment]
@twoseat 

I was wondering what is going wrong since my app is very simple hello world kind of code.
I followed what was mentioned in the readme here: https://github.com/cloudfoundry/cf-java-client

I believe now I have the right approach to start the application via `CloudFoundryOperations`. 
I tried with/without adding proxy configuration in connection context. Not working in both cases.
Not sure why `start()` is not starting the application! 

I don't see a problem with the configuration:
https://gist.github.com/rahul-raj/a06a1aba4f89b78e2c218caaa9da2189

**Comment by twoseat** [comment]
Did the sample code work?

**Comment by rahul-raj** [comment]
@twoseat 
Yes, it's working..
![image](https://user-images.githubusercontent.com/517415/76423764-4547cb80-63cd-11ea-99f0-47fea22eb45b.png)

**Comment by twoseat** [comment]
That's good. Now try a `GetApplicationRequest` with your app's name.

**Comment by rahul-raj** [comment]
It is working as well:
![image](https://user-images.githubusercontent.com/517415/76424839-c5bafc00-63ce-11ea-85e2-2f2922c7a2ea.png)

**Comment by twoseat** [comment]
Cool. Finally, try:
```
        CountDownLatch latch = new CountDownLatch(1);

        this.cloudFoundryOperations.applications()
            .start(StartApplicationRequest.builder()
                .name(applicationName)
                .build())
            .subscribe(System.out::println, t -> {
                t.printStackTrace();
                latch.countDown();
            }, latch::countDown);

        latch.await();
```

**Comment by rahul-raj** [comment]
wow! it worked!
So, the main thread was exiting right away before completion of start task?

**Comment by twoseat** [comment]
Correct. One of the wins of Reactor is it handles the coordination and scheduling of threads for you, but you do have to know that there are (potentially) multiple threads active.
