### ISSUE TITLE
Incorrect Enum Values for Status and Status Reasons for V3 Deployments

### ISSUE THREAD

**Issue by nickkomen** [cloudfoundry/cf-java-client#1039]
When running the V3 Deployments functionality (such as list-deployments) against a CF API version 3.80.0 or higher, the calls will fail with an IllegalArgumentException saying that status "ACTIVE" is not valid.

As of CF API 3.80.0 (when deployments was taken out of Experimental status), the valid values for status and status_reason have changed as follows:
status: ACTIVE, FINALIZED
status_reason: DEPLOYING, CANCELING, DEPLOYED, CANCELED, SUPERSEDED, DEGENERATE
http://v3-apidocs.cloudfoundry.org/version/3.80.0/#list-deployments

The two enums org.cloudfoundry.client.v3.deployments.DeploymentStatusValue and org.cloudfoundry.client.v3.deployments.DeploymentStatusReasonValue should be updated to fix this.

**Comment by twoseat** [comment]
Fix incoming. Note that for backwards compatibility the existing values will remain active for some time. Thanks for the report!
