### ISSUE TITLE
Support on invalid authentication / org.cloudfoundry.reactor.util.Operator$ResponseReceiver$InvalidTokenException is private

### ISSUE THREAD

**Issue by eaglerainbow** [cloudfoundry/cf-java-client#1046]
This is in reference to https://github.com/promregator/promregator/issues/182#issuecomment-637757562.

In a nutshell: A user apparently has some sort of authentication issue when trying to logon to the CF platform (when starting the application). On sending the first request (in our case it's a `cloudFoundryClient.info().get(request)`), an exception is raised:

```
   2020-06-02T10:57:01.79-0400 [APP/PROC/WEB/0] OUT Caused by: org.cloudfoundry.reactor.util.Operator$ResponseReceiver$InvalidTokenException: null
   2020-06-02T10:57:01.79-0400 [APP/PROC/WEB/0] OUT 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
   2020-06-02T10:57:01.79-0400 [APP/PROC/WEB/0] OUT Assembly trace from producer [reactor.core.publisher.MonoProcessor] :
   2020-06-02T10:57:01.79-0400 [APP/PROC/WEB/0] OUT 	reactor.core.publisher.Mono.checkpoint(Mono.java:1862)
   2020-06-02T10:57:01.79-0400 [APP/PROC/WEB/0] OUT 	org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.token(AbstractUaaTokenProvider.java:255)
```

In essence this hints to https://github.com/cloudfoundry/cf-java-client/blob/272094ceca9c54b7ccf125adf80d5be044a4f73b/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/util/Operator.java#L233.

Note that this class is also `private` - and virtually does not contain any valuable information - in particular no information about what went wrong during authentication. 

I also tried to do along something the lines of

```java
Mono<String> tokenMono = this.cloudFoundryClient.getTokenProvider().getToken(this.cloudFoundryClient.getConnectionContext());
tokenMono.doOnError(e -> {
    log.error("Error while getting the Auth Token", e);
}).block();
```

but also here only the same private exception is raised.

All this leads to the questions: How are consumers of the library intended to perform the verification of authentication? What is the expected error handling / the intended support approach on detecting invalid credentials provided?

Thanks for the pointer!

**Comment by eaglerainbow** [comment]
BTW: I noticed https://github.com/cloudfoundry/cf-java-client/issues/1035#issuecomment-591751095, but I didn't see anything which could help me there.

**Comment by twoseat** [comment]
Can you confirm the version of the java client being used (unlikely to make a difference in this case, but still helpful for me to know)

**Comment by eaglerainbow** [comment]
Sure thing! Sorry not to have reported that in first place:

We are running on 3.21.0.RELEASE (see also https://github.com/promregator/promregator/blob/ecf9a00d34de41b1094e4a846d431c31bb654c65/pom.xml#L58 ).

BTW: In my local test case, the CF platform is reporting `"api_version":"2.147.0"` at `/v2/info`.

HTH.

**Comment by eaglerainbow** [comment]
I could try going to [3.24.0.RELEASE](https://github.com/cloudfoundry/cf-java-client/releases/tag/v3.24.0.RELEASE) if that helped.

**Comment by twoseat** [comment]
For security reasons you should definitely update to at least [3.22.0.RELEASE](https://github.com/cloudfoundry/cf-java-client/releases/tag/v3.22.0.RELEASE), but I don't think this issue would be affected.

**Comment by eaglerainbow** [comment]
ad 3.22.0 - [Wilco](https://en.wikipedia.org/wiki/Procedure_word#WILCO)

**Comment by twoseat** [comment]
It's worth saying that we take great care to retain backwards compatibility, so it's worth updating to the latest version as often as your corporate policies allow.

**Comment by eaglerainbow** [comment]
> ad 3.22.0 - Wilco

With https://github.com/promregator/promregator/issues/183 I have bumped the version to 3.24.0. Will go out with our next release version.

BTW: As already expected, bumping did not change anything in the behavior (initial topic of this ticket).

**Comment by skmedishetty** [comment]
@twoseat  is invalid token issue is resolved, we are facing same issue, i get invalid token error after running app for a day.
cf client version 3.24.0

**Comment by dmikusa-pivotal** [comment]
Closing as this was opened against the 3.x which is no longer supported. Feel free to open a new issue if you're still having issues with the latest supported versions of cf-java-client. Thanks
