### ISSUE TITLE
Missing support for service instance maintenance_info

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-java-client#1048]
### Expected behavior

As a cf-java-client user
* in order to trigger the equivalent of `cf update-service --upgrade` CF CLI calls
* I need to be able to provide a [maintenance_info](https://apidocs.cloudfoundry.org/13.2.0/service_instances/update_a_service_instance.html) in the `org.cloudfoundry.client.v2.serviceinstances.UpdateServiceInstanceRequest.builder()`

### Observed behavior

Only service plan object has maintenance info contributed in dbc5275ed0299ad11018666490e5d01aef9ad4ff

**Comment by twoseat** [comment]
Resolved in https://github.com/cloudfoundry/cf-java-client/commit/9fb5485a5cd88a85e2666dffac5790278016d47a (Forgot to tag appropriately)

**Comment by gberche-orange** [comment]
many thanks @twoseat !

**Comment by gberche-orange** [comment]
@twoseat I lately realized that maintenance_info fields are also missing to support the cf CLI workflow `cf services` which displays the maintenance_info as a new [upgrade available](https://docs.cloudfoundry.org/devguide/services/managing-services.html#upgrade) column and `cf service s`  which displays the maintenance_info details.

The maintenance_info would therefore also be needed in:

```
CloudFoundryOperations.Services:
Mono<ServiceInstance> getInstance(GetServiceInstanceRequest request);
Flux<ServiceInstanceSummary> listInstances();
```

https://github.com/cloudfoundry/cf-java-client/blob/9fb5485a5cd88a85e2666dffac5790278016d47a/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/_ServiceInstance.java#L28
https://github.com/cloudfoundry/cf-java-client/blob/9fb5485a5cd88a85e2666dffac5790278016d47a/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/AbstractServiceInstanceSummary.java#L26

Any chance to include this field in the two additional responses before cutting 3.25.0 release ?

**Comment by twoseat** [comment]
I'll take a look - it's not always as simple as just adding the field in because we often have to do something to put the right data in the right place, but I suspect not too hard. For my tracking purposes can you open a new issues with this request please.

**Comment by gberche-orange** [comment]
Thanks, I've opened https://github.com/cloudfoundry/cf-java-client/issues/1050 to help with tracking.
