### ISSUE TITLE
Missing maintenance_info in ServiceInstance and ServiceInstanceSummary

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-java-client#1050]
### expected behavior

As a cf-java client user
* in order to implement the equivalent  of cf CLI workflow `cf services` which displays the maintenance_info as a new [upgrade available](https://docs.cloudfoundry.org/devguide/services/managing-services.html#upgrade) column and `cf service s`  which displays the maintenance_info details.
* I need a `MaintenanceInfo` to be returned from

```
CloudFoundryOperations.Services:
Mono<ServiceInstance> getInstance(GetServiceInstanceRequest request);
Flux<ServiceInstanceSummary> listInstances();
```

### current behavior

`MaintenanceInfo` to be returned from these calls
https://github.com/cloudfoundry/cf-java-client/blob/9fb5485a5cd88a85e2666dffac5790278016d47a/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/_ServiceInstance.java#L28
https://github.com/cloudfoundry/cf-java-client/blob/9fb5485a5cd88a85e2666dffac5790278016d47a/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/AbstractServiceInstanceSummary.java#L26

### Workaround

Use low level client `org.cloudfoundry.client.v2.serviceinstances` instead of cf-operations

**Comment by twoseat** [comment]
Hi @gberche-orange - I'm working on this now and have a question (or possibly two!) When I try `cf service s` I don't see where the `maintenance_info` should appear. Can you help?

**Comment by twoseat** [comment]
OK, now I have an actual question! To fit with how the operations layer normally works we wouldn't actually return `maintenance_info` from, for example, `Flux<ServiceInstanceSummary> listInstances();`. Instead the returned object would have a new boolean something like `upgradeAvailable`. Is that boolean what you're actually asking for?

**Comment by gberche-orange** [comment]
@twoseat a `upgradeAvailable` boolean would match the use-case of `cf services` listing whether an upgrade is available. However, to show the actual upgrade description in `cf service myservice` reproduced below, the `maintenance_info` is necessary (although the cli currently chooses to only display the ` maintenance_info.description`  and not yet `maintenance_info.version`)

I would therefore suggest in a 1st step to return the full `maintenance_info` object and leave client callers to implement the logic of the computing the `upgrade_available` field by comparing the returned maintenance_info and the associated plan's catalog entry. This would save extra CC API calls for clients that don't yet need the `upgrade` field.

```
$ cf services
Getting services in org acceptance / space dev as admin...

name      service   plan     bound apps   last operation     broker         upgrade available
mydb      p-mysql   small                 create succeeded   mysql-broker   yes
otherdb   p-mysql   medium                create succeeded   mysql-broker   no

$ cf service mydb
Showing info of service mydb in org osb-cmdb-services-acceptance-tests / space development as xxx...

name:             mydb
service:          p-mysql
tags:             
plan:             standard
description:      An osb-cmdb service that deploys a backing service
documentation:    
dashboard:        
service broker:   test-broker-upgrade-instance

Showing status of last operation from service si-upgrade-instance...

status:    create succeeded
message:   
started:   2020-06-10T14:27:32Z
updated:   2020-06-10T14:27:32Z

There are no bound apps for this service.

Showing available upgrade details for this service...

upgrade description: provides patch for CVE XX

TIP: You can upgrade using 'cf update-service si-upgrade-instance --upgrade'
```

**Comment by twoseat** [comment]
So as a user you'd say that the full `maintenance_info` will be useful over just the description, even if you had the boolean? That makes sense, and follows a precedent we've set elsewhere. And not having to calculate the boolean just yet would make things easier, though I'd expect to add it later anyway.
