### ISSUE TITLE
cf client - unable to fetch "stack(cflinuxfs2/cflinuxfs3)" info while fetching list of buildpacks using the cloudFoundryOperations.

### ISSUE THREAD

**Issue by anhsirksai** [cloudfoundry/cf-java-client#1056]
Hi,

I am trying to fetch the "cf buildpacks" command output using the cf client as below:
```
cloudFoundryOperations.buildpacks()
                    .list()
                    .collectList().block();
```

I am able to fetch the results for all the buildpacks available in a pool.

The output only contains only the fields described in below class.

```
public final class Buildpack extends _Buildpack {
    private final Boolean enabled;
    @Nullable
    private final String filename;
    private final String id;
    private final Boolean locked;
    private final String name;
    private final Integer position;
```

I am using the cf-client version 3.23.0.RELEASE(Even the latest tag contains only the below shown "Buildpack" class variables without "stack" variable)

However, I also need the "stack" cflinuxfs2/cflinuxfs3 information as part of the output which is shown while using cf cli client version 6.42.0. Could you please help me figure out the right cf client version to fetch the stack info along with the list of buildpacks deployed.

```
buildpack                   position   enabled   locked   filename                                                    stack
staticfile_buildpack        1          true      true     staticfile_buildpack-cached-cflinuxfs3-v1.4.43.zip          cflinuxfs3
```

**Comment by twoseat** [comment]
Thanks for the report. This is an improvement in the CLI that hasn't made it into the java client yet. It should be a small change, so we should be able to include it within the next couple of releases.

**Comment by anhsirksai** [comment]
Cool :) Its not available in the v3 api as well,  as per my understanding.

I am not able to figure out from the implementation in "ReactorCloudFoundryClient" class. This does not have a Buildpacksv3 variable and I am not definitively able to fetch the information using the client as well.  Can you please confirm if my understanding is right?

```
package org.cloudfoundry.reactor.client;

public final class ReactorCloudFoundryClient extends _ReactorCloudFoundryClient {
    private final transient ApplicationUsageEvents applicationUsageEvents;
    private final transient ApplicationsV2 applicationsV2;
    private final transient ApplicationsV3 applicationsV3;
    private final transient Blobstores blobstores;
    private final transient Buildpacks buildpacks;
    private final transient Builds builds;
    private final transient DeploymentsV3 deploymentsV3;
    private final transient Domains domains;
    private final transient Droplets droplets;
    private final transient EnvironmentVariableGroups environmentVariableGroups;
    private final transient Events events;
    private final transient FeatureFlags featureFlags;
    private final transient Info info;
```

**Comment by twoseat** [comment]
I'm sorry, I didn't quite understand your question. If it helps, the solution I'll implement is to add the field to the `_Buildpack` object referenced above, then add the line `.stack(entity.getStack())` to the `toBuildpackResource` method of `DefaultBuildpacks`. In fact now that I've worked out just how simple it is, I'll do it now so you can pick up a build snapshot tomorrow!

**Comment by anhsirksai** [comment]
That was pretty quick to fix it :) This might take a while to reach our nexus. But I will take this fix as soon as possible.  Thank you for the effort :)

**Comment by twoseat** [comment]
It's still only in the build snapshot at the moment. I'll be doing a release shortly after the next release of Spring Boot to pick up some more dependency updates, but I don't know quite when that will be.
