### ISSUE TITLE
Issue fetching Instance Details when state is set to 'STOPPED'

### ISSUE THREAD

**Issue by skhan17** [cloudfoundry/cf-java-client#1057]
Hi! There seems to be an issue in getting the information for  instance details, specifically, whenever I want to obtain details for a state that is in 'STOPPED' state, I get the error that is attached in the screenshot below. However, whenever I want to obtain instance details for a state that is in either the 'RUNNING' or 'DOWN' state, the instance details print out, it just seems to be an error with just stopped apps. It also seems that apps with running/down apps with stopped apps, gives an error. I just wanted to clarify if this was an error that could be fixed on your end or if this is an outlying error? Thank you!

![Error](https://user-images.githubusercontent.com/68302097/87709810-5dbd5d80-c794-11ea-977e-29ef06a75523.PNG)

**Comment by twoseat** [comment]
Hi. Can you tell me what version of the client you're using?

**Comment by skhan17** [comment]
Hi! I have no version specified, I just have ' implementation 'org.springframework.cloud:spring-cloud-cloudfoundry-discovery' ' specified in the gradle.build. 

I am currently a new intern working on this project, can you tell me how to check what the client version is? Thank you.

**Comment by twoseat** [comment]
I'm not too familiar with Gradle, but I believe `gradle dependencies` from the root of your project should give you what you need.

**Comment by skhan17** [comment]
After checking, I believe the client version is 2.2.1

**Comment by twoseat** [comment]
I believe that's the version of spring-cloud-cloudfoundry-discovery you're using (there is no such version of the client). But that tells me that you are (presumably) using `3.9.0.RELEASE` (https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/v2.2.1.RELEASE/pom.xml#L190).

With that info I can dig into this tomorrow and see what I can find. Thanks.

**Comment by skhan17** [comment]
okay thank you!

**Comment by twoseat** [comment]
The dependency supplied as part of `spring-cloud-cloudfoundry-discovery` is very old (they're looking into an upgrade at some point), so it's likely but not guaranteed that what you're seeing is a result of using an old version of the java client. Please try excluding the cloudfoundry-client-reactor, cloudfoundry-operations and cloudfoundry-util dependencies that are being shipped with spring-cloud-cloudfoundry-discovery, and add the 3.25.0.RELEASE version in your own maven/gradle file. Then let me know if you still see the problem.

**Comment by skhan17** [comment]
Hi! I get this error when I tried to add the 3.25.0.RELEASE:

![repos](https://user-images.githubusercontent.com/68302097/87709339-a6284b80-c793-11ea-9a09-747a5add180d.PNG)

**Comment by twoseat** [comment]
You're trying to add the `3.25.0.RELEASE` of `spring-cloud-cloudfoundry-discovery`, which doesn't exist. What you want to do is force the dependency for each of the modules mentioned above. So something like the following in `build.gradle`:

```
dependencies {
    compile("org.springframework.cloud:spring-cloud-cloudfoundry-discovery:2.2.1.RELEASE")
    compile('org.cloudfoundry:cloudfoundry-client-reactor:3.25.0.RELEASE') {
        force = true
    }
    compile('org.cloudfoundry:cloudfoundry-operations:3.25.0.RELEASE') {
        force = true
    }
    compile('org.cloudfoundry:cloudfoundry-util:3.25.0.RELEASE') {
        force = true
    }
}
```

Please be aware that I've almost no experience of Gradle, so a) that could be wrong, and b) even if it's right it might not be how your employer does this sort of thing. There are often several ways to achieve the same result in Maven, Gradle, etc., but consistency is very important, so have a look around your project and any others you have access to there, see if you can find something you think is doing the same thing, and if you do find something do it that way (sorry if you already know this, but you did say you're an intern!)

Also you should be able to copy/paste the error text, which is much easier for others to read than a screenshot. Just paste it surrounded by triple backticks (```)

**Comment by skhan17** [comment]
Hi! So I added that to my build.gradle file and it resolved my issue! Thank you!

**Comment by twoseat** [comment]
That's good news! Please keep a lookout for updates to `spring-cloud-cloudfoundry-discovery`, as I'm hopeful that an update soon will update their dependency on the java client and let you back out the changes to your build file.
