### ISSUE TITLE
StartApplication is not working 

### ISSUE THREAD

**Issue by shirakurland** [cloudfoundry/cf-java-client#1065]
Hello,
I have been assigned to create a method that will start an application. I have the code implemented correctly yet nothing is happening when I run my project. 
I'm an intern, so i am new to this and therefore I am not so familiar with cloudfoundry overall. 
If you can help me in any way that would be much appreciated.

My code is written below: 
```
public Mono<Map<String, Object>> startApplication(String orgName, String spaceName, String appName){ 
        return this.getApplications(orgName, spaceName)
                .flatMap(ApplicationDetail ->  Mono.zip(Mono.just(ApplicationDetail.getName()),Mono.just(ApplicationDetail.getRequestedState().equals("STOPPED") ?
                                runApplication(orgName, spaceName, appName): "the application is already running")))
                .filter(hmap -> hmap.getT1().equalsIgnoreCase(appName))
                .collectMap(Tuple2::getT1,Tuple2::getT2);
    }
```
```
    public Mono<Void> runApplication(String appName, String orgName, String spaceName) {
        final CloudFoundryOperations cloudFoundryOperations = this.getCloudFoundryOperations(orgName, spaceName);
      
           return cloudFoundryOperations.applications()
                .start(StartApplicationRequest.builder()
                        .name(appName)
                        .build());
    }
```

**Comment by twoseat** [comment]
There are a few things that might be your problem depending on your surrounding code. My first guess is threading, which would mean that you've set up something to happen but never wait on the active thread for it to actually happen before returning complete. The second guess would be that you haven't actually subscribed to your flow to cause something to happen - you haven't in the code listed, but perhaps you have that elsewhere.

Try the following snippet, which handles both of these things, and if that works you should be able to build from there:
```
        CountDownLatch latch = new CountDownLatch(1);

        this.cloudFoundryOperations.applications()
            .start(StartApplicationRequest.builder()
                .name(applicationName)
                .build())
            .subscribe(System.out::println, t -> {
                t.printStackTrace();
                latch.countDown();
            }, latch::countDown);

        latch.await();
```

**Comment by shirakurland** [comment]
I want to return the runApplication method and then call it in my startApplication. 
What should I return? @twoseat

**Comment by shirakurland** [comment]
> There are a few things that might be your problem depending on your surrounding code. My first guess is threading, which would mean that you've set up something to happen but never wait on the active thread for it to actually happen before returning complete. The second guess would be that you haven't actually subscribed to your flow to cause something to happen - you haven't in the code listed, but perhaps you have that elsewhere.
> 
> Try the following snippet, which handles both of these things, and if that works you should be able to build from there:
> 
> ```
>         CountDownLatch latch = new CountDownLatch(1);
> 
>         this.cloudFoundryOperations.applications()
>             .start(StartApplicationRequest.builder()
>                 .name(applicationName)
>                 .build())
>             .subscribe(System.out::println, t -> {
>                 t.printStackTrace();
>                 latch.countDown();
>             }, latch::countDown);
> 
>         latch.await();
> ```
I want to return the runApplication method and then call it in my startApplication.
what should I return?

**Comment by twoseat** [comment]
Ternary operators are great, but from experience they're almost never a good idea within a reactive flow. Try refactoring your code to remove it and I'll be better able to understand what you're trying to achieve. At the moment you seem to be overloading the return object - it's either a string, or a complex object, which isn't friendly for whoever comes next in the flow.

Also take a look at `TupleUtils.function`, as used here, to clean up your code a little:
https://github.com/cloudfoundry/cf-java-client/blob/main/integration-test/src/test/java/org/cloudfoundry/client/v2/ApplicationsTest.java#L704-L708

**Comment by shirakurland** [comment]
Hello,

I decided to take a step back and just try to get an application running instead of getting the application to run with additional conditional statements. After running the code, I receive the following error: " java.lang.IllegalArgumentException: Organization orgName does not exist. "

I am wondering if you can help me understand why my code is not picking up on the organization that includes the application I want to run. My code is as follows:

public void runApplication(String appName, String orgName, String spaceName) throws InterruptedException {     
        CountDownLatch latch = new CountDownLatch(1);
        this.getCloudFoundryOperations(orgName,spaceName)
                .applications()
                .start(StartApplicationRequest.builder()
                        .name(appName)
                        .build())
                .subscribe(System.out::println, t -> {
                    t.printStackTrace();
                    latch.countDown();
                }, latch::countDown);
        latch.await();
    }

Like I said earlier, I am intern and I'm new to cloudFoundryOperations so if there is any way you can guide me that would be much appreciated!!

Thanks in advance,

Shira Kurland

**Comment by twoseat** [comment]
Reactor can do conditionals such as `if` in a variety of ways, but often the best approach is a filter. Excuse the formatting as I'm coding in a browser, but I think in your case that would look like this:

```
this.getApplications(orgName, spaceName)
            .filter(applicationDetail -> applicationDetail.getName().equals(appName))
            .filter(applicationDetail -> applicationDetail.getRequestedState().equals("STOPPED"))
            .flatMap(applicationDetail -> runApplication(orgName, spaceName, appName))
```

Incidentally, the `start()` method [here](https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L567-L578) already handles this scenario (and handles waiting for the application to start), so be sure you're not reinventing the wheel.

**Comment by shirakurland** [comment]
Thank you for all your help! The method now works properly 👍
