### ISSUE TITLE
Provide Page number in response

### ISSUE THREAD

**Issue by pranjalc92** [cloudfoundry/cf-java-client#1066]
The current/next and last page number is not present in the response of any Response Entities.

When we want to iteratively get all records like spaces, then crawling the APIs is difficult when the current or next page number is not part of the response.

**Comment by twoseat** [comment]
You'll be pleased to hear that there's no need to use the page number, as the client will handle that for you. As an example, [this test](https://github.com/cloudfoundry/cf-java-client/blob/main/integration-test/src/test/java/org/cloudfoundry/client/v2/SpacesTest.java#L384-L402) lists all spaces, turning the entire list into a `Flux` of space resources. Note that there's also a `requestClientV3Resources()` option if you're using v3 apis

**Comment by dmikusa-pivotal** [comment]
Closing as this question was answered. If you feel like it was not answered or have additional questions, feel free to reopen it.
