### ISSUE TITLE
Calls to CF are not originating after a period of time

### ISSUE THREAD

**Issue by vpdhayanithi** [cloudfoundry/cf-java-client#1074]
Hello all,

We notice a strange problem. After certain period of time (3hrs - 24 hrs) of launch of our application, we see no outbound http calls to platform are made by CF java library. The mono is constructed and subscribed but the call is never made. The only custom configuration made is connection pool's size is set to 32.  On checking the thread dump, what we notice is there are 4 threads with name cloudfoundry-client-epoll-_d_ of which 1 is waiting and 3 are running. When it is properly functioning, we notice all 4 of them running. Am I missing anything here? Any pointers will be appreciated.

Regards,
Vishnu Prasath

**Comment by twoseat** [comment]
Can you tell me what version of the client you're running?

**Comment by vpdhayanithi** [comment]
We are using 4.6.0 version.

**Comment by twoseat** [comment]
I don't have any immediate ideas for you. In theory this could happen if the endpoint stops responding some ways, so if you can figure out what the waiting thread is waiting for that might give you a clue (we've seen failures in the past where we just overwhelmed particular endpoints). And I would definitely recommend upgrading to the latest version of the client - we're dependent on our reactor dependencies for this aspect of thread management, and having the latest versions of those dependencies may make this issue go away. In the meantime I'll work on some long-lived tests to see what I can find.

**Comment by vpdhayanithi** [comment]
Thanks for your response. I shall try. Nevertheless, I see one of cloudfoundry-client-epoll-d thread goes into waiting state. May I know how can I avoid this situation? By setting timeout or some other configuration

**Comment by dmikusa-pivotal** [comment]
It's been a while, but following up on this. The problem you're describing could be a number of things.  Like Paul said though, it could be blocked threads, you could be calling `.block()` somewhere and causing issues, your token could be expiring and not getting refreshed, errors could be occurring but swallowed. I'm sure there are more things as well.

I would recommend taking a look at the [troubleshooting section](https://github.com/cloudfoundry/cf-java-client#troubleshooting) of the README for ideas on how to debug more.

I'm going to close this ticket as it's been quite for a while. If you suspect a bug with the cf-java-client and you can provide a sample app with detailed steps to reproduce the issue, please reopen and attach that information. Thanks
