### ISSUE TITLE
Missing Service Offerings API

### ISSUE THREAD

**Issue by theghost5800** [cloudfoundry/cf-java-client#1075]
Hello, 
I am glad to see that coverage of v3 API endpoints is increasing with every new release of cf java client. I have noticed that [Service Offerings](http://v3-apidocs.cloudfoundry.org/version/3.92.0/index.html#service-offerings) is missing in client. So I decided to track this as issue.

**Comment by theghost5800** [comment]
I have noticed also that [v3 Service Brokers](http://v3-apidocs.cloudfoundry.org/version/3.92.0/#service-brokers) and [v3 service plan visibility](http://v3-apidocs.cloudfoundry.org/version/3.92.0/index.html#service-plan-visibility) missing in the client.

**Comment by twoseat** [comment]
If you have specific requests can you log those as separate issues for tracking purposes? Thanks!

**Comment by theghost5800** [comment]
Hi @twoseat ,
I have decided to implement missing APIs by myself. I would like you to review my PR. Changes are separated in different commits.

**Comment by dmikusa-pivotal** [comment]
Closing as the associated PR has been merged.
