### ISSUE TITLE
Missing V3 Service Brokers API

### ISSUE THREAD

**Issue by theghost5800** [cloudfoundry/cf-java-client#1076]
Missing implementation of http://v3-apidocs.cloudfoundry.org/version/3.92.0/#service-brokers

**Comment by twoseat** [comment]
Resolved in 6e576188bafd370084830cc08850d6415f4ff034

**Comment by theghost5800** [comment]
Wrong issue was closed. I think that this should be closed - https://github.com/cloudfoundry/cf-java-client/issues/1075

**Comment by twoseat** [comment]
I shouldn't do admin before 9am! Thanks @theghost5800
