### ISSUE TITLE
Consult: where are from the crash event exit status

### ISSUE THREAD

**Issue by amber-yan** [cloudfoundry/cf-java-client#1082]
We often hit some app.crash event, the exit_description is like: exit with status 137 or something else.
I'd like to confirm where are the exit status? Is it the same for java application and node js application? 
How do I know the exact meaning of the exit status?

Thanks

**Comment by twoseat** [comment]
The java client is not responsible for the error codes that are returned - we just report the information supplied by the cloud controller. This [article](https://community.pivotal.io/s/article/When-an-app-crashes-how-to-interpret-the-log-entries?language=en_US) may help you with diagnosing your problems.
