### ISSUE TITLE
cloudFoundClient getInstance request performance is slow

### ISSUE THREAD

**Issue by emmaz03sap** [cloudfoundry/cf-java-client#1090]
hi CF client library authors,

There is noticeable delay for getInstance requests recently since Jan27. It has been pretty fast (under 20 seconds) before and now taking about 3-5minutes. 

We consume the getInstance API like:

```
 CloudFoundryOperations cloudFoundryOperations = getCloudFoundryOperations(org, space);

GetServiceInstanceRequest instanceRequest = GetServiceInstanceRequest.builder()
           .name(name)
            .build();
ServiceInstance instance = cloudFoundryOperations.services().getInstance(instanceRequest)
                .retryWhen(Retry.anyOf(SSLException.class)
                        ...
                .block();
```
and I assume it is the code here:
https://github.com/cloudfoundry/cf-java-client/blob/54732e1eda5f6d360584e70c5e3fa4ae74faed15/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/DefaultServices.java#L237

I consulted the CF curl team and running V2 and V3 command to get service instance directly is fast (~5seconds). Could you please help advice if there is recent changes or announcement or known performance delay related to this? 

We appreciate your suggestions and help.

Regards,
Emma

**Comment by dmikusa-pivotal** [comment]
Hi @emmaz03sap - Taking a quick look at the blame log, it doesn't look like this particular method has changed in years so on the surface there doesn't seem to be anything that would cause more delays.

Questions for you:

1. Did you upgrade your cf-java-client libraries? If so what version were you using previously? What version are you using now?
2. Have you upgraded any dependencies in Maven or Gradle? In particular, have you switched Spring Boot versions (if you are using Spring Boot)?

Suggestions:

1. Enable basic request logging. Set `logging.level.cloudfoundry-client=debug` (Spring Boot). This enables debug logging for `cloudfoundry-client.request`, `cloudfoundry-client.response` and `cloudfoundry-client.operations` which should give you some basic request/response information about what is happening when the slowness occurs.
2. You can also enable `logging.level.cloudfoundry-client.wire=trace` which will give you wire level logging. It's not pretty to look at, but can give you more clues about what is happening.

Hope that helps!
