### ISSUE TITLE
Releases v5.3.0.RELEASE  and v5.2.0.RELEASE are incomplete

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-java-client#1100]
https://github.com/cloudfoundry/cf-java-client/releases/tag/v5.2.0.RELEASE
https://github.com/cloudfoundry/cf-java-client/releases/tag/v5.3.0.RELEASE

It seems that the releases are incomplete:
* lacking release notes
* not yet published on maven central according to https://mvnrepository.com/artifact/org.cloudfoundry/cloudfoundry-operations but only on springjars according to https://mvnrepository.com/artifact/org.cloudfoundry/cloudfoundry-operations?repo=bt-spring-jars

As a result, dependabot PRs such as https://github.com/orange-cloudfoundry/osb-cmdb/pull/102 fail likely because the jars can't be fetched from maven central

**Comment by dmikusa-pivotal** [comment]
Thanks for raising this up. There are some CI issues at the moment. I'm looking into them and hope to have them fixed shortly. I'll give you an update when the pipelines are green again.

**Comment by dmikusa-pivotal** [comment]
These should be published now. I've also added release notes on Github. Let me know if you're still seeing issues.

**Comment by gberche-orange** [comment]
great, thanks a lot @dmikusa-pivotal !
