### ISSUE TITLE
API throttling

### ISSUE THREAD

**Issue by SvenScheurer** [cloudfoundry/cf-java-client#1121]
Dear contributors,

q: does your API client support any way of API throttling making calls to Cloud Foundry endpoints?
I wasn't able to find something inside this repository and was wondering whether you have some call limits per user.

Thanks and best,
Sven

**Comment by dmikusa-pivotal** [comment]
>q: does your API client support any way of API throttling making calls to Cloud Foundry endpoints?
I wasn't able to find something inside this repository and was wondering whether you have some call limits per user.

The client library is not throttling anything or counting API requests made.

It's not part of the client, but we use Reactor so you could use something like [`retryWhen()`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#retryWhen-reactor.util.retry.Retry-) to back off when there's an issue. Like if you get a 429 response from the API, retry after a few seconds.
