### ISSUE TITLE
CF API V2 vs V3

### ISSUE THREAD

**Issue by dev-mash** [cloudfoundry/cf-java-client#1149]
Is it possible to switch from V2 to V3 CF apis?

We want to test a problem which occurs when using CF V3 API. We use following code to create a service instance:
![image](https://user-images.githubusercontent.com/67481204/166929554-e4cd9877-8e83-44e2-b6e3-124d71fec20b.png)

https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/DefaultServices.java#L156

This seems to use the CF V2 API. Is it possible to make sure CF API V3 is used and if yes, how to define the API version?

**Comment by dmikusa-pivotal** [comment]
The operations library primarily uses the v2 API, as you're seeing. There is no configuration to switch it. The operations library is built on top of the client library and it primarily uses the v2 API, so it would require code changes to make it use v3.

Over time, everything will eventually move to v3, but we're not in any particular rush to move things over. The v2 API is deprecated but it will very likely continue to exist for a long time and it works well in most cases.

If you want to use the v3 API, you can use the CF v3 Client libraries directly. This may require additional work in some cases, as the operations library sometimes wraps up multiple client library calls into one method for your convenience.

https://github.com/cloudfoundry/cf-java-client/tree/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3

**Comment by dev-mash** [comment]
Thanks for the prompt reply and pointing me into this direction. I will have a look into the direct usage of V3 client library.

**Comment by dmikusa-pivotal** [comment]
No problem.
