### ISSUE TITLE
How target the space when pushing an app

### ISSUE THREAD

**Issue by donacarr** [cloudfoundry/cf-java-client#1154]
Hi, 

I am updating my code to pass from old client lib 1.x to 5.8 and I need to push my test app in the dev space of my org.
I am using [CloudFoundryOperations API](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-builder) and so basically I will do something like
```
cloudFoundryOperations.applications()
            .push(PushApplicationRequest.builder()........
```
But how may I target the space where pushing the app ?

**Comment by dmikusa-pivotal** [comment]
You can set the org & space when you create the `DefaultCloudFoundryOperations` object using the builder. See below.

```
DefaultCloudFoundryOperations.builder()
    .cloudFoundryClient(cloudFoundryClient)
    .dopplerClient(dopplerClient)
    .uaaClient(uaaClient)
    .organization("example-organization")
    .space("example-space")
    .build();
```

**Comment by donacarr** [comment]
Thank you @dmikusa-pivotal
