### ISSUE TITLE
Access token is not refreshed

### ISSUE THREAD

**Issue by donacarr** [cloudfoundry/cf-java-client#1155]
Hi,

I am using Spring Boot and the 5.8.0.RELEASE to build a java application to push a nodejs app in CF and make same REST api call.
I am using the PasswordGrantTokenProvider to get the Access token.
I noted from the below logs that only after the first 60 minutes there is the log  **_Negotiating using refresh token_**.
And so after two hours the Access token is expired.
No more log _cloudfoundry-client.token_ after the 16:25:35 time...
Any idea?
Please let me know if I have to enable more logging to provide more details.
Thx

```
15:25:21.210 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Negotiating using token provider
15:25:24.572 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Refresh Token:       <redacted>
15:25:24.653 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Refresh Token Issued At:  2022-06-03T13:25:22 UTC
15:25:24.654 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Refresh Token Expires At: 2022-06-10T13:25:22 UTC
15:25:24.673 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Access Token:       <redacted>
15:25:24.680 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Access Token Issued At:  2022-06-03T13:25:22 UTC
15:25:24.681 [cloudfoundry-client-epoll-2] DEBUG cloudfoundry-client.token - Access Token Expires At: 2022-06-03T14:25:22 UTC
16:25:34.323 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Negotiating using refresh token
16:25:35.764 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Refresh Token:       <redacted>
16:25:35.777 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Refresh Token Issued At:  2022-06-03T13:25:22 UTC
16:25:35.778 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Refresh Token Expires At: 2022-06-10T13:25:22 UTC
16:25:35.779 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Access Token:       <redacted>
16:25:35.792 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Access Token Issued At:  2022-06-03T14:25:33 UTC
16:25:35.793 [cloudfoundry-client-epoll-3] DEBUG cloudfoundry-client.token - Access Token Expires At: 2022-06-03T15:25:33 UTC
```

**Comment by dmikusa-pivotal** [comment]
Nothing jumps out from what you've posted. I think we'll need more details, see https://github.com/cloudfoundry/cf-java-client#troubleshooting for what is typically helpful.

>I noted from the below logs that only after the first 60 minutes there is the log Negotiating using refresh token.
>And so after two hours the Access token is expired.

Can you expand on what you're doing in the client? You mentioned pushing an app, but surely that doesn't take hours to do. What else is the app doing? If you could provide a code snippet or something that reproduces this that would increase the odds of being able to track down the issue.
