### ISSUE TITLE
Spring Boot 2.7 support

### ISSUE THREAD

**Issue by eragee** [cloudfoundry/cf-java-client#1177]
From readme:

> The Cloud Foundry Java Client has two active versions. The 5.x line is compatible with Spring Boot 2.4.x - 2.6.x just to manage its dependencies, while the 4.x line uses Spring Boot 2.3.x.

Are you planning to release a version that is compatible with Spring Boot 2.7.x?  Thank you.

**Comment by dmikusa** [comment]
Sorry, that just never got updated. I'm 99% sure we tested and it worked fine with 2.7.x. I do not believe it'll work with 3.0 though. I think there are changes necessary to make that work, mostly due to the Java 17 requirement. That'll have to be another branch.

**Comment by eragee** [comment]
Thanks for clarifying.  We'll start testing 5.9 with SB 2.7.
