### ISSUE TITLE
OAuth cli token harvesting doesn't appear to work with Go CLI

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#161]
We love the feature Scott added that harvests current oauth tokens from the cf cli's config file.  This makes it so that in order to use the maven plugin we don't need to supply a username and password for our commands if we have an active "cf" session.

However, we recently transitioned to the Go CLI and it appears this feature has stopped working.  It would be great if this feature could be updated to work with the Go CLI `config.json` file.

**Comment by nebhale** [comment]
@youngm I'm looking over all of the issues in the repo with a fresh set of eyes.  I wanted to get a feel for whether you still think this is worth doing.  If so, what's the root issue you're trying to solve; how long it takes to resolve a token from a username and password, having to manage properties containing username and password, etc.

**Comment by youngm** [comment]
@nebhale The main use case is.  I have users who interact with CF using the CLI and deploy their apps using the maven plugin.  It is really convenient to be able to run cli and maven commands interchangeably without having to manage 2 different auth mechanisms.  The options for maven are:

* put username and password as system properties when running commands (not a good idea)
* put credentials in your maven server.xml which is a pain to do and even more of a pain to do securely

If maven could simply share the cli's current token then users can log in interactively with the cli then interchangeably invoke cli and maven-cf-plugin commands without dealing with different ways to authenticate.

That said.  This feature has been broken for so long that most of my users that took advantage of this functionality have moved on and found different solutions.  In some cases the move they made was to migrate from the maven plugin to the cli and manifests for deployment automation.

Does that help?

**Comment by nebhale** [comment]
Yeah, that gives me a lot of insight.  Generally, if a properly integrated plugin existed, would there be a desire to use it?  Specifically, I'd sort of expected that the build plugins would be used in CI situations, but most developers would prefer the CLI when working locally.  Any thoughts?

**Comment by youngm** [comment]
@nebhale I would say that is not true for developers who want to remain consistent with their CI.  Honestly most developers don't push for development anyway they develop on their local machine then let CI deploy to CF.  Being able to duplicate what CI is doing easily from a dev box is mainly only useful when you are testing CI or debugging some issue.

It would be easier for developers to move between CLI and Maven if both supported a common configuration mechanism (e.g. CLI manifest.yml).  Perhaps it would be better to put effort into manifest support for the maven plugin over auth sharing?

**Comment by nebhale** [comment]
Yeah, there's discussion going about making the manifest format a contract that everyone can depend on.  I consider manifest support to be required for V2.  So why don't we close this issue out in lieu of first class manifest support?

**Comment by youngm** [comment]
@nebhale I'm good with that.  Thanks for talking this through with me.
