### ISSUE TITLE
Provide support for manifest.yml in vcap-java-client

### ISSUE THREAD

**Issue by davidehringer** [cloudfoundry/cf-java-client#18]
See http://blog.cloudfoundry.com/2012/01/10/simplified-application-deployment-with-cloud-foundry-manifest/

It would be nice if the vcap-java-client (or some additional module) supported deployment descriptions in the manifest.yml format.

Please let me know if this type of enhancement request should be filed or discussed somewhere else more appropriate.

**Comment by nebhale** [comment]
@davidehringer Heads up that the latest snapshots include pushing with a manifest.  Only took us four years to deliver it 😉.
