### ISSUE TITLE
No way to purge services

### ISSUE THREAD

**Issue by michaelklishin** [cloudfoundry/cf-java-client#182]
There is no way to purge a service and its dependent objects (what `cf purge-service-offering` does).
Service brokers and their support tools that build on top of this client need this feature.

I plan on contributing a pull request with this some time next week.

**Comment by nebhale** [comment]
/Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
