### ISSUE TITLE
Support HTTP proxies with Loggregator integration

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry/cf-java-client#194]
Loggregator integration via websockets is accomplished using a Tomcat embedded websockets library. This library does not currently support websockets via an HTTP proxy. As soon as a release of the library is available with proxy support, `cloudfoundry-java-client` should be modified to take advantage of it. 

See https://issues.apache.org/bugzilla/show_bug.cgi?id=55006

**Comment by nebhale** [comment]
@scottfrederick I'm going to close this out for now as it's tracked by https://www.pivotaltracker.com/story/show/100979980.  I've had a chat with Mark and he says that the Tomcat issue still hasn't bubbled up, but might soon.  I'm going to hold the issue until then (or until we come up with an alternate strategy).
