### ISSUE TITLE
Retain a specific number of deployed builds and remap a primary URL to the latest deployed build

### ISSUE THREAD

**Issue by loxal** [cloudfoundry/cf-java-client#199]
Something like this https://docs.google.com/a/loxal.net/file/d/0B2BBStu44q_AQ19faGZfdjhWN3c/edit

The idea is:
* having X (declarable) number of builds of the same app
* having two URLs, 
  * the primary one, pointing to the latest deployed build
  * the secondary URL, is unique and points to an individual build
* the mechanism is fail-safe, i.e. if a deployment fails, a subsequent deployment resolves the mess
...cf. screenshot. This deployment schema is currently used by some hybris / SAP teams.

I've implemented it here https://github.com/loxal/cf-java-client/blob/feature/sysLogDrainUrl-support/cloudfoundry-maven-plugin/src/main/java/org/cloudfoundry/maven/DeleteObsoleteBuilds.java

Would you consider to adopt this concept? If yes, I would cleanup the code and evtl. split the concept in two distinct goals.

**Comment by nebhale** [comment]
@loxal As the new PM on this, I'm looking over all of the issues in the repo with a fresh set of eyes.  As part of the ongoing V2 effort, we're trying to ensure that each project (in this case build plugin) has a clearly defined goal.  In this case, our clearly defined goals are to offer a subset of the CLI's functionality as it relates to the application built using Maven or Gradle.  This implies then that blue/green deployment is outside of that scope.

In truth, blue/green deployment isn't something that we should be handling at the build system, it should be handled at the platform layer.  And it is coming.  The work on routing services in CF is designed to facility things like blue/green deployment A/B testing, etc.

I'll leave this issue open for a bit to discuss, but we're planning on closing it out as won't fix.

**Comment by loxal** [comment]
@nebhale Nice to hear that it’s coming to the platform. Do you know something about the timeline of this feature?

**Comment by nebhale** [comment]
@loxal Unfortunately, I don't have a huge amount of insight into the dates around it.  I'd recommend asking on `cf-dev` where the PMs should be lurking.

**Comment by loxal** [comment]
Thanks a lot! I’m pretty sure the industry is waiting for this one! :+1:
