### ISSUE TITLE
Failed deployment of newly deployed apps (no redeployment of the same app)

### ISSUE THREAD

**Issue by loxal** [cloudfoundry/cf-java-client#200]
Sometimes I get failures like this:

#######
[WARNING] GET request for "https://api.cf1.hybris.com/v2/spaces/6b5bc8e9-0bfb-4252-ae74-b7f69c3865df/apps?inline-relations-depth=1&q=name:customer-dev-v1-v1-6-0-b1699999" resulted in 401 (Unauthorized); invoking error handler

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 14:16 min

[INFO] Finished at: 2014-07-03T03:14:42+02:00

[INFO] Final Memory: 15M/104M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.cloudfoundry:cf-maven-plugin:1.1.8.KIWI-RELEASE:push-only (default-cli) on project customer: Error while creating application 'customer-dev-v1-v1-6-0-b1699999'. Error message: '401 Unauthorized'. Description: 'Invalid Auth Token' -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.
#########

I guess it's related to the token handling mechanism and some timeout constants. Keep in mind the first deployment may take significantly more time as in some cases an entire local .m2 repository has to be created (which is not the root cause).

I'm investigating this issue right now

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
