### ISSUE TITLE
Maven plugin does not correctly identify existing applications

### ISSUE THREAD

**Issue by chrylis** [cloudfoundry/cf-java-client#205]
The `cf:apps` goal correctly identifies my existing application, but `cf:app` throws an NPE out of `org.cloudfoundry.maven.common.UiUtils.renderCloudApplicationDataAsTable(UiUtils.java:106)`, and `cf:push` clobbers my application's configuration (`applicationExists(application)` in the helper appears to be returning false erroneously).

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by chrylis** [comment]
Response? This is a year-old bug report that appears to have just been dropped on the floor...

**Comment by nebhale** [comment]
Yup, you're right. Closed out the wrong issue. Apologies.

**Comment by twoseat** [comment]
Hi @chrylis. With my apologies for the significant delay, we're now working on this issue. We have a fix for the first part of your problem, but I'd appreciate some clarification on the second half. Specifically:
a. Do you see part 2 only after part 1 has happened, or is it independent of part 1?
b. What configuration are you losing? For example is it service bindings, env. variables, urls, all of these?

**Comment by chrylis** [comment]
I have since stopped using the plugin because of these problems, but I *believe* that:

a. The two were independent, but I thought might share a common cause.
b. Anything that could be specified in the manifest seemed to get wiped.

**Comment by nebhale** [comment]
Completed in b74129b4f3d9fe1238bb16c071e6efa3947d689f.
