### ISSUE TITLE
Application environment variable with '=' in value not set.

### ISSUE THREAD

**Issue by nierajsingh** [cloudfoundry/cf-java-client#249]
Setting an application environment variable through:

public void updateApplicationEnv(String appName, Map<String, String> env)

in 

CloudFoundryClient

with an '=' in the value is not set, for example:

JAVA_OPTS "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"

This works fine with CLI version 6.6.2 and higher.

No exceptions are thrown.

**Comment by nierajsingh** [comment]
A junit to test the error is the following:

public void setEnvironmentThroughMapEqualSign() throws IOException {
		String appName = createSpringTravelApp("env4");
		CloudApplication app = connectedClient.getApplication(appName);
		assertTrue(app.getEnv().isEmpty());

		Map<String, String> env1 = new HashMap<String, String>();
		env1.put("bar", "baz=bazvalue");
		connectedClient.updateApplicationEnv(appName, env1);
		app = connectedClient.getApplication(app.getName());
		assertEquals(env1, app.getEnvAsMap());

		connectedClient.updateApplicationEnv(appName, new HashMap<String, String>());
		app = connectedClient.getApplication(app.getName());
		assertTrue(app.getEnv().isEmpty());
		assertTrue(app.getEnvAsMap().isEmpty());
	}

Error:

java.lang.AssertionError: expected:<{bar=baz=bazvalue}> but was:<{bar=null}>
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.failNotEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:128)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at org.cloudfoundry.client.lib.CloudFoundryClientTest.setEnvironmentThroughMapEqualSign(CloudFoundryClientTest.java:639)

**Comment by scottfrederick** [comment]
Fixed via #251.
