### ISSUE TITLE
space_guid information should be present on CloudApplication

### ISSUE THREAD

**Issue by tdemande** [cloudfoundry/cf-java-client#250]
Currently, a CloudApplication cannot be linked to a space, although when gettting the response from the Cloud Controller on the "/apps" endpoints, [this information is present] (http://apidocs.cloudfoundry.org/195/apps/list_all_apps.html). It looks like adding a simple field to CloudApplication (either simple type like String/GUID or complex CloudSpace) and getting the space_guid (adding something like *app.setSpaceGuid(getEntityAttribute(resource, "space_guid", String.class*) [somewhere near there] (https://github.com/cloudfoundry/cf-java-client/blob/e1849f64b558199f198560020e1ec96bd7c31052/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/util/CloudEntityResourceMapper.java#L157) )  could easily add this potentially valuable information.

**Comment by scottfrederick** [comment]
@tdemande Unfortunately, this won't be quite as clean as I'd like. The data returned from the CC Apps API endpoint includes the space GUID, as you said (along with several other GUIDs).

Populating a `CloudSpace` in `CloudApplication` using this info would require another round-trip to CC to get the details of the space. Adding another round trip to every `getApplication()` call would not be good, as this method is used a lot and it is already not very efficient. 

We could just save the space GUID in `CloudApplication` (and potentially the other GUIDs returned from the CC Apps API), but then you would need a `getSpace(UUID guid)` method to retrieve the space details yourself. This would be easy enough to implement, but the Java API doesn't expose GUIDs very much now, and starting to add `get` methods that take GUIDs for things along with the existing `get` methods that take names of things could cause a big increase in the number of methods in an already monolithic and cluttered Java API. 

Can I ask what your use case is for getting the space that an app is in? A default org and space are typically passed when [creating the Java client](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryClient.java#L89-L162), and all other operations are relative to that org and space. Are you doing something different with the API such that you don't already know the org and space the Java client is operating in?

**Comment by tdemande** [comment]
Here, we are using OAuth as authentication system, in order to get a CF user information about what he can actually see (Orgs, Spaces, Apps, Services especially). So [we are using this](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/CloudFoundryClient.java#L92-L94) to create the CloudFoundryClient. So no current session space to infer the space from.
As we also store all the visible spaces, this is not an issue (for us) to only get the GUID of the space in the CloudApplication as, as long as we retrieve the CloudSpaces first, this is easily available.

**Comment by scottfrederick** [comment]
> Populating a CloudSpace in CloudApplication using this info would require another round-trip to CC to get the details of the space.

@tdemande Turns out I was wrong here. All space data (not just space GUID) is present in the JSON response from the application fetch. So populating a `CloudSpace` in the `CloudApplication` was pretty easy. 

Fixed in https://github.com/cloudfoundry/cf-java-client/commit/8e9b2c946da183a4b2a8a353cd4b07013da82851
