### ISSUE TITLE
Provide updated API changes since 0.8.6

### ISSUE THREAD

**Issue by scurry** [cloudfoundry/cf-java-client#255]
As of 0.8.6, you provided good documentation on what we should expect for changes to the API (https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/API_changes.md).  However, it has not been updated for recent versions.   We are requesting that you provide updated documentation once 1.1.1 is released.

We have code that depends on the API and need to know what has changed so we can address any incompatibilities.

**Comment by scottfrederick** [comment]
Fixed in https://github.com/cloudfoundry/cf-java-client/commit/0d4c19015028bc80372bdfddef4d8f405f238624
