### ISSUE TITLE
used memory is less than 0 for application instances using InstanceStats.getUsage().getMem()

### ISSUE THREAD

**Issue by ZongqiangZhang** [cloudfoundry/cf-java-client#265]
The method InstanceStats.getUsage().getMem() return a value less than 0 when the actual memory usage is bigger than Integer.MAX_VALUE.

The variable type for Usage.mem and Usage.disk should be long instead of int.

**Comment by cgfrost** [comment]
Fixed with commit daab9ccbcc17af27d65a04b6d6fcbd38cf9f048e
