### ISSUE TITLE
getSpaceDevelopers(String spaceName) returns NPE in version 1.1.1

### ISSUE THREAD

**Issue by AndreasHeix** [cloudfoundry/cf-java-client#271]
Hi,
not sure if this is related to https://github.com/cloudfoundry/cf-java-client/issues/269.

Here's my code:
		CloudCredentials credentials = new CloudCredentials(user, password);
		client = new CloudFoundryClient(credentials, getTargetURL(target), true);
		client.login();
		//try to force more metadata, see https://github.com/cloudfoundry/cf-java-client/issues/269
		CloudSpace space = client.getSpace("foo");
		space.getOrganization();
		//now back to the call I really want to do
		List<UUID> developers = client.getSpaceDevelopers("foo");

However, I am getting an NPE in CloudControllerClientImpl:

	private List<UUID> getSpaceUserGuids(String spaceName, String urlPath) {
		UUID orgGuid = sessionSpace.getOrganization().getMeta().getGuid();

because the sessionSpace is "null".

It looks a little bit difficult to me anyhow, as there can be several spaces with the same name in a CF landscape albeit in different orgs. So: Wouldn't I have to specify the org as well when I want to retrieve details about a space?

Thanks and regards
Andreas

**Comment by scottfrederick** [comment]
@AndreasHeix That's a bug in `getSpaceUserGuids()`. Other `CloudFoundryClient` constructors allow you to pass a default org and space that operations can act on, which is what the `sessionSpace` field gets set from. `getSpaceUserGuids()` shouldn't assume that this field is always set.

I think you are right about specifying the org on this call. We can leave the current forms of the `getSpaceXxxx()` methods that just take a space name, and have them throw a more useful exception if the default org wasn't specified at construction. Then we can add another form of those methods that takes an org parameter to meet your use case. The same should be done with the `associateXxxxWithSpace()` methods.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/cloudfoundry/cf-java-client/commit/cca3986ba056bf1f79f4b73c594a0f02db2761f6 and https://github.com/cloudfoundry/cf-java-client/commit/26c32370b577d53b0123e77efd2ed09ee06bcd8c.
