### ISSUE TITLE
NPEs on null Environment Variable Values

### ISSUE THREAD

**Issue by MarkHerhold** [cloudfoundry/cf-java-client#273]
If an application has an environment variable value is set as an empty string, e.g. `NODE_ENV=`, a NPE will result [since this commit](https://github.com/cloudfoundry/cf-java-client/commit/80ede53db362c3eb3d54d3c246f65e445189e50a) was merged in.

This commit assumes that the environment variable values will always be a non-null, resulting in a NPE when `entry.getKey().toString()` is called. In the previous release this was not a problem because everything was assumed to be a String, making this a regression in my opinion.

**Comment by scottfrederick** [comment]
Closed via https://github.com/cloudfoundry/cf-java-client/pull/274
