### ISSUE TITLE
Whether the client can support Authorization Code way authentication?

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/cf-java-client#277]
Whether the client can support Authorization Code way authentication, I see here only way password authentication, if I want to use authorization_code authentication way, do you have any good Suggestions?

**Comment by nebhale** [comment]
@wdxxs2z How do you intend to get an `authorization_code` to configure the client with?

**Comment by wdxxs2z** [comment]
Hi @nebhale ,
In CloudCredentials,add two fields:
        
        private String code;	
        private String redirect_uri;
        public CloudCredentials(String clientId, String clientSecret, String code,String redirect_uri ,OAuth2AccessToken token) {
		this.clientId = clientId;
		this.clientSecret = clientSecret;
		this.code = code;
		this.redirect_uri = redirect_uri;
		this.token = token;
	}

and in OauthClient: may add a function createAccessCodeToken

        public OAuth2AccessToken createAccessCodeToken(CloudCredentials credentials) {
		HttpHeaders headers = new HttpHeaders();
		headers.add("Content-Type", "application/json;charset=utf-8");
		headers.add("accept", "application/json");
		String base = credentials.getClientId() + ":" + credentials.getClientSecret();
		String base64 = Base64.encodeBase64String(base.getBytes());
		headers.add("Authorization", "Basic " + base64);
		Map<String, Object> body = new HashMap<String, Object>();
		body.put("code", credentials.getCode());
		String jsonBody = JsonUtil.convertToJson(body);
		HttpEntity<String> httpEntity = new HttpEntity<String>(jsonBody, headers);
		
		ResponseEntity<String> accessToken = restTemplate.postForEntity(authorizationUrl + "/oauth/token?"
				+ "grant_type=authorization_code"
				+ "&redirect_uri=" + credentials.getRedirect_uri()
				+ "&code=" + credentials.getCode(), 
				httpEntity, String.class);
		Map<String, Object> tokenMap = JsonUtil.convertJsonToMap(accessToken.getBody());
		String access_token = (String)tokenMap.get("access_token");
		Integer expires_in = (Integer)tokenMap.get("expires_in");
		String token_type = (String)tokenMap.get("token_type");
		String refresh_token = (String)tokenMap.get("refresh_token");
		long expires_in_time = expires_in;
		DefaultOAuth2AccessToken token = new DefaultOAuth2AccessToken(access_token);
		token.setExpiration(new Date(expires_in_time * 1000 + System.currentTimeMillis()));
		token.setTokenType(token_type);		
		Map<String,Object> info = new HashMap<String, Object>();
		info.put("message", "This is code token grant type");
		token.setAdditionalInformation(info);
		DefaultOAuth2RefreshToken refreshToken = new DefaultOAuth2RefreshToken(refresh_token);
		token.setRefreshToken(refreshToken);
		return token;
	}

**Comment by nebhale** [comment]
@wdxxs2z My question was more of where you're going to get the token in the first place?  I know how it would be integrated, but how would you produce it in the first place?

**Comment by nebhale** [comment]
Just chatted with the UAA team and we'll definitely do this work in V2.  You can track its progress [here](https://www.pivotaltracker.com/story/show/106214548).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
