### ISSUE TITLE
As CLI does, add any user to a space.

### ISSUE THREAD

**Issue by o-orand** [cloudfoundry/cf-java-client#278]
Client-lib should allow user with enough privilege to assign another user to a space.

For me it's not clear how can I get user guid from a username with client lib. 

The CLI is using UAA to retreive user guid
```
GET /Users?attributes=id,userName&filter=userName+Eq+%22aValidUsername%22 HTTP/1.1
Host: uaa.xxx.com
```
Once you've got the user guid , it's almost done.

CC API only provides a way to get all user using GET /v2/users for an organization (it's look like  the most appropriate filter). And search for the username in the returned list. Do you have other ideas ?

Regards,
 Olivier

**Comment by wdxxs2z** [comment]
If you want associate an user to an org or a space,first you need config the uaa.yml and find the client id "cloud_controller_username_lookup"
cloud_controller_username_lookup:
      id: cloud_controller_username_lookup
      authorities: scim.userids
      authorized-grant-types: client_credentials
      secret: c1oudc0w
and modify the userids_enabled: false to userids_enabled: true.

Then you can use your response body entity attribute name: username.
But in cloud controller api, there is no filter username. Cups!!

**Comment by o-orand** [comment]
Thanks @wdxxs2z.
In fact, it seems not a good idea to use UAA as I won't be able to query it on PWS public instance (see https://github.com/cloudfoundry/cli/issues/444). 
Using CC API to get users and then filter looks like the best option. Endpoint ```/v2/users``` requires  admin right, so the only way to get username and user guid, is to use ```/v2/organizations/{guid}/users```.

**Comment by wdxxs2z** [comment]
So we can't use /v2/users and /v2/users/{guid}/summary  api ,just can use such as /v2/organizations/{guid}/users,/v2/organizations/{guid}/managers ... apis.
