### ISSUE TITLE
Update an existing service

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry/cf-java-client#283]
Currently it is not possible to update an existing service with the client-lib, since CloudFoundryClient does not offer methods such as `updateService()` or `updateUserProvidedService()`. I believe that updating a service is not the same as deleting it and creating it again since existing application bindings would be affected by the deletion.
Is such functionality planned? Would you accept pull requests for it?

**Comment by davidehringer** [comment]
@stoyanr  Note that when you update a service existing, existing bindings will not see that update, which might not be what you want.  So the general process flow is to update the service, unbind it from apps, and then rebind it to apps.

We have implemented `updateUserProvidedService()`, along with a bunch of other functionality, in an internal fork of the cf-java-client.  We are exploring how we can contribute some or all of that back to the project.

**Comment by scottfrederick** [comment]
> I believe that updating a service is not the same as deleting it and creating it again 

Deleting and recreating a service is certainly different from just updating. For managed (i.e. non-user-provided) services, deleting an instance will release all resources and destroy associated data. Deleting and recreating is obviously less destructive. 

> since existing application bindings would be affected by the deletion.

What @davidehringer said above. Deleting/recreating and updating both require unbinding, rebinding, and restarting any bound apps before they will pick up the change to a service instance. 


> Is such functionality planned? 

Everything that is planned for the CF java client is captured in these GitHub issues. There wasn't previously an issue to capture this work, but this issue will serve that purpose now. 

> Would you accept pull requests for it?

Yes, certainly. PRs are always welcomed and appreciated.

**Comment by nebhale** [comment]
@stoyanr This support will be added as part of the V2 effort.  You can track its progress [here](https://www.pivotaltracker.com/story/show/101451550).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
