### ISSUE TITLE
Upload application as an asynchronous operation

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry/cf-java-client#284]
Currently it is not possible to upload an application with the client-lib as an asynchronous operation, since the implementation of `uploadApplication()` in `CloudControllerClientImpl` is blocking. Since uploading a large application may take a fairly big amount of time (e.g. several minutes) I believe an asynchronous implementation would be very useful.
Is such functionality planned? Would you accept pull requests for it?
Background: We use a workflow engine (Activiti) to control an application deployment process. The engine only allows service tasks to run for few minutes before restarting them, therefore any long-running operations have to be performed asynchronously, started in one task and the status polled in the next task. It's not possible to spawn a thread for the long-running operation since the next task that polls the status can be executed in a different VM.

**Comment by scottfrederick** [comment]
The forms of `uploadApplication()` currently support getting callbacks for upload status, but not true async behavior. There are no plans to add true async, but we would consider a PR for this. 

The actual process of uploading the bits is currently async within the library, this just isn't exposed by the API. The process of [uploading a directory or archive](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L1378-L1398) is roughly this: 

1. Get the list of files in the directory (if uploading a directory, which is not common with Java but is with other apps like Ruby or Node.js) or in the archive (jar, war, zip). 
2. Send the list of files to CF to see if any of them have been previously uploaded. 
3. Create a list of files in the directory or archive that have not been previously uploaded. 
4. Asynchronously upload each file as a multi-part PUT. 

If that step 4 could be exposed via the API in a  clean way, it could be generally useful.

**Comment by veronicfang** [comment]
@scottfrederick  we face a problem when we upload a java application(a war pacakage),it always show a 502 bad gateway exception, my package size is about 14M. We use the four steps as you mentioned, but it seems doesn't work,can you give me some suggestions? And can you explain me about the "clean way " int the  "If that step 4 could be exposed via the API in a clean way" ,?

**Comment by scottfrederick** [comment]
> we face a problem when we upload a java application(a war pacakage),it always show a 502 bad gateway exception, my package size is about 14M. We use the four steps as you mentioned, but it seems doesn't work,can you give me some suggestions? 

The `502 bad gateway` error usually means something is timing out the long-lived connection being used for uploading. I regularly upload > 45M jar files with the client lib, so I don't think it is a problem in the library, but likely something in the networking, HAProxy, or Router.

> And can you explain me about the "clean way " int the "If that step 4 could be exposed via the API in a clean way" ,?

I just meant that someone would need to spend some time looking more closely at that code and designing the API changes. I haven't done that.

**Comment by nebhale** [comment]
@stoyanr As part of the V2, the API is being redesigned to be reactive and non-blocked.  Snapshots today are reactive, but still blocking (using Spring's `RestTemplate`).  Before final release we're going to update that to be non-blocking as well.  We won't be making these changes in the V1 line so I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
