### ISSUE TITLE
The oauthClient changePassword  function maybe too old.

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/cf-java-client#288]
The uaa changepassword restful api is /Users/{id}/password , and the uaa api description is too simple.

**Comment by wdxxs2z** [comment]
After my test, if coupled with “ body.put("schemas", new String[] {"urn:scim:schemas:core:1.0"}); ” will be submitted to the 400 bad request  error, so I think we should remove it.

**Comment by nebhale** [comment]
The UAA isn't within scope of this project any longer.
