### ISSUE TITLE
Pushing folders destroys folder hierarchy

### ISSUE THREAD

**Issue by MagicTucura** [cloudfoundry/cf-java-client#290]
Hello,

I pushed a folder with the plugin to CF but it seems that the folder hierarchy gets destroyed.

**For example**: I have a folder *test1* and it contains two subfolders: *test2* and folder *test3*. Folder *test2* contains an image file *test.png*.
The folder *test2*, *test3* will be placed into *test1*, however the image will also be placed into the parent folder but the filename will be changed into *test2\test.png*. So the file will not be placed into the folder but renamed to contain the parent folder name itself. Please note the changed slash in the filename.

I will add screenshots with my specific folder hierarchy and the result after the push to cf.
![cmd1hierarchy](https://cloud.githubusercontent.com/assets/11677644/8405273/82678312-1e53-11e5-8283-9d08589fbebe.png)
![imdoc folder hierarchy](https://cloud.githubusercontent.com/assets/11677644/8405275/8429fe8c-1e53-11e5-8313-5b278597f006.png)

Like you can see the folders developer-guide, specifaction and user-guide are copyied into the parent as a folder, the should contain 2 files and one folder but if i check them they contain nothing.

Can it be that the maven plugin doesnt understand the windows seperator?

Kind regards

Tucura

**Comment by MagicTucura** [comment]
It is working on Linux operating system. I guess the file separator is not working with windows

**Comment by glyn** [comment]
@MagicTucura: which version of Windows are you using? I know this probably doesn't matter, but it might.

Also, please could you describe how to recreate the problem. I don't want to go chasing the wrong bug. ;-) If you can provide a minimal sample project to recreate, that would be very helpful.

**Comment by glyn** [comment]
A unit test was able to reproduce this problem, or at least something very similar. The test and fix are [here](https://github.com/cloudfoundry/cf-java-client/commit/c2dd465c0b8c644cbffab7050ff0dfcade6485c8).

**Comment by glyn** [comment]
Please note that the fix will not appear in a built version of the Maven plugin until such is released from the 1.x branch.

**Comment by glyn** [comment]
Leaving open until the fix is available for testing.

**Comment by nebhale** [comment]
@MagicTucura We've pushed a snapshot version of the plugin to `http://repo.spring.io/snapshot` for you to test.  It should be `1.1.4.BUILD-SNAPSHOT`.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
