### ISSUE TITLE
Proxy servers with required authentication

### ISSUE THREAD

**Issue by farioas** [cloudfoundry/cf-java-client#292]
Currently both maven and gradle plugin not supports Digest authentication scheme in Proxy

Maven:
mvn -Dproxy.user=user -Dproxy.password=pass -Dhttps.proxyHost=proxy.host.com -Dhttps.proxyPort=3128 cfPush

[WARNING] GET request for "https://someapi/info" resulted in 407 (Proxy Authentication Required); invoking error handler

Gradle:
gradle cfPush -Dproxy.user=user -Dproxy.password=pass -Dhttps.proxyHost=proxy.host.com -Dhttps.proxyPort=3128

GET request for "https://someapi/info" resulted in 407 (Proxy Authentication Required); invoking error handler

**Comment by nebhale** [comment]
@farioas It would appear that you're configuring a username and password for the proxy.  This doesn't seem to match with the digest authentication scheme you describe.  Can you please explain a little more?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
