### ISSUE TITLE
cfPush clears all bound services

### ISSUE THREAD

**Issue by apetherick** [cloudfoundry/cf-java-client#293]
When using the cf push command line tool, any bound services are not cleared. However, in this plugin cfPush clears all bound services.

**Comment by scottfrederick** [comment]
@apetherick The gradle and maven plugins aren't meant to completely mimic the behavior of the `cf` CLI. The CLI lets you specify some of the metadata for an application in `manifest.yml`, but not everything. The gradle and maven plugins expect all app metadata to be expressed in the build file. 

As an example, the CLI lets you specify the names of services that should be bound to the app at push, but not all the details necessary to create the service instance - it expects the service instance to be created with a separate CLI command (e.g. `cf create-service` or `cf create-user-provided-service`). The gradle and maven plugins allow you to specify all service instance details and will create the service instance if necessary before binding it to the app at push. As such, the plugins expect the configuration block in the build file to be a complete picture of what the app metadata should look like. 

Can you explain your use case for pushing an app once with the gradle plugin with a service specified in the build file, then pushing again without that service specified in the build file?

**Comment by apetherick** [comment]
Yes, perhaps I posted a little early. I've started using it more and have a feel for the way it's meant to be used now, thank you for your help.
