### ISSUE TITLE
Support for Encrypting Settings Password

### ISSUE THREAD

**Issue by esheri3** [cloudfoundry/cf-java-client#295]
The maven plugin works when the Cloud Foundry username and password are stored in the clear within settings-security.xml. However, attempts to encrypt the password using the following reference is failing: https://maven.apache.org/guides/mini/guide-encryption.html. I'm getting a "403 Access token denied" message. Does the maven plugin support encrypted password in settings-security.xml (and I'm just doing something wrong)?

**Comment by trung** [comment]
Hmm, it works for me. I have encrypted password stored in settings.xml.
I'm using plugin version 1.0.4

**Comment by nebhale** [comment]
@esheri3 Have you tried with the latest version of the plugin?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
