### ISSUE TITLE
Maven Plugin stacks support

### ISSUE THREAD

**Issue by BLaurent** [cloudfoundry/cf-java-client#297]
Hi,
is there a way to set the stack ( stack: cflinuxfs2 ) via maven plugin ?

Regards
Ben

**Comment by scottfrederick** [comment]
Yes, you can add a `stack` element to the configuration block for the app: https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-maven-plugin/src/main/java/org/cloudfoundry/maven/AbstractApplicationAwareCloudFoundryMojo.java#L117-L122.

**Comment by BLaurent** [comment]
Brilliant
Thanks

**Comment by PatelParas** [comment]
Thanks Eclipse CF plugin need this emplementaion
