### ISSUE TITLE
401

### ISSUE THREAD

**Issue by carrieysn** [cloudfoundry/cf-java-client#298]
use this  getOrgAuditors       org.cloudfoundry.scc.client.CloudFoundryException: 401 Unauthorized (Invalid Auth Token)

**Comment by scottfrederick** [comment]
@carrieysn We will need more information than this to understand what is going on. Are other client library methods working for you, and only this one failing? Are the credentials you are using to authenticate to CF valid?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
