### ISSUE TITLE
cf-maven-plugin overwrites cf env variables

### ISSUE THREAD

**Issue by csikosbalint** [cloudfoundry/cf-java-client#321]
Hi, I try to use the app variables for api_key/api_secret values. I would like to set-env these and still use the cf-maven-plugin for deployment, but the plugin overwrites the env varibales, so I have to put these sensitive info into the pom.xml but this way I cannot upload it into a remote cvs.
Am I miss-using the plugin or is a developement possible when the plugin only adds/checks specified variable and makes no change for the existing one?

Bests,
Balint

**Comment by nebhale** [comment]
@Zteve Is this issue covered by the work you did on #205?

**Comment by Zteve** [comment]
@nebhale With the fix to issue https://github.com/cloudfoundry/cf-java-client/issues/205 the rule is: if you don't specify any env variables in the `pom.xml` (or the command line) then existing env variables will not be touched.  A subsequent `cf-push` can then leave vars already set.

This does mean _any_ env variables, so no other variables can be set in the pom ether.

**Comment by nebhale** [comment]
@csikosbalint Does @Zteve's solution handle your issue?  Is it sufficient that you never set any environment variables in the POM?

**Comment by csikosbalint** [comment]
Thanks for the answers. For me the ideal flow would be a configuration option with values like 'increment' and 'overwrite'. But now I use the cf-client-java library so I can handle this from there and do the merge if necessary, so this is not an urgent issue any more.
I hope I could give valuable feedback for a future improvement if you agree with this. 
Thank you again, I find the issue resolved this way.
