### ISSUE TITLE
org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable

### ISSUE THREAD

**Issue by soumee** [cloudfoundry/cf-java-client#324]
I am using the cloud foundry java sdk to deploy applications.
Today when I tried to deploy an application it got uploaded and also started successfully. However when I try to get the application status I get the following error. Need help with diagnosing the issue.

29 Oct 2015 09:09:44,855 [WARN] org.cloudfoundry.client.lib.rest.LoggingRestTemplate - GET request for "https://api.run.pivotal.io/v2/apps/6ee041c9-97c4-42ec-a4db-da61bf9c0ae4/stats" resulted in 503 (Service Unavailable); invoking error handler

org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable\n\tat org.cloudfoundry.client.lib.rest.CloudControllerResponseErrorHandler.handleError(CloudControllerResponseErrorHandler.java:26)\n\tat org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:557)\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:515)\n\tat org.cloudfoundry.client.lib.rest.LoggingRestTemplate.doExecute(LoggingRestTemplate.java:54)\n\tat org.springframework.web.client.RestTemplate.execute(RestTemplate.java:480)\n\tat org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:245)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getInstanceInfoForApp(CloudControllerClientImpl.java:941)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.doGetApplicationStats(CloudControllerClientImpl.java:927)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getRunningInstances(CloudControllerClientImpl.java:906)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.mapCloudApplication(CloudControllerClientImpl.java:894)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getApplication(CloudControllerClientImpl.java:877)\n\tat org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.getApplicationStats(CloudControllerClientImpl.java:919)\n\tat org.cloudfoundry.client.lib.CloudFoundryClient.getApplicationStats(CloudFoundryClient.java:230)\n\tat 

Thanks

**Comment by nebhale** [comment]
Duplicated of #322 and #323.  This is a bug in the Cloud Controller and is covered by a bug with that time.

**Comment by soumee** [comment]
Is there a time line when the fix will be available?

**Comment by nebhale** [comment]
The issue https://www.pivotaltracker.com/story/show/106702544 and can be tracked there.  You'll need to connect with the CAPI team to find out their ETA.

**Comment by soumee** [comment]
Ok. I am new to this process. Can you help me out with how can I connect with the CAPI team?. We have production code which are now failing.

**Comment by nebhale** [comment]
The cf dev list (https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/) might be a good place to start.

**Comment by nebhale** [comment]
I believe that [opening an issue](https://github.com/cloudfoundry/cloud_controller_ng/issues) in the `cloud_controller_ng` repository will also get their attention.
