### ISSUE TITLE
SpringCloudFoundryClient: skip ssl verification

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cf-java-client#326]
Calling builder without providing a value for skipSslValidation leads to a NullPointerException.
Please replace
```java
!Optional.of(skipSslValidation).orElse(false)
```
by
```java
!Optional.ofNullable(skipSslValidation).orElse(false)
```
Thanks!

**Comment by nebhale** [comment]
Closing in lieu of #325.  Turns out that the original issue was dead on, and I was wrong.
