### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry/cf-java-client#331]
Can we tag this commit with 1.1.3? https://github.com/cloudfoundry/cf-java-client/commit/202126c5ea2285c21434e136ecec882d68fd69e3

**Comment by nebhale** [comment]
Hmm...  It seems like there aren't any tags at all in here.  Any idea why that is @scottfrederick?

**Comment by nebhale** [comment]
26 releases worth of history [invented](https://github.com/cloudfoundry/cf-java-client/releases).
