### ISSUE TITLE
[Question] How to communicate with Cloud Controller properly using CloudFoundryClient

### ISSUE THREAD

**Issue by LeeU1911** [cloudfoundry/cf-java-client#332]
Hey,

Our goal is to communicate with Cloud Controller in order to get roles at organization level of a particular Cloud Foundry user (roles can be users, auditors or managers). A prerequisite of this is to implement OAuth2 flow to authenticate the user with CloudFoundry UAA server.

OAuth2 flow has been implemented using spring-security-oauth2 library, which means the app redirects to UAA server for user's authentication then retrieve the access token correctly. 

Our current solution is after authentication, we make another call to Cloud Controller using CloudFoundryClient. At the moment, we use access token value that is stored in OAuth2AuthenticationDetails object within SecurityContext to build CloudCredentials so this call is authenticated with Cloud Controller. 

Because there is no expiration date value of token available in the SecurityContext (spring-security-oauth2 lib only extracts the access token value and type then store in Authentication object), CloudFoundryClient tries to refresh the token since it thinks token has expired due to null value of expiration date. 

At that point, refresh token is not available either, so a null pointer exception is thrown. 

Of course, another solution is to use RestTemplate to call Cloud Controller without using CloudFoundryClient at all but we would love to hear your suggestions. Thank you!

Code snippet as below:
```java
URL cloudControllerUrl;
  	CloudFoundryClient client = null;
  	try {
  	    cloudControllerUrl = new URL("<Cloud_Controller_URL");
  	    OAuth2Authentication o = (OAuth2Authentication) SecurityContextHolder.getContext().getAuthentication();
  	    OAuth2AuthenticationDetails d = (OAuth2AuthenticationDetails) o.getDetails();
  	    OAuth2AccessToken token = new DefaultOAuth2AccessToken(d.getTokenValue());
  	    CloudCredentials credentials = new CloudCredentials(token);
  	    client = new CloudFoundryClient(credentials, cloudControllerUrl, true);
  	    
  	} catch (MalformedURLException e) {
  	    e.printStackTrace();
  	}
  	return client;
```

**Comment by nebhale** [comment]
At the moment we don't currently address the "delegation" to incoming tokens in the client.  We certainly wouldn't add that support to the V1 API (which you're using in the example), but it's something that we can consider for the V2 API.  There's a bit of a mismatch as creation of a `CloudFoundryClient` is supposed to happen once and then be reused in a multi-threaded manner.  Changing the outgoing token for each request is a bit of a step away from that.  Not insurmountable, but it means some interesting changes to the user expectations about the class.

**Comment by o-orand** [comment]
Hi @nebhale ,
It seems not possible to create a `SpringCloudFoundryClient` using an Oauth 2 token using new V2 API, as in the snippet above. Am I wrong ?

Do you think it is a bad idea to have multiple `CloudFoundryClient` as we've done here:
https://github.com/Orange-OpenSource/elpaaso-sandbox-service/blob/master/src/main/java/com/orange/clara/cloud/services/sandbox/ElpaasoSandboxServiceApplication.java#L46-L67

Thanks

**Comment by nebhale** [comment]
@o-orand The `Reactor*Client` builders now [take a `tokenProvider`](http://docs.cloudfoundry.com/cf-java-client/api/latest-snapshot/cloudfoundry-client-reactor/org/cloudfoundry/reactor/client/ReactorCloudFoundryClient.Builder.html#tokenProvider-org.cloudfoundry.reactor.TokenProvider-) argument which allows you to implement any strategy for providing an OAuth Token.  At the moment we only provide a [`PasswordGrantTokenProvider`](http://docs.cloudfoundry.com/cf-java-client/api/latest-snapshot/cloudfoundry-client-reactor/org/cloudfoundry/reactor/tokenprovider/PasswordGrantTokenProvider.html) but will definitely provide additional implementations.  If you do implement one that extracts from Spring Security's context, please let us know and we'd be happy to incorporate it.

**Comment by o-orand** [comment]
@nebhale great, thanks ! I'll have a look in a couple of weeks.
