### ISSUE TITLE
API endpoints with port number are not supported

### ISSUE THREAD

**Issue by mpermar** [cloudfoundry/cf-java-client#333]
Hi guys, 

It looks like the Java client does not support API endpoint with port numbers on them. The following endpoint/domain pair works from the command line:

```
[root@martins-build-box ~]# cf api
API endpoint: http://api.sandbox6.mydomain.com:8181 (API version: 2.23.0)
[root@martins-build-box ~]# cf domains
Getting domains in org myorg as myorg-admin...
name                     status
sandbox6.mydomain.com   shared
wbx2.com                 shared
[root@martins-build-box ~]#
```

However, from the Java client to connecting to such endpoint as "http://api.sandbox6.mydomain.com:8181" will fail. This is because CloudControllerClientImpl's extractUriInfo compares the URI's authority to the domain. But authorities can have port numbers and therefore never finds a match and fires an IllegalArgumentException

Should you need it the following code will reproduce the issue:
```
	public void testCloudControllerImpl() {

		Map<String, String> uriInfo = new HashMap<String, String>(2);
		String uri = "http://foo-3-6007.sandbox6.mydomain.com:8181";
		Map<String, UUID> domains = new HashMap<String, UUID>();
		domains.put("sandbox6.mydomain.com", UUID.randomUUID());
		domains.put("anotherdomain.com", UUID.randomUUID());
		
		CloudControllerClientImpl impl = new CloudControllerClientImpl();
		impl.extractUriInfo(domains, uri, uriInfo);
	}
```

**Comment by nebhale** [comment]
Fixed.

**Comment by mpermar** [comment]
Thanks @nebhale. Any idea when this might make it to a maven artifact release?

**Comment by nebhale** [comment]
We're closing in on a V1 maintenance release.  I think it'll be before the new year, but make no promises. :smile:

**Comment by mpermar** [comment]
Fair enough. I'll keep an eye on it.
