### ISSUE TITLE
[Question] stream.next.get() returns null

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cf-java-client#336]
Trying to test the get application (and get service instance), I implemented in two different way:
### In a consume way
```java
Publisher<GetApplicationResponse> publisher = this.client
  .applicationsV2().get(GetApplicationRequest.builder().id(applicationId).build());
Stream<GetApplicationResponse> stream = Streams.wrap(publisher);
stream.consume(response -> {
       assertThat(response, is(notNullValue()));
       assertThat(response.getMetadata(), is(notNullValue()));
       assertThat(response.getEntity(), is(notNullValue()));
       assertThat(response.getMetadata().getId(), is(equalTo(applicationId)));
       log.debug("get_application_consume - {} found", response.getEntity().getName());
   }, t -> {
       log.debug("get_application_consume - " + applicationId + " - error", t);
       fail(t.getMessage());
 }, v -> log.debug("get_application_consume - {} - end", applicationId));
```
It ends with following output
```
DEBUG o.c.integrationclient.Sandbox(98) - get_application_consume
DEBUG o.c.integrationclient.Sandbox(81) - Building to api.nd-cfapi.itn.ftgroup
DEBUG o.c.integrationclient.Sandbox(81) - Building to api.nd-cfapi.itn.ftgroup
DEBUG o.c.integrationclient.Sandbox(107) - get_application_consume - static_test found
DEBUG o.c.integrationclient.Sandbox(111) - get_application_consume - 3a4e9275-e937-4735-b272-84ddea21b1f6 - end
```
So far, so good

### In a get way with promise
```java
Publisher<GetApplicationResponse> publisher = this.client
                .applicationsV2().get(GetApplicationRequest.builder().id(applicationId).build());
Stream<GetApplicationResponse> stream = Streams.wrap(publisher);
GetApplicationResponse response = stream.next().get();
assertThat(response, is(notNullValue()));
assertThat(response.getMetadata(), is(notNullValue()));
assertThat(response.getEntity(), is(notNullValue()));
assertThat(response.getMetadata().getId(), is(equalTo(applicationId)));
log.debug("get_application_get - {} found", response.getEntity().getName());
```
And it fails because ```response ``` is null.
```
DEBUG o.c.integrationclient.Sandbox(81) - Building to api.nd-cfapi.itn.ftgroup
DEBUG o.c.integrationclient.Sandbox(117) - get_application_get
Expected: is not null
     but: was null
java.lang.AssertionError: 
Expected: is not null
```

In both test I use the same applicationId. Does anybody has an idea?

**Comment by nebhale** [comment]
This is down to the fact that the library is asynchronous.  Calling `.get()` before the call has actually returned returns `null`.  A call to `.poll()` instead would block until a success or failure event happened.  In general, we wouldn't recommend using the `Promise` style, but rather take a look at how the `TestSubscriber` [is implemented][i] (with a `CoundDownLatch`) and [used][u] (with `.subscribe()`).

[i]: https://github.com/cloudfoundry/cf-java-client/blob/master/test-utils/src/main/java/org/cloudfoundry/utils/test/TestSubscriber.java#L98-L105
[u]: https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-spring/src/test/java/org/cloudfoundry/client/spring/loggregator/LoggregatorMessageHandlerTest.java#L54-L64

**Comment by antechrestos** [comment]
@nebhale Thank you!

**Comment by smaldini** [comment]
Note that .get() has changed to be blocking since today :) and the Read only Promise super class has been introduced in the latest snapshot (reactor.Mono, returned by next(), where Stream#promise() performs the older task returning a Promise).
