### ISSUE TITLE
[Question]  Will this release be published to the maven repository in the near future?  Thanks

### ISSUE THREAD

**Issue by sboyatsis** [cloudfoundry/cf-java-client#337]

**Comment by nebhale** [comment]
What release are you looking for?

**Comment by sboyatsis** [comment]
Sorry.  The latest 1.1.4RELEASE

**Comment by nebhale** [comment]
The Artifactory server we use was acting up yesterday, but I've just published it now.  `1.1.4.RELEASE` should be available in `repo.spring.io/release`.
