### ISSUE TITLE
updateApplicationUris not mapping route correctly 

### ISSUE THREAD

**Issue by sboyatsis** [cloudfoundry/cf-java-client#351]
Most likely a very unique scenario but we have a cloud organization with with the following domains available.

`sandbox.lmig.com`
`pdc.sandbox.lmig.com`

An application was trying to add a URI to an application with this URI:
`stevebspringmusic-pdc.sandbox.lmig.com`

When using the `updateApplicaitonUris` method specifying that URI the result is that the domain of `pdc.sandbox.lmig.com` is used with a host of `stevebspringmusic` .  The mapped route is incorrectly created as 

`stevebspringmusic.pdc.sandbox.lmig.com`

Desired result would be with the dash instead of .  (`stevebspringmusic-pdc.sandbox.lmig.com`)

In looking at cf client code it looks like the `extractUriInfo` function logic may need to be re-worked.  It determines that domain is `pdc.sandbox.lmig.com` and then grabs host name by subtracting 1 assuming that character is a "."  .  I've verified this behavior occurs in releases 1.1.2, 1.1.3, and 1.1.4.RELEASE.  I used this code segment to recreate the issue.

```
package com.lmig.cf.cfclienttest;
import org.cloudfoundry.client.lib.CloudCredentials;
import org.cloudfoundry.client.lib.CloudFoundryClient;
import org.cloudfoundry.client.lib.domain.CloudSpace;
import org.cloudfoundry.client.lib.CloudFoundryException;
import org.cloudfoundry.client.lib.CloudFoundryOperations;
import org.cloudfoundry.client.lib.StartingInfo;
import org.cloudfoundry.client.lib.domain.ApplicationStats;
import org.cloudfoundry.client.lib.domain.CloudApplication;
import org.cloudfoundry.client.lib.domain.CloudDomain;
import org.cloudfoundry.client.lib.domain.CloudInfo;
import org.cloudfoundry.client.lib.domain.CloudRoute;
import org.cloudfoundry.client.lib.domain.CloudService;
import org.cloudfoundry.client.lib.domain.CloudServiceOffering;
import org.cloudfoundry.client.lib.domain.Staging;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;


/**
 * Testing misc cloudfoundry java client functions
 *
 */
public class App 
{
    public static void main( String[] args )
    {
    	String target = "https://api.sandbox.sys.paas.lmig.com" ;
        String user = "n0001010" ;
        String password = "xxxxx" ;
        String uri;
        int i;
        List<String> appURIs = new ArrayList<String>();
           

        CloudCredentials credentials = new CloudCredentials(user, password);
        CloudFoundryClient client = new CloudFoundryClient(credentials, getTargetURL(target),"n0001010", "sandbox",false);


        client.login();
        
        appURIs.add("stevebspringmusic-pdc.sandbox.lmig.com");
        appURIs.add("stevebspringmusic.sandbox.paas.lmig.com");

        client.updateApplicationUris("spring-music",appURIs);

        CloudApplication myapp = client.getApplication("spring-music"); 
       
        appURIs = myapp.getUris();
        i = 0;
        uri = appURIs.get(i);
        int num_items = appURIs.size();
        while (i < num_items) {
        	System.out.printf("app URI is %s\n",uri);
        	i = i+1;
        	if (i < num_items)
        		uri = appURIs.get(i);
        }
    }
```
    private static URL getTargetURL(String target) {
        try {
            return URI.create(target).toURL();
        } catch (MalformedURLException e) {
            throw new RuntimeException("The target URL is not valid: " + e.getMessage());
        }
    }
}

**Comment by nebhale** [comment]
@LokeshN As you're aware, all development effort has moved to V2 so we won't be fixing this issue from V1.  If this is still an issue for you in V2, please open another issue against it.
