### ISSUE TITLE
UploadStatusCallback not able to get the status of the file upload properly

### ISSUE THREAD

**Issue by LokeshN** [cloudfoundry/cf-java-client#363]
I am using CloudFoundryClient to upload a war file and using an Custom implementation of UploadStatusCallback to get whether the upload has finished successfully or failed. But the success/failure has not been reported back to the callback.

**Code in CloudControllerClientImpl.java:**

**In the below method, when the job status indicates FAILED or FINISHED it has not been updated back to UploadStatusCallback using  callback.onProgress(..) method.**

```java
private void processAsyncJob(Map<String, Object> jobResource, UploadStatusCallback callback) {
		CloudJob job = resourceMapper.mapResource(jobResource, CloudJob.class);
		do {
			boolean unsubscribe = callback.onProgress(job.getStatus().toString());
			if (unsubscribe) {
				return;
			}
			if (job.getStatus() == CloudJob.Status.FAILED) {
				return;
			}
			try {
				Thread.sleep(JOB_POLLING_PERIOD);
			} catch (InterruptedException ex) {
				return;
			}
			ResponseEntity<Map<String, Object>> jobProgressEntity =
					getRestTemplate().exchange(getUrl(job.getMeta().getUrl()),
						HttpMethod.GET, HttpEntity.EMPTY,
						new ParameterizedTypeReference<Map<String, Object>>() {});
			job = resourceMapper.mapResource(jobProgressEntity.getBody(), CloudJob.class);
		} while (job.getStatus() != CloudJob.Status.FINISHED);
	}
```
Could you please change the code, so that during failure/success scenarios users will get the callback for the same.

Thanks,
Lokesh

**Comment by nebhale** [comment]
@LokeshN As you're aware, all development effort has moved to V2 so we won't be fixing this issue from V1.
