### ISSUE TITLE
java.lang.ClassNotFoundException: reactor.core.publisher.SchedulerGroup

### ISSUE THREAD

**Issue by jamesmasters2** [cloudfoundry/cf-java-client#381]
I'm trying to use this, and getting this exception no matter what I try.
java.lang.NoClassDefFoundError: reactor/core/publisher/SchedulerGroup] with root cause
java.lang.ClassNotFoundException: reactor.core.publisher.SchedulerGroup

**Comment by nebhale** [comment]
You need to make sure that you're using the latest Reactor `2.5.0.BUILD-SNAPSHOT`s.  Reactor is changing quite quickly and we're keeping up with it daily.
