### ISSUE TITLE
Loggregator broken... 

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cf-java-client#387]
Once again :smile: 
It aims to get recent logs from api endpoint leading to a ```404 NOT FOUND``` error.

**Comment by nebhale** [comment]
@antechrestos Sorry about that.  I'm actually working now on doing some work to the client setups that will allow us to start properly integration testing the logging stuff as well.  Getting that tested is the next thing on my list.

**Comment by antechrestos** [comment]
@nebhale no problem :)
