### ISSUE TITLE
Create unique route while pushing to Bluemix from inside a maven build file

### ISSUE THREAD

**Issue by katheris** [cloudfoundry/cf-java-client#405]
I am pushing my application using the following plugin:
                <groupId>org.cloudfoundry</groupId>
                <artifactId>cf-maven-plugin</artifactId>
                <version>1.1.3</version>
I want to push my app as part of the build but I am having issues when the name for the app I have specified does not give me a unique route. Is there some way to define the route to use in maven, or to let it choose a unique route?

There seems to be no documentation of the maven plugin so this may already be possible, I don't know.

**Comment by nebhale** [comment]
The Maven plugin has not be resurrected in the 2.x line.  Therefore this issue is unlikely to ever be completed.
