### ISSUE TITLE
Allow multiple hosts to be mapped when deploying using gradle

### ISSUE THREAD

**Issue by asarver** [cloudfoundry/cf-java-client#409]
Using cloudfoundry gradle plugin.

It would be nice to specify multiple hosts to be mapped to application when doing task cfDeploy, like:

cloudfoundry {
    application = 'TestApp'
    variants = ['-inst1', '-inst2']
    host = ['testapp', 'testapp2']
    instances = 2
    memory = 512
}

This might already be possible, but I do not know.

**Comment by nebhale** [comment]
The Fradle plugin has not be resurrected in the 2.x line.  Therefore this issue is unlikely to ever be completed.
