### ISSUE TITLE
The java client can implement some tcp route operation? 

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/cf-java-client#420]
Hi :
I see now the cf-java-client does not support some TCP route operation, i wana to know cf-java-client team supporters this in the near future?

Some like:
createSharedDomain with default-tcp,
```
{
  "name": "example.com",
  "router_group_guid": "my-random-guid"
}
```
create or update application with ports.
```
{
  "name": "my_super_app",
  "space_guid": "a1687ba5-e188-44c8-b82a-ea6c893ae620",
  "diego": true,
  "ports": [
    1024,
    2000
  ]
}
```
Thanks.

**Comment by nebhale** [comment]
The functionality for creating a shared domain is scheduled, but [a ways down the backlog](https://www.pivotaltracker.com/story/show/101527354).  The issue will be used to update the [`CreateApplicationRequest`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/lombok/org/cloudfoundry/client/v2/applications/CreateApplicationRequest.java) with a ports argument.

**Comment by wdxxs2z** [comment]
Thanks @nebhale . I will modify my code and close the issue.Thank you.
