### ISSUE TITLE
setting timeout from client (CloudFoundryOperations) during login

### ISSUE THREAD

**Issue by codecheetos** [cloudfoundry/cf-java-client#422]
Looking at the low level implementation, the library is using RestTemplate which supports setting connection and socket timeout. How can we override the default connection and socket timeout when calling the CloudFoundryClient.login()?

**Comment by nebhale** [comment]
This doesn't exist today.  We're in the process of switching to a different networking stack which will necessitate a change here.  This issue will stay open as a marker that we need to add this functionality.

**Comment by nebhale** [comment]
@codecheetos We haven't added support for configuring this, but can you please take a look at the latest snapshot and see if you'd still need to make these changes.  I'm hoping that our new implementation works in such a way that you won't experience timeouts any longer.

**Comment by nebhale** [comment]
As of `2.0.0.M9` timeouts are now configurable in [`DefaultConnectionContext`](http://docs.cloudfoundry.com/cf-java-client/api/latest-snapshot/cloudfoundry-client-reactor/org/cloudfoundry/reactor/DefaultConnectionContext.html).
