### ISSUE TITLE
Add operation to obtain list of services to 'org.cloudfoundry.operations.services.Services'

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#425]
Similar to fetching list of applications, it should be possible/easy to obtain a list of services.

I was thinking it would go something like this (i.e. similar to how one obtains list of applications):

           CloudFoundryOperations client = ... ;
           client.services()
              .list()
              .map(...)

Note: I guess there may be different kinds of lists available here. E.g a list services available from the 'marketplace' and a list of service instances that a user has already created in their space.

For our use-case (i.e. porting STS Boot Dash from v1 client to v2) we are presently only interested in the service instances. (We may need the other list later though)

**Comment by nebhale** [comment]
We're planning on implementing the `-operations` layer such that it more or less matches the CF CLI.  Your `services` operation is being [worked currently](https://www.pivotaltracker.com/story/show/106155476) and you can always take a look at the current schedule for [all of the `-operations` APIs](https://www.pivotaltracker.com/n/projects/816799/search?q=label%3Aoperations) in the tracker.
