### ISSUE TITLE
CF Logs - Illegal characters in log message

### ISSUE THREAD

**Issue by Selvaguru** [cloudfoundry/cf-java-client#459]
When the log message has tab or empty space in front, they are represented by some illegal characters,

For example, consider the following actual log of an application,
![log empty](https://cloud.githubusercontent.com/assets/7485286/14639090/4fc7703c-0658-11e6-86bd-462c1fc15def.PNG)

When we get the logs using this library, the output is as follows,

![output protobuf](https://cloud.githubusercontent.com/assets/7485286/14639113/6472b4b0-0658-11e6-9b6c-93d91f15e02b.PNG)

**Comment by nebhale** [comment]
@Selvaguru Which version of the library are you using and running into these issues?

**Comment by Selvaguru** [comment]
@nebhale it was 1.1.4

**Comment by nebhale** [comment]
With the imminent release of v2 of the library, we've shifted all efforts off of v1 development.  We don't plan on fixing this issue and encourage you to take a look at the V2 milestones and snapshots.  If you still see this issue there, please open another issue to let us know.
