### ISSUE TITLE
Where can I find the Release artifacts??

### ISSUE THREAD

**Issue by mandeepkhambay** [cloudfoundry/cf-java-client#483]
The release repo doesn't have the release artifacts, where can I find them?
http://repo.spring.io/release/org/cloudfoundry/

I am looking for release versions of below:

   <dependency>
        <groupId>org.cloudfoundry</groupId>
        <artifactId>cloudfoundry-client-spring</artifactId>
        <version>2.0.0.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.cloudfoundry</groupId>
        <artifactId>cloudfoundry-operations</artifactId>
        <version>2.0.0.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core</artifactId>
        <version>2.5.0.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-netty</artifactId>
        <version>2.5.0.BUILD-SNAPSHOT</version>
    </dependency>

Thanks,

Mandeep Khambay

**Comment by nebhale** [comment]
There are no fully released artifacts yet and your like will be accurate once there are.  In the meantime, snapshots can be found as described in the documentation at http://repo.spring.io/snapshot/org/cloudfoundry/ and milestones at http://repo.spring.io/milestone/org/cloudfoundry/.

**Comment by mandeepkhambay** [comment]
Thanks Nebhale. Do you guys have an ETA on the release versions?

**Comment by nebhale** [comment]
No, nothing concrete.  We're releasing milestones every fortnight and as we get closer well start hardening on a date.
