### ISSUE TITLE
Issue using map route

### ISSUE THREAD

**Issue by mandeepkhambay** [cloudfoundry/cf-java-client#491]
Getting below error: 
Server error, status code: 502, error code: 10001, message: Service broker error: paths element

This was working earlier before June 1 build. Can you please suggest a workaround.

Here is the code that used to work before:
`
    MapRouteRequest mapRoute = MapRouteRequest.builder()
        .applicationName(cfAppHubUIAppName)
        .domain(domain)
        .host(hostname)
        .build();
    cloudFoundryOperations.routes().map(mapRoute).block();
`

**Comment by mandeepkhambay** [comment]
Adding path to it seems to work. This was not required before. Below code works, but not the desired behavior. 
`    MapRouteRequest mapRoute = MapRouteRequest.builder()
        .applicationName(cfAppHubUIAppName)
        .domain(domain)
        .host(hostname)
        .path("/test ")
        .build();
    cloudFoundryOperations.routes().map(mapRoute).block();
`

**Comment by mandeepkhambay** [comment]
Thanks for starting on this. Any ETA on the fix?

Thanks again!

Mandeep

**Comment by Zteve** [comment]
Fix being built now — unfortunately it threw up a couple of issues for the rest of the code.  Ben will resolve this issue if it makes it through integration test successfully.

**Comment by mandeepkhambay** [comment]
Thanks Zteve, I really appreciate the quick turnaround!

**Comment by nebhale** [comment]
Resolved 5469ff8758a0e9b860e2f3d67d780376cb20a9d6

**Comment by mandeepkhambay** [comment]
Got the latest (build 894), tried it out, its working!!! Thanks again everyone and appreciate the quick turnaround!!
