### ISSUE TITLE
Security Groups API : Creating a Security Group and Associate Space with it

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cf-java-client#494]
[Creating a Security Group](http://apidocs.cloudfoundry.org/latest-release/security_groups/creating_a_security_group.html) and [Associate Space with the Security Group](http://apidocs.cloudfoundry.org/latest-release/security_groups/associate_space_with_the_security_group.html) appears to be missing

**Comment by nebhale** [comment]
[Create Security Group](https://www.pivotaltracker.com/story/show/101522656) and (Associate Space with Security Group)[https://www.pivotaltracker.com/story/show/101522654] already exist and are prioritized for implementation.

**Comment by s-bortolussi** [comment]
@nebhale Thanks for your answer

We can provide you with such implementation ASAP.

**Comment by nebhale** [comment]
If you'd like to contribute an implementation, please submit a Pull Request that matches our coding standards and idioms.  There are a couple of other contributors at Orange that can help you with that if you need it.
