### ISSUE TITLE
Cannot build SpaceApplicationSummary

### ISSUE THREAD

**Issue by FaKeller** [cloudfoundry/cf-java-client#496]
Hello, I am working with the latest snapshot of the java client and after a recent update there is an error on the applications list query from the operations client. So when querying the applications along the lines of:

```java
cfOps.applications().list().collectList().doOnError(System.err::println).block()
```

the following error appears on the console:

```
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class org.cloudfoundry.client.v2.spaces.SpaceApplicationSummary] value failed (java.lang.IllegalStateException): Cannot build SpaceApplicationSummary, some of required attributes are not set [packageUpdatedAt]
 at [Source: reactor.io.netty.common.ReleasingBufferInputStream@37ba703f; line: 114, column: 5] (through reference chain: org.cloudfoundry.client.v2.spaces.Json["apps"]->java.util.ArrayList[1])
```

I am issuing the queries against `api.run.pivotal.io`, so I would not suspect the fault to be on the server side? Thank you very much in advance for investigating the issue!

**Comment by FaKeller** [comment]
I have just noticed that indeed the API from `api.run.pivotal.io` does not return a `packageUpdatedAt` for one of the applications:

```js
$ cf curl /v2/apps/<guid>
{
   "metadata": {
      // ...
      "created_at": "2016-06-07T08:46:28Z",
      "updated_at": "2016-06-07T08:46:57Z"
      // ...
   },
   "entity": {
      // ...
      "buildpack": null,
      "detected_buildpack": null,
      "memory": 1024,
      "instances": 1,
      "disk_quota": 1024,
      "state": "STOPPED",
      "package_state": "PENDING",
      "package_updated_at": null,
      // ...
   }
}
```

It seems like the app was created, but the initial push probably failed for some reason leaving the `package_updated_at` with a `null` value.

**Comment by kdvolder** [comment]
I think Ben just fixed this. I reported a very similar error to this one just before you in the slack channel and Ben followed-up with this commit: 

https://github.com/cloudfoundry/cf-java-client/commit/4f0f3699a801935d5107b2c380f5cd086481d9e4

**Comment by nebhale** [comment]
Yep, fixed in latest snapshot.
