### ISSUE TITLE
How to set list of env vars in one shot

### ISSUE THREAD

**Issue by mohanpindyala** [cloudfoundry/cf-java-client#504]
I am trying to set list of environment variables by using a loop or flux and it is not working . It only retains last one from the list and drops everything else. BTW I am a newbie to reactive programming.
Code sample 
`
 List<SetEnvironmentVariableApplicationRequest> envVars = new ArrayList<>();
.....filling list and then following code.....
 Flux.fromIterable(envVars).flatMap(envVar -> {
                                return cfOperations
                                            .applications()
                                            .setEnvironmentVariable(envVar)
                                            .then();
                            }).subscribe();
`

**Comment by twoseat** [comment]
I believe the behaviour you're seeing is expected based on how Cloud Foundry works. [This issue](https://github.com/cloudfoundry/cf-java-client/issues/488) essentially the same, and contains two possible solutions. Let us know if that doesn't help.

**Comment by mohanpindyala** [comment]
it works thanks

**Comment by twoseat** [comment]
@mohanpindyala Great!
