### ISSUE TITLE
MapRoute with no host does not work

### ISSUE THREAD

**Issue by mandeepkhambay** [cloudfoundry/cf-java-client#514]
We have a need to mapRoute with no hostname, just domain name. It works in CLI and can also be achieved through direct REST calls (POST /v2/routes and PUT - /v2/apps/<app guid>/routes/<routes guid>). 

**Error with CloudFoundryOperations mapRoute request:**

FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: hosts element

2016-06-28T20:38:34.51-0700 [App/0]      ERR java.lang.NullPointerException: hosts element
2016-06-28T20:38:34.51-0700 [App/0]      ERR 
**at java.util.Objects.requireNonNull(Objects.java:228)**
2016-06-28T20:38:34.51-0700 [App/0]      ERR 
at org.cloudfoundry.client.v2.routes.ListRoutesRequest$Builder.host(List

Thanks,

Mandeep Khambay

**Comment by Zteve** [comment]
@mandeepkhambay Thank you for raising this problem. We are currently scanning the code base for similar issues and have discovered this one already.  A fix will be included soon. When this has been committed I will close this issue.

**Comment by Zteve** [comment]
Fix is in commit [cf-java-client / 1f3bfa1][1].

[1]:https://github.com/cloudfoundry/cf-java-client/commit/1f3bfa1b9f2283e5496d1f21ccd7df375dd3c526

**Comment by mandeepkhambay** [comment]
I just verified, the fix is working. Thanks Steve!

**Comment by Zteve** [comment]
You're welcome.
