### ISSUE TITLE
Release version release date?

### ISSUE THREAD

**Issue by mandeepkhambay** [cloudfoundry/cf-java-client#515]
Hi,

Do you know when the release version is expected?

Thanks,

Mandeep

**Comment by nebhale** [comment]
The current, non-binding plan is to get a release out by the end of July.  We are gated on releases of `reactor-core` and `reactor-netty` which is also scheduled for that time.

**Comment by mandeepkhambay** [comment]
Thanks Ben, I will keep a look out.
