### ISSUE TITLE
cf-gradle-plugin has no documentation

### ISSUE THREAD

**Issue by StephenTurley** [cloudfoundry/cf-java-client#522]

**Comment by nebhale** [comment]
@StephenTurley Yep, because there's no [V2 code](https://github.com/cloudfoundry/cf-java-client/tree/master/cloudfoundry-gradle-plugin) there yet either.  V1 documentation can be found [here](https://github.com/cloudfoundry/cf-java-client/tree/1.x/cloudfoundry-gradle-plugin).
