### ISSUE TITLE
Add tags in ServiceOffering class

### ISSUE THREAD

**Issue by alexander071** [cloudfoundry/cf-java-client#527]
Hi colleagues,

I am writing an automation tool for managing of services. It allows users to "push" services in a manner similar to pushing applications.

The services are declared with a similar syntax to the one used for declaring applications in manifest.yml files. Example:

```
services:
  - name: managed-service-1
    type: uaa
    tags: [ custom-tag-1, custom-tag-2 ]
```

As you can see, the user can declare custom tags, which should be used when creating/updating the service.

However, when the service is created, the service broker could inject some "default" tags in addition to the custom ones described in the user's manifest. So in the end we get a service with the following tags:
`[ default-tag-1, custom-tag-1, custom-tag-2 ]`

The first "push" done by my automation tool works fine in this case. However, a problem arises when it tries to decide whether to update a service or not. If a service with these tags exists:
`[ default-tag-1, custom-tag-1, custom-tag-2 ]`
And the user has specified only these tags in the manifest:
`[ custom-tag-1, custom-tag-2 ]`
Then my tool decides that the service should be updated, because the tags are different and it does not know that "default-tag-1" is a default tag inserted by the service broker itself.

So, in order to fix this issue, I need a method in the Java client that allows me to retrieve these "default" tags. I noticed that the `/services` endpoint of the CF controller already returns them, but for some reason the Java client does not include them in the ServiceOffering class returned by the listServiceOfferings() method (which contacts the `/services` endpoint).

Do you think that it would be a good idea to include the tags in the ServiceOffering class?

Thanks and best regards,
Alexander

**Comment by Zteve** [comment]
Since you address this in pull request #528, I'm going to close this issue and delete its associated tracker story, in favour of the pull request (and _its_ story).  This saves duplication.
