### ISSUE TITLE
Cannot get list of organizations with pcfDef 

### ISSUE THREAD

**Issue by 1123** [cloudfoundry/cf-java-client#530]
First of all thanks for your great work on the cloudfoundry client. 

So these are my first steps with this 2.0 cloudfoundry client. I have been using the 1.x versions previously. Unfortunately, I fail to get a list of organizations from my local pcfDev environemnt -- and also for api.run.pivotal.io. Here's my code: 

@Slf4j
public class CfClientTest {

    private ConnectionContext connectionContext;
    private UaaClient uaaClient;
    private DopplerClient dopplerClient;
    private CloudFoundryClient cloudFoundryClient;
    private TokenProvider tokenProvider;

    @Before
    public void setup() {
        this.tokenProvider = PasswordGrantTokenProvider.builder()
                .password("user")
                .username("pass")
                .build();
        this.connectionContext = DefaultConnectionContext.builder()
                .apiHost("api.local.pcfdev.org")
                .build();
        this.uaaClient = ReactorUaaClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
        this.dopplerClient = ReactorDopplerClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
        this.cloudFoundryClient = ReactorCloudFoundryClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();
    }

    @Test
    public void testWitcfhOperations() {
        log.info("testing getting orgs");
        DefaultCloudFoundryOperations operations = DefaultCloudFoundryOperations.builder()
                .cloudFoundryClient(cloudFoundryClient)
                .dopplerClient(dopplerClient)
                .uaaClient(uaaClient)
                .organization("pcfdev-org")
                .space("pcfdev-space")
                .build();
        operations.organizations()
                .list()
                .map(OrganizationSummary::getName)
                .subscribe(System.out::println);
    }
}

The test passes, but no organization names are printed to stdout. Yet I am sure that there should be the system org and the pcfdev-org. Also the username and password are correct (the default ones with pcfdef). I can login with the cf command line tool.

The whole project with dependencies is here: https://github.com/1123/cf-client-test . It must be something obvious. What am I missing?

**Comment by nebhale** [comment]
The problem that you're running into is that the client is _very_ asynchronous.  In most cases (e.g. Web applications), this is fine since the container stays alive for a long time and responses can be handled during that lifecycle.  However, JUnit is very aggressively single-threaded and completes tests very quickly, shutting down the JVM as soon as possible; typically before a network request returns.  To compensate for this, you need to keep the test alive until the request has completed (again, this is very much a test thing, not a typical usage thing), typically using a `CountDownLatch`.  I've [submitted a PR](https://github.com/1123/cf-client-test/pull/1) to your example showing you how to do this.

**Comment by 1123** [comment]
Great, thanks. This gets me one step further. So now the client is authenticating with the pcfdev, yet the test runs forever probably because no data is received, and the countdownlatch prevents it from finishing. I will need to turn on logging to see what's the problem and will paste the output here.
