### ISSUE TITLE
cf-java-client stops working completely when its auth token expires

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#535]
The latest snapshot I tried yesterday has a very serious problem (for STS at least, where a client instance life-time is tied to the IDE session). 

The problem is that client seems like it *never* refreshes its auth token. When the token expires the client stops working alltogether. 

In STS this means the user has to close their IDE and reopen it to re-establish a connection to CF.

Long story short, this bug is a blocker for us. We have to stick with the old snapshot and reactor 2.5.0 for now until this bug is fixed.

**Comment by nebhale** [comment]
Fixed in d33f41bcd653d32a1b742e243983a1072cafd322.
