### ISSUE TITLE
logstreaming in proxied / firewalled environment drops connection after a few minutes

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#536]
I'm  testing STS tooling behind a proxy/firewall setup. I'm using a basic 'squid' proxy (this one https://github.com/sameersbn/docker-squid ).

The latest snapshot now works a little better, it does make contact and streams logs succesfully, but the connection always closes after a few minutes.

I don't see this behavior when 
 
 - connecting directly (i.e. not via proxy)
 - using CFT (which is based on the V1 client)either with or without proxy.

So to me it looks like V2 client is somehow dropping the ball on this, since it works properly with V1.

**Comment by nebhale** [comment]
Fixed.
