### ISSUE TITLE
Fail to get App while using CloudFoundryOperations.applications()#get

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cf-java-client#540]
It appears that CloudFoundryOperations.applications()#get requests for ApplicationStatistics.

While getting ApplicationStatisticsResponse, got a deserialization exception

```java
Caused by: java.lang.AssertionError: Found unexpected property net_info in payload for Json
	[...]	
	at org.cloudfoundry.client.v2.applications._ApplicationStatisticsResponse$ApplicationStatisticsResponseDeserializer.deserialize(_ApplicationStatisticsResponse.java:52)
	at org.cloudfoundry.client.v2.applications._ApplicationStatisticsResponse$ApplicationStatisticsResponseDeserializer.deserialize(_ApplicationStatisticsResponse.java:41)

```

Whereas net_info property does not seem to be [documented](http://apidocs.cloudfoundry.org/236/apps/get_detailed_stats_for_a_started_app.html) and thus part of ApplicationStatisticsResponse , it is indeed returned by api call 

```
$ cf curl v2/apps/6a5601d5-ae48-4b5c-b440-580b245bb4f0/stats
{
   "0": {
      "state": "RUNNING",
      "stats": {
         "name": "test-application-lclah",
         "uris": [
            "test-application-lclah.xxxx"
         ],
         "host": "x.x.x.x",
         "port": xxxx,
         "net_info": {
            "address": "x.x.x.x",
            "ports": [
               {
                  "container_port": xxxx,
                  "host_port": xxxxx
               },
               {
                  "container_port": xxxx,
                  "host_port": xxxxx
               }
            ]
         },
         "uptime": xx,
         "mem_quota": 536870912,
         "disk_quota": 536870912,
         "fds_quota": 16384,
         "usage": {
            "time": "2016-07-28T09:31:15.164895799Z",
            "cpu": 0.0018390040377131692,
            "mem": 321777664,
            "disk": 170438656
         }
      }
   }
}
```

The CC API version is 2.56.0

**Comment by nebhale** [comment]
@s-bortolussi Can you please post the configuration you've used for the `ConnectionContext`?  It was our goal that we'd ignore unknown properties in a customer environments while breaking in test environments.

**Comment by s-bortolussi** [comment]
@nebhale Oups, Im a afraid I ve just copied and pasted ConnectionContext configuration from IntegrationTestConfiguration



    @Bean
    DefaultConnectionContext connectionContext(@Value("${test.apiHost}") String apiHost,
                                               @Value("${test.proxy.host:}") String proxyHost,
                                               @Value("${test.proxy.password:}") String proxyPassword,
                                               @Value("${test.proxy.port:8080}") Integer proxyPort,
                                               @Value("${test.proxy.username:}") String proxyUsername,
                                               @Value("${test.skipSslValidation:false}") Boolean skipSslValidation) {

        return DefaultConnectionContext.builder()
                .apiHost(apiHost)
                .problemHandler(new FailingDeserializationProblemHandler())  // Test-only problem handler
                .skipSslValidation(skipSslValidation)
                .build();
    }

**Comment by nebhale** [comment]
Yeah, give it a try without the problem handler. The `README` has a good example of typical configuraion.

**Comment by s-bortolussi** [comment]
Works much better !
Thanks for your help

**Comment by nebhale** [comment]
No worries.

**Comment by twoseat** [comment]
As an update to this issue, the `net_info` field shouldn't have been in the payload, and has been removed in the latest builds of CF.

**Comment by s-bortolussi** [comment]
Thanks for the update.
