### ISSUE TITLE
Updating application resources

### ISSUE THREAD

**Issue by kiuby88** [cloudfoundry/cf-java-client#544]
Hi,
we'd like to update the resources of a deployed application, `memory` and `disk_quota`, `instances`.  Currently, I do it using a `PushApplicationRequest`, but I have to use the artifact path in order to create the request, it would be interesting to update the application resources avoiding to update the application artifact . Is this something that will be added soon, or is there an alternative way of doing this?

Thanks a lot for your help!

**Comment by twoseat** [comment]
@kiuby88 You could try a `cloudFoundryClient.applicationsv2.update`. The only field *required* on that request is the `applicationId`, which is obviously needed, so you should be able to update the fields you mentioned OK.

This isn't a feature we're planning to add to the operations layer; we model that on the CLI, which doesn't have the feature you mention.

**Comment by kiuby88** [comment]
@twoseat, thanks for your response.
I have just found the `scale` operation of `CloudFoundryOperations`. It is just what I was finding. It allows to modify the application's resources from the operation layer.
