### ISSUE TITLE
Docker deployments not working

### ISSUE THREAD

**Issue by a-thaler** [cloudfoundry/cf-java-client#550]
In DefaultCloudFoundryOperations.applications().push(...) you can specify a dockerImage but the Path to the application is still mandatory and will be respected always. With that it is not possible to use the dockerImage attribute.
Furthermore the "diego" flag gets not set in the DefaultApplications.requestCreateApplication if a value for a dockerImage gets provided. Same for DefaultApplications.requestUpdateApplication.

**Comment by a-thaler** [comment]
Hi @twoseat,
thanks for taking care of that.
Unfortunately the fix does not work for me.
The branch which you added to the "push" method in "DefaultApplications" does not call "requestCreateApplication" anymore which is needed in my understanding, as you still need to create the application. Here, you set the "dockerImage" attribute at the application. Furthermore the "diego" flags needs to set to "true".

Can you please take a look again

**Comment by a-thaler** [comment]
Hi @twoseat,
sorry, I was partially wrong with my last comment. The "requestCreateApplication" method is still called, just the "diego" flag still needs to get set in the "requestCreateApplication" method in case a dockerImage is provided.

**Comment by twoseat** [comment]
Thanks for pointing that out @a-thaler - entirely my fault, your initial report was very clear. This should now be working, but let me know if you see further issues.

**Comment by a-thaler** [comment]
Works fine for me now, thanks a lot @twoseat.
However, I think the same fix should be applied to the "requestUpdateApplication" method to be consistent.
