### ISSUE TITLE
COUNTER_EVENT info not mapped into Envelope

### ISSUE THREAD

**Issue by matthewcosgrove** [cloudfoundry/cf-java-client#554]
Currently, on latest 2.0.0.BUILD-SNAPSHOT, the envelope for eventType=COUNTER_EVENT does not contain information about what the event is or the actual count

Running cf nozzle produces the following output (note the counterEvent field)

> origin:"MetronAgent" eventType:CounterEvent timestamp:1471296248497456989 deployment:"cf" job:"doppler-partition-f27b9190dec95dcd0a6f" index:"0" ip:"10.0.0.20" counterEvent:name:"dropsondeUnmarshaller.counterEventReceived" delta:11 total:6137874 

However, the output via cf java client is

> Envelope{containerMetric=null, deployment=cf, error=null, eventType=COUNTER_EVENT, httpStart=null, httpStartStop=null, httpStop=null, index=0, ip=10.0.0.20, job=doppler-partition-f27b9190dec95dcd0a6f, logMessage=null, origin=MetronAgent, tags={}, timestamp=1471296323497448439, valueMetric=null}

From a cursory glance, I can see that there is a class `_CounterEvent.java` which is not included in the following mappings in `_Envelope.java`
```
        Optional.ofNullable(dropsonde.containerMetric).ifPresent(d -> envelope.containerMetric(ContainerMetric.from(d)));
        Optional.ofNullable(dropsonde.error).ifPresent(d -> envelope.error(Error.from(d)));
        Optional.ofNullable(dropsonde.httpStart).ifPresent(d -> envelope.httpStart(HttpStart.from(d)));
        Optional.ofNullable(dropsonde.httpStartStop).ifPresent(d -> envelope.httpStartStop(HttpStartStop.from(d)));
        Optional.ofNullable(dropsonde.httpStop).ifPresent(d -> envelope.httpStop(HttpStop.from(d)));
        Optional.ofNullable(dropsonde.logMessage).ifPresent(d -> envelope.logMessage(LogMessage.from(d)));
        Optional.ofNullable(dropsonde.valueMetric).ifPresent(d -> envelope.valueMetric(ValueMetric.from(d)));
```

**Comment by nebhale** [comment]
Yep, you're right.  That's been missing a long time :(
