### ISSUE TITLE
Environment variables when running integration test against PCFDEV

### ISSUE THREAD

**Issue by PavelSosin** [cloudfoundry/cf-java-client#556]
I'm trying to run Integration tests using PCFDEV. To satisfy Test configuration requirement I had to define in my run configuration some environment variables which are not described in documentation but still receive authentication errors. What are the standard PCFDEV's value for the environment variables expected by Integration tests? Which values are not correct:

```
TEST_APIHOST=api.local.pcfdev.io
TEST_USERNAME=admin
TEST_PASSWORD=admin
TEST_SKIPSSLVALIDATION=true
TEST_UAA_CLIENTID=cf
TEST_UAA_CLIENTSECRET=adminclientsecret
TEST_ADMIN_PASSWORD=admin
TEST_ADMIN_USERNAME=admin
TEST_ADMIN_CLIENTID=cf
TEST_ADMIN_CLIENTSECRET=adminclientsecret ?
```
BR
Pavel

**Comment by nebhale** [comment]
The documentation has now been updated to match the Integration Test configuration.  The values we use for testing against `pcfdev` can be found [here](https://github.com/cloudfoundry/cf-java-client/blob/master/.idea/runConfigurations/integration_test.xml#L20-L25).
