### ISSUE TITLE
Why currentVariant is being removed ?

### ISSUE THREAD

**Issue by vtrbtf** [cloudfoundry/cf-java-client#559]
I'm trying to get the currentVariant variable after `cfDeploy` occurs, so that I can do some checks ( calling `/health` for example ) on the application, before calling `cfSwapDeploy`, but I've noticed this property is being removed explicitly. 
Why this is happening ?   

Thanks 😄

**Comment by nebhale** [comment]
I believe that this refers to the CF Java Client 1.x which is no longer supported.  Is this the case?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a year, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
