### ISSUE TITLE
Timeout Creating Service

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry/cf-java-client#560]
Hi, I'm hitting the timeout limit of 5mins specified here:
https://github.com/cloudfoundry/cf-java-client/blob/2b2a50d59b1236261f65b9441f6d814687f9f30a/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/services/DefaultServices.java#L869

My Broker takes longer than 5mins to provision some services - is there a way to override this value?

**Comment by nebhale** [comment]
There isn't.  We'll add that to the backlog.

**Comment by wybrono** [comment]
Can this function be used now?

**Comment by nebhale** [comment]
@wybrono Nope, it's still on the backlog.

**Comment by nebhale** [comment]
Solved as part of 2.5.0.RELEASE in #693
