### ISSUE TITLE
Cannot get answer from a statistics request

### ISSUE THREAD

**Issue by Pola15** [cloudfoundry/cf-java-client#561]
Hi,

I'm not sure if it's an issue or it's just before I don't know how to use the API, I have tried all samples I can find, but I hardly can even find a piece of code that compile with the new version.

I need to get the IPs from the instances of my application, so I have created the below code. It contains the definition of a class ApplicationStatisticsResponseConsumer that extracts the IPs from the instance statistics, and another piece of code that use it to get the IPs. 

Somehow I never get the IP (the println always prints empty array). and in fact, the accept method is never entered.

So is it the right way to use the API?

Thanks,
Pola

```
public static class ApplicationStatisticsResponseConsumer implements Consumer<ApplicationStatisticsResponse>{

        ArrayList<Host> ips = new ArrayList<Host>();

        @Override
        public void accept(ApplicationStatisticsResponse t) {
            Map<String, InstanceStatistics> map = t.getInstances();
            for(InstanceStatistics stat : map.values()){

                Statistics statistics = stat.getStatistics();
                if(statistics != null)
                    ips.add(new Host(statistics.getHost(), statistics.getPort()));
            }
        }
        public List<Host> getIPs() {
            return ips;
        }
    }

        String applicationId = getApplicationID(appName);       

        ApplicationStatisticsRequest request = ApplicationStatisticsRequest.builder().applicationId(applicationId).build();
        Mono<ApplicationStatisticsResponse> response = cfClient.applicationsV2().statistics(request);           

        ApplicationStatisticsResponseConsumer consumer = new ApplicationStatisticsResponseConsumer();
        response.subscribe(consumer);

        System.out.println(consumer.getIPs());
```

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
