### ISSUE TITLE
Not Available in Maven Central

### ISSUE THREAD

**Issue by DanielJonesEB** [cloudfoundry/cf-java-client#563]
The old Cloud Foundry client was available in Maven Central, but the new snazzy version is not. I'm working with an enterprise customer (also a PCF user) for whom it's easy to download libraries from Maven Central, but getting new repositories added (such as Spring Releases) is an epic task involving service requests and lead-times measured in weeks.

Could it please be deployed into Maven Central?

**Comment by nebhale** [comment]
All milestone and releases available in Maven Central (might take a little while to propagate).
