### ISSUE TITLE
The admin user can not view the new organization 

### ISSUE THREAD

**Issue by wybrono** [cloudfoundry/cf-java-client#577]
I created a new organization, and the authority of the organization manager attached to the admin user, but with the admin user login appsmanager, still can not see the organization. But with the cli operation, I can see the organization.
why?

**Comment by nebhale** [comment]
What APIs were you using to do this work?  Specifically, were you using the Client or Operations APIs?

**Comment by wybrono** [comment]
Sorry,
I used the wrong method, I do not have associated organizations and space
