### ISSUE TITLE
 Login error

### ISSUE THREAD

**Issue by wybrono** [cloudfoundry/cf-java-client#579]
when I login cf,I get this error
java.lang.ClassNotFoundException: org.apache.http.conn.ssl.TrustStrategy

I have imported this jar,Why can not find this class
why?

**Comment by nebhale** [comment]
@wybrono We do not use that class, nor do we have that JAR on our classpath during any development or testing, so I'm quite sure that it isn't required by our code.  You might check the full stack trace to find out where in the code this _is_ being required and start there.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
