### ISSUE TITLE
POST /UAALoginServerWAR/oauth/token fails with HTTP 411 status code

### ISSUE THREAD

**Issue by leachbj** [cloudfoundry/cf-java-client#580]
Using cf-client 2.0.2 and reactor-core 3.0.3 the auth request fails with missing content-length header.  Using 2.0.1 and 3.0.3 I can see `content-length: 0`

Here's the full request that fails.

```
POST /UAALoginServerWAR/oauth/token?client_id=cf&client_secret=&grant_type=password&password=<redacted>&username=<redacted> HTTP/1.1

host: mycfhost
content-type: application/x-www-form-urlencoded
authorization: Basic <redacted>
accept: application/json
```

**Comment by nebhale** [comment]
What version of PCF/CF are you using?  We removed that header because it appears that it isn't necessary in versions of the CF released in the last year or so.

**Comment by leachbj** [comment]
POST requests one of content-length or transfer-encoding:chunked, they're both being removed so the POST request is invalid.  A nice server might just assume the length=0 case for the missing headers but doesn't look like our version of cf does (or perhaps an intermediate proxy!).
