### ISSUE TITLE
Feature request: Add support for updating security groups

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-java-client#585]
We would like the ability to update the rules of an existing security group (see [Security Groups API - Updating a Security Group](https://apidocs.cloudfoundry.org/247/security_groups/updating_a_security_group.html)) It appears that currently only create, delete and list have been implemented. In cases where a security group is bound to one or more spaces, we would prefer to do an update as this would maintain the list of associated spaces.

**Comment by twoseat** [comment]
Added in 2.1.0.RELEASE
