### ISSUE TITLE
/v2/apps debug field is actually a string and not a Boolean

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#590]
The apps debug field is a string will values like "run", "suspend", and maybe "none" and not a boolean.

This causes problems for my apps that have a debug value set.  My organization is probably the only organization in the world using the debug field so I can submit a PR if you want.  Wasn't sure if it would be easier for you to just fix it or to process a PR.  LMK, thanks!

**Comment by twoseat** [comment]
Thanks for the report @youngm - the fix should be in the latest 2.0 snapshot now, and will make it to the 2.1 snapshot as soon as we've cleared up a CI snag.

**Comment by youngm** [comment]
Thanks @twoseat
