### ISSUE TITLE
map route using CloudFoundryOperations with null hostname hangs with no response

### ISSUE THREAD

**Issue by pandeyar** [cloudfoundry/cf-java-client#591]
We are experiencing weird issue whenever we try to map route using java client on spring cloud version 1.0.0.RELEASE,  cloudFoundryOperations.routes().map(mapRoute) call just hangs without any response back.  We are using following dependency. 
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-cloudfoundry-service-broker</artifactId>
<version>1.0.0.RELEASE</version>
</dependency>

Whereas if switch version of spring-cloud-cloudfoundry-service-broker to 1.0.0.BUILD-SNAPSHOT map route always works and response is immediate.
In case needed we are using cloudfoundry-operations version 2.0.1.RELEASE.
Could you take a look at this?

**Comment by nebhale** [comment]
@pandeyar Are you still seeing this issue when using the client with Spring Cloud?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
