### ISSUE TITLE
Checking status of an Application

### ISSUE THREAD

**Issue by davinder2385** [cloudfoundry/cf-java-client#598]
Hi,
Can you please help me with a sample code snippet to check the status of an application -- Running or Stopped using these APIs?

Also, is it possible to query the events associated with the application using java APIs?
(Sample code please)
Thanks,
Davinder

**Comment by nebhale** [comment]
The easiest way is to get the current status of the application using the Operations API:

```
this.cloudFoundryOperations.applications()
    .get(GetApplicationRequest.builder()
        .name("test-application")
        .build())
    .flatMapIterable(ApplicationDetail::getInstanceDetails)
    .zipWith(Flux.range(0, Integer.MAX_VALUE))
    .subscribe(tuple -> {
        InstanceDetail instance = tuple.getT1();
        int index = tuple.getT2();

        System.out.printf("#%d: %s\n", index, instance.getState());
    });
```

**Comment by davinder2385** [comment]
Thank you.
One more question.
On command prompt i am logging into CF using "cf login -sso".
Is there any java equivalent for logging into the CF environment with -sso option?
Can you please share a sample snippet?
Appreciate your help on this.

**Comment by nebhale** [comment]
The `TokenProvider` is an interface that allows you to implement any authentication system you need.
