### ISSUE TITLE
Complete client organisation integration tests

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cf-java-client#617]
Four tests outstanding, depending on meaningless filtering (e.g. filter a user in a space based on space). Need to decide whether to keep the filter and enable the tests, or remove the filter and break parity with the API.

**Comment by nebhale** [comment]
@twoseat was there a CAPI issue about the useless filter?

**Comment by twoseat** [comment]
Sorry, meant to link it - https://github.com/cloudfoundry/cloud_controller_ng/issues/594

**Comment by twoseat** [comment]
Completed as part of #620 (https://github.com/cloudfoundry/cf-java-client/commit/962919bf3071331ac51642507506aa065047ff4f)
