### ISSUE TITLE
hey,can you give some example code?

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-java-client#635]
i try the jar some day,but i do not success,for example ,i look you test code,and same code in test,but not success,can you give a simple code,example for request list orgs

**Comment by nebhale** [comment]
Given a [properly configured](https://github.com/cloudfoundry/cf-java-client#usage) `CloudFoundryOperations`, the following:

```
this.cloudFoundryOperations.organizations()
  .list()
  .map(OrganizationSummary::getName)
  .subscribe(System.out::println);
```

Note that this runs asynchronously, which is fine in most web applications, but if you're trying to run this from either a test or a `main()` method, you'll need to ensure that your VM stays alive longer than it takes for the request and response to happen.  You might use a `CountDownLatch` to ensure this:


```
CountDownLatch latch = new CountDownLatch(1);

this.cloudFoundryOperations.organizations()
  .list()
  .map(OrganizationSummary::getName)
  .subscribe(System.out::println, t -> {
    t.printStackTrace();
    latch.countDown();
  }, latch::countDown);

latch.await();
```

**Comment by geekyzk** [comment]
ohh, can you teach me how to use it in web ? 
this is my code:
@RequestMapping(value = {"/","/index"},method = RequestMethod.GET)
public String index(){
cloudFoundryOperations.organizations().list().subscribe(OrganizationSummary ->{

    });
}










On 01/20/2017 22:54， Ben Hale<notifications@github.com>wrote：

Given a properly configuredCloudFoundryOperations, the following:

this.cloudFoundryOperations.organizations()
  .list()
  .map(OrganizationSummary::getName)
  .subscribe(System.out::println);


Note that this runs asynchronously, which is fine in most web applications, but if you're trying to run this from either a test or a main() method, you'll need to ensure that your VM stays alive longer than it takes for the request and response to happen. You might use a CountDownLatch to ensure this:

CountDownLatch latch = new CountDownLatch(1);

this.cloudFoundryOperations.organizations()
  .list()
  .map(OrganizationSummary::getName)
  .subscribe(System.out::println, t -> {
    t.printStackTrace();
    latch.countDown();
  }, latch::countDown);

latch.await();

**Comment by nebhale** [comment]
Unless you are using [Spring 5](https://spring.io/blog/2016/07/28/reactive-programming-with-spring-5-0-m1), you'll need to convert the the reactive type (a `Flux` in this case), to a non-reactive type using a `.block()` call.  This call blocks the calling thread until a response has been received.

```
@RequestMapping(value = {"/", "/index"}, method = RequestMethod.GET)
public String index() {
    List<OrganizationSummary> organizationSummaries = cloudFoundryOperations.organizations()
        .list()
        .collectList()
        .block();

    return organizationSummaries.steam()
        .collect(Collectors.joining(", "));
}
```

**Comment by geekyzk** [comment]
Thank you ,can i ask a question for you ? I design a web manager for cf,but before that i use Spring restTemplate to request
cloudfoundry data, i save user token in servletContext, but some times the data is error,for example , a user login,but when he success, show the other's information in the servletcontext.Can be consulted when have landed in a multi-user save token better way,
I'm in the current project ,use connect cloudfoundry class the scope is session,but in the project,must use spring quartz
to collect data to local db,but not get connect class in quartz



On 01/20/2017 23:38， Ben Hale<notifications@github.com>wrote：

Unless you are using Spring 5, you'll need to convert the the reactive type (a Flux in this case), to a non-reactive type using a .block() call. This call blocks the calling thread until a response has been received.

@RequestMapping(value = {"/", "/index"}, method = RequestMethod.GET)
public String index() {
    List<OrganizationSummary> organizationSummaries = cloudFoundryOperations.organizations()
        .list()
        .collectList()
        .block();

    return organizationSummaries.steam()
        .collect(Collectors.joining(", "));
}

**Comment by nebhale** [comment]
A traditional way to do this would be to have you web application use OAuth for authentication and authorization, delegating to the Cloud Foundry UAA for tokens.  That way, the user logs in and the whole handshake is delegated off to the UAA.  When it's complete, the token is presented to the web application.  **That same token can then be used to make calls with the Java Client** ensuring that the user _must_ have the appropriate permissions to do what they're trying to do.  A custom `TokenProvider` that extracts from either the Spring `SecurityContext` or the `ServletContext` on each request would be appropriate.

**Comment by geekyzk** [comment]
Thank you, you can give a contact after more contact?
