### ISSUE TITLE
bluemix connection

### ISSUE THREAD

**Issue by safrazhanas** [cloudfoundry/cf-java-client#674]
I've tried to create (bluemix) CloudFoundryOperations using the steps mentioned in Readme.

        DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
                .apiHost(apiHost)
                .build();

        PasswordGrantTokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
                .password(password)
                .username(userName)
                .build();
        ReactorCloudFoundryClient cloudFoundryClient = ReactorCloudFoundryClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();

        ReactorDopplerClient dopplerClient = ReactorDopplerClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();

        ReactorUaaClient uaaClient = ReactorUaaClient.builder()
                .connectionContext(connectionContext)
                .tokenProvider(tokenProvider)
                .build();

        DefaultCloudFoundryOperations cloudFoundryOperations = DefaultCloudFoundryOperations.builder()
                .cloudFoundryClient(cloudFoundryClient)
                .dopplerClient(dopplerClient)
                .uaaClient(uaaClient)
                .organization(organization)
                .space(space)
                .build();

        cloudFoundryOperations.organizations()
                .list()
                .map(OrganizationSummary::getName)
                .subscribe(System.out::println);

i have replaced apiHost ('api.ng.bluemix.net'), userName, password, organization and space appropriately. when i run above code snippet under main method, i don't get organization names in console. neither i get an error. 

appreciate, if anyone can give insight.

**Comment by nebhale** [comment]
All calls in the Java Client are asynchronous and your application is exiting before the server has responded.  In long-lived applications (like web applications), this isn't a big deal because the application's lifetime always outlives the request's lifetime.  However, if you're running in a `main()` method, you need to manage the lifecycle of the application manually.  Typically this is done with a `CountDownLatch`.

```
...
CountDownLatch latch = new CountDownLatch(1);

cloudFoundryOperations.organizations()
  .list()
  .map(OrganizationSummary::getName)
  .subscribe(System.out::println, t -> {
    t.printStackTrace();
    latch.countDown();
  }, latch::countDown);

latch.await();
```
