### ISSUE TITLE
sshCode example

### ISSUE THREAD

**Issue by andreaturli** [cloudfoundry/cf-java-client#682]
I'm using the following dev env:
```
$ cf dev version
PCF Dev version 0.23.0 (CLI: 474b3ba, OVA: 0.436.0)

$ cf -v
cf version 6.22.2+a95e24c-2016-10-27 
```

By issuing `cf ssh-code` using the cli, I get the code without problems but using the following java code:
```
CloudFoundryOperations cfOperations = DefaultCloudFoundryOperations.builder()
              .cloudFoundryClient(cloudFoundryClient)
              .uaaClient(uaaClient)
              .organization(organization)
              .space(space)
              .build();
String sshCode = cfOperations.advanced().sshCode().block();
``` 
I get the following error:
```
java.lang.IllegalStateException: Parameter code not in URI https://uaa.local.pcfdev.io/login
```
I'd really appreciate a working example on the doc or a working snippet of code that I can use to reproduce the steps described at https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#other-ssh-access but using the java client.

Thanks!

**Comment by twoseat** [comment]
Hi @andreaturli. I suggest taking a look at our [integration test](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/operations/AdvancedTest.java#L34-L42) for this.

It's not as straightforward to read as your example of course, as it's semi-production code, but if you check the configuration for our tests (e.g. the [CloudFoundryOperations](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/IntegrationTestConfiguration.java#L199-L209)) that should demonstrate how everything should be configured.

I'll leave this issue open while you investigate, and if we're the source of your NPE please let us know!

**Comment by nebhale** [comment]
@andreaturli We've managed to replicate your issue and it comes down to the fact that there must be a properly negotiated token _before_ you ask for an `sshCode`.  These days, tokens are not negotiated until a `401` is received, so if the first call is to `sshCode` and the server doesn't respond with a `401`, then there is no token and no code.  I'll talk to the UAA team about the best way to deal with this.

**Comment by andreaturli** [comment]
thanks @twoseat and @nebhale 

@nebhale is there a way to force a `401` ? Can I set a very short expiration time on the token, maybe?

**Comment by andreaturli** [comment]
thanks @nebhale, `2.0.4.BUILD-SNAPSHOT` solves my issue!

**Comment by nebhale** [comment]
I hope you mean `2.4.0.BUILD-SNAPSHOT` 😄

**Comment by andreaturli** [comment]
indeed! 👍
