### ISSUE TITLE
LogMessage marshalling fails on large messages

### ISSUE THREAD

**Issue by jghiloni** [cloudfoundry/cf-java-client#688]
When using `ReactorDopplerClient`, very large messages can cause `ReactiveDopplerEndpoints.toEnvelope` fail with an `EOFException`. 

Steps to reproduce (abstract):
1. Have a `ReactorDopplerClient` listening to the CF firehose
1. Log an app message (thus generating a `LogMessage`) where the total size of the envelope is greater than **4096 bytes**.

Steps to reproduce (concrete):
1. Start and run the nozzle at https://github.com/jghiloni/test-log-nozzle outside of CF (for ease)
1. Push the app at https://github.com/jghiloni/cfclient-msgsize-test
1. Hit https://msg-test.<APP_DOMAIN>/msg/<SIZE> starting at 4096 and working down until the nozzle works. In our environment, that was 3946.

How I tested:
I added a line in `ReactorDopplerEndpoints::toEnvelope` to make it look like this:

```
private static Envelope toEnvelope(byte[] bytes) {
        try {
            // added this line
            System.out.println("Envelope size: " + bytes.length);
            return Envelope.from(org.cloudfoundry.dropsonde.events.Envelope.ADAPTER.decode(bytes));
        } catch (IOException e) {
            e.printStackTrace();
            throw Exceptions.propagate(e);
        }
    }
```

And watched for my messages to come through to note 4096, and correlated to the message size. This matches what we saw with fewer debugging options on my client's system.

**Comment by nebhale** [comment]
Thanks for the detailed report.  I'll take a look shortly.

**Comment by nebhale** [comment]
@jghiloni What versions of the Java Client and Reactor Netty are you working with?

**Comment by jghiloni** [comment]
This was Client 2.4.0.RELEASE and Reactor Core 3.0.5.RELEASE, and also seen on 2.3.0.RELEASE/3.0.4.RELEASE

**Comment by nebhale** [comment]
And `reactor-netty 0.6.0.RELEASE`?

**Comment by jghiloni** [comment]
We actually aren't bringing in `reactor-netty`. The app is just a firehose nozzle and only has web enabled for actuators.

**Comment by nebhale** [comment]
`reactor-netty` is a dependency under `cloudfoundry-client-reactor` that we use for our networking stack.  So it'll be in the dependency tree somewhere.  It's undergone some major changes recently, so I just want to ensure that you're on a version that I'm testing with.

**Comment by jghiloni** [comment]
I ran `mvn help:effective-pom` and it's not there, and it's not listed under `External Libraries` in IntelliJ.

**Comment by nebhale** [comment]
[Hmm....](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/pom.xml#L68-L71)

**Comment by jghiloni** [comment]
Found it! Sorry about that, don't know why I couldn't see it. It's not in the effective pom, but I did find it in IntelliJ. Yes, it's `0.6.0.RELEASE`.

**Comment by nebhale** [comment]
Not your fault, I'm sure.  Thanks for the info, working on it now.

**Comment by nebhale** [comment]
OK, the fix has been made in [`reactor-netty 0.6.2.BUILD-SNAPSHOT`](https://github.com/reactor/reactor-netty/compare/bd7bcf837fa4bd5df7ba9c2f87b5a200c4145777...reactor:d36c9f8fb2e4c0bca7da95b94e416d7295687705).  You can test your code by adding

```
<dependency>
  <groupId>io.projectreactor.ipc</groupId>
  <artifactId>reactor-netty</artifactId>
  <version>0.6.2.BUILD-SNAPSHOT</version>
</dependency>
```

to it.  There's no definite date on that release, but it should be soon, and we'll do a release with it as soon as it possible.

**Comment by nebhale** [comment]
@jghiloni Any chance that you've gotten a chance to test this?  We're planning a release this evening or tomorrow and wanted to see if you've seen any improvement.

**Comment by jghiloni** [comment]
Yeah, sorry I didn't report back. It solved the problem completely,  since the envelope size is bigger than the biggest message Diego allows before splitting it into multiple messages. Thanks!

**Comment by nebhale** [comment]
Great to here.  Release soon.
