### ISSUE TITLE
The token valid time

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-java-client#689]
Hey team
I look this the project source , but i not find how to get the token valid time.
The cf-java-client jar  when the token out of data, it will auto get new token?
Our team would like to obtain the current token of the effective time to determine whether the current user login is valid.

**Comment by nebhale** [comment]
Token issue and expiration times are [logged when tokens are negotiated](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L129-L130).  You can enable this logging by setting [`cloudfoundry-client.token` to `DEBUG`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L60).

Any time the server returns a `401` (that the current authorization is invalid), the [client invalidates the token](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/util/AbstractReactorOperations.java#L237-L240) and re-subscribes to the original request.  That re-subscription causes a new token to be negotiated.
