### ISSUE TITLE
Deadlock when performing request within filter

### ISSUE THREAD

**Issue by yshewchuk** [cloudfoundry/cf-java-client#715]
Hello,

When running the following sample code, I run into deadlock and the results are never displayed:

```
ConnectionContext connectionContext = DefaultConnectionContext.builder()
    .apiHost(checkNotNull("<our api address>"))
    .skipSslValidation(true)
    .build();

TokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
    .username("<username (using an admin user for testing)>")
    .password("<password (using an admin user for testing)>")
    .build();

CloudFoundryClient client = ReactorCloudFoundryClient.builder()
    .connectionContext(connectionContext)
    .tokenProvider(tokenProvider)
    .build();

List<OrganizationResource> orgs = PaginationUtils
    .requestClientV2Resources(page -> client.organizations()
        .list(ListOrganizationsRequest.builder()
            .build()))
  
    // filter out any orgs that have four or fewer spaces
    .filter(o -> client.organizations()
        .listSpaces(ListOrganizationSpacesRequest.builder()
            .organizationId(o.getMetadata().getId())
            .resultsPerPage(1)
            .page(1)
            .build())
        .map(response -> response.getTotalResults() > 4)
        .block())
      
    // wait for the results
    .collectList()
    .block();

// print out results
for (OrganizationResource o : orgs) {
    System.out.println(o.getEntity().getName());
}
```

The following are the (sanitized) logs starting at the point where the communication begins (after initialization of the client):
[deadlock_log.txt](https://github.com/cloudfoundry/cf-java-client/files/851976/deadlock_log.txt)

Any ideas why this might be happening? It appears to be related to connection pooling (perhaps the previous request is not quite done with its connection?) based on what I can make of the logs.

I can work around this by doing a flatMap and returning either the original value or an empty mono based on the results of the inner query. I suspect that it may have something to do with the filter method signaling a request when the predicate returns false, but I'm not entirely sure. 

Thanks in advance for any assistance you can provide.
Yuri

**Comment by nebhale** [comment]
Yeah, this issue is almost undoubtedly due to the use of `block()` within another flow.  That's never the answer and likely to cause all sorts of thread and connection deadlocks.  You might reach out to the Reactor team for confirmation of this, but that's almost certainly it.

**Comment by yshewchuk** [comment]
Thanks for the quick response. That could very well be, is that to say that you consider this 'by design'? I suppose you would suggest going with the workaround, then? I was hoping to be able to use the filter method as it makes it much more clear what the intent is. Perhaps I should discuss with the Reactor team to see about a filter method that uses a Mono<Boolean> instead.

**Comment by nebhale** [comment]
I agree that there is some evidence that `filter(Function<T, Mono<Boolean>>)` might be interesting (/cc @smaldini), but it's not required in order to use `filter` here.  I'm going to freehand this, so the odds of it even compiling are low, but you should get the idea:

```
CountDownLatch latch = new CountDownLatch(1);

PaginationUtils
    .requestClientV2Resources(page -> client.organizations()
        .list(ListOrganizationsRequest.builder()
            .page(page)
            .build()))
    .then(organizationResource -> client.organizations()
            .listSpaces(LisOrganizationSpacesRequest.builder()
                .organizationId(ResourceUtils.getId(organizationResource))
                .resultsPerPage(1)
                .page(1)
                .build())
        .map(PaginatedResponse::getTotalResults)
        .and(Mono.just(organizationResource))
    .filter(function((spaceCount, organizationResource) -> spaceCount > 4))    
    .map(function((spaceCount, organizationResource) -> organizationResource)
    .map(organizationResource -> ResourceUtils.getEntity(organizationResource).getName())
    .subscribe(System.out::println, t -> {
        t.printStackTrace();
        latch.countDown();
    }, latch::countDown);

latch.await();
```

The key stanza is:

```
        .and(Mono.just(organizationResource))
    .filter(function((spaceCount, organizationResource) -> spaceCount > 4))    
    .map(function((spaceCount, organizationResource) -> organizationResource)
```

In this, we attach the space count to the original resource as a context (in a `Tuple`), then filter upon that count, and then extract the resource from the context that was attached to it for further usage.  Not as elegant as being about to return a `Mono<Boolean>` for a predicate, but serviceable for today.
