### ISSUE TITLE
Delete user problem

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-java-client#716]
Hi team:
   There isn't create user and delete user method in the CloudfoundryReactorClient?
   If i use uaaClient to create user,it will sent `/Users` and  use cloudfoundry cli to create user,it will sent two request,uaa `/Users`,cloudfoundry api `/v2/users` . I want to find create user method in coudfoundryClient,but didn't find.Though use uaaClient created the user can also use.
  The focus is on i use delete user method in uaaClient, it only delete uaa user info and delete username in cloudfoundry db,but user guid and related permission info is still in cloudfoundy db.Therefore,i want to find delete user method in cloudfoundryClient, but isn't find also.

**Comment by twoseat** [comment]
Hi @geekyzk - the full range of user features you're looking for were added in [2.5.0.RELEASE](https://github.com/cloudfoundry/cf-java-client/tree/v2.5.0.RELEASE/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/users), so I suspect you need to upgrade the version you're using (we're currently at 2.7.0.RELEASE).

**Comment by geekyzk** [comment]
Oh,thanks, i use 2.2.0.RELEASE.


On 03/21/2017 17:25，Paul Harris<notifications@github.com> wrote：

Hi @geekyzk - the full range of user features you're looking for were added in 2.5.0.RELEASE, so I suspect you need to upgrade the version you're using (we're currently at 2.7.0.RELEASE).
