### ISSUE TITLE
Cannot List Service Usage Events

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cf-java-client#717]
Hi,

When listing service usage events, I get following error

```
Cannot construct instance of org.cloudfoundry.client.v2.serviceusageevents.ServiceUsageEventEntity, problem: Cannot build ServiceUsageEventEntity, some of required attributes are not set [servicePlanName]
```

It appears that servicePlanName is configured as mandatory in [_ServiceUsageEventEntity](https://github.com/cloudfoundry/cf-java-client/blob/d0cd4dae1872afdfdb8be92cba9548ee992e4993/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/serviceusageevents/_ServiceUsageEventEntity.java)
```java

    /**
     * The service plan name
     */
    @JsonProperty("service_plan_name")
    abstract String getServicePlanName();
```

But I could not find such a constraint in [Service Usage Events API](https://apidocs.cloudfoundry.org/253/service_usage_events/list_service_usage_events.html).

Is there any reason for that ?

Thanks in advance

sebastien

**Comment by twoseat** [comment]
@s-bortolussi My apologies, there's no obvious reason for this, looks like it was just an oversight. A fix will be available in a build snapshot very soon.

**Comment by s-bortolussi** [comment]
@twoseat Great ! Thanks for your quick response

**Comment by s-bortolussi** [comment]
@twoseat The fix works perfectly. Thanks
