### ISSUE TITLE
Push application with manifest file

### ISSUE THREAD

**Issue by hongnguyenthanh** [cloudfoundry/cf-java-client#721]
Hi All,
I was looking for a method in cloudfoundry-operation that helps to push application with information indicated in a manifest.yml file but haven't found any. Could you let me know if this is possible with  cloudfoundry-operation, or cloudfoundry-client?

Thanks
Hong

**Comment by twoseat** [comment]
Hi Hong, I'm currently working on that very feature, tracked in #216. I don't have an exact date for when it will be available (it's quite complicated!) but barring an emergency release it should be in 2.9.0.RELEASE.

**Comment by nebhale** [comment]
Closed in lieu of #216
