### ISSUE TITLE
[Doc] better explain basic CloudFoundryOperations usage in readme

### ISSUE THREAD

**Issue by xfabre** [cloudfoundry/cf-java-client#726]
Hi,

in the readme you give a basic example of CloudFoundryOperations usage:

`cloudFoundryOperations.organizations().list().map(Organization::getName).subscribe(System.out::println);
`

1. Seems like `map(Organization::getName)` should be `map(OrganizationSummary::getName)`
2. If one total beginner copy/paste the code in a java main it will exit without doing anything.
you should provide a way to block until the println is done or point to a documentation that explains how to do it.

Thanks!

**Comment by nebhale** [comment]
There are clearly some dated references in the docs and we'll get them updated, but I'm not keen on changing the sxample such that it is blocking.  My concern is that having one of the primary example be blocking will lead to copy-and-pasting of that blocking code in real applications.  This is the entire thing that we're trying to avoid.

**Comment by xfabre** [comment]
Fair enough. 
Perhaps a guide for those who are upgrading from 1.1.* to 2.* version would be the right place to explain best practises and anti-patterns.
