### ISSUE TITLE
Verify current user info is true problem?

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-java-client#727]
Hi team:
   When config the cloudfoundryClient,the client default is not login before using any api.Of course,i can using a api to check the user info is true.
   How do I verify that the user info is correct when registering TokenProvide?

**Comment by nebhale** [comment]
Is the goal to have an authentication failure on bean creation rather than first use of the API?

**Comment by geekyzk** [comment]
Yes, because I would like to use cf user authentication system to verify the current login user information is correct

**Comment by nebhale** [comment]
As I think you've realized, you can just make any call with the API in order to trigger a token negotiation and failure.  Alternatively, you can call `tokenProvider.getToken(connectionContext).block()`.  This is the underly behavior that the API would use.

**Comment by geekyzk** [comment]
Thank you for solving my problem

**Comment by nebhale** [comment]
No problem.
