### ISSUE TITLE
Service access

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#729]
Hi,

I can't seem to find a way to retrive the services along with their service plans without targeting a space.
In CLI it is available via `cf service-access`, what am I missing ? :/

Thanks!
Andrea.

**Comment by nebhale** [comment]
It would be on the [`ServiceAdmin`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/2.8.0.RELEASE/org/cloudfoundry/operations/serviceadmin/ServiceAdmin.html) interface, but has not yet been implemented.

**Comment by andreaAlkalay** [comment]
So, is there any other way to recieve the list of service plans for an administrator ?
(WIthout targeting a space)

**Comment by nebhale** [comment]
Not at the moment. As you can see from the history of this issue, it's been assigned to the next releas.
