### ISSUE TITLE
How to get status login to CF instance

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry/cf-java-client#733]
Hi All,
I initialize DefaultCloudFoundryOperations as following

```
DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
    .apiHost(host)
    .build();

PasswordGrantTokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
    .password(password)
    .username(user)
    .build();

ReactorCloudFoundryClient cloudFoundryClient = ReactorCloudFoundryClient.builder()
    .connectionContext(connectionContext)
    .tokenProvider(tokenProvider)
    .build();

DefaultCloudFoundryOperations operations = DefaultCloudFoundryOperations.builder()
    .cloudFoundryClient(cloudFoundryClient)
    .organization(org)
    .space(space)
    .build();
```

Could you tell me if there is any way to know if login has been successful or not. 

Thanks,
Van

**Comment by stipx** [comment]
@ngocvanho here is what I've done to check if the credentials are correct:
`tokenProvider.getToken(connectionContext).subscribe().block(loginTimeout);`

At least this one fails when the credentials are wrong. But I also wonder why an operation just silently doesn't work if the credentials are wrong.

**Comment by nebhale** [comment]
@ngocvanho The first use of the API will trigger a token to be negotiated.  This can be by calling either the client or the operations; either will make a call to the server trigger token negotiation and a failure if the credentials are incorrect.  If you'd like to aggressively negotiate a token (rather than lazily on usage), using @stipx's example of requesting a token directly from the `TokenProvider` will work.  I might go with a slightly more semantically correct version like:

```
tokenProvider
    .getToken(connectionContext)
    .next()
    .block(timeout);
```

but the resulting behavior is the same.

**Comment by nebhale** [comment]
@stipx An operation will not silently fail if the credentials are incorrect.  The token is only lazily negotiated when needed, so creation of a `*Client` or `Operations` will succeed because they do not negotiate tokens.  Only usage of those instances will negoatiate a token causing a credential-based failure.

**Comment by ngocvanho** [comment]
@stipx, 
thanks for your response.

**Comment by ngocvanho** [comment]
@nebhale, @stipx,
Thanks for your response.
I have a question,   when i push app, code as following:

     DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
        .apiHost(host)
        .build();

    PasswordGrantTokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
        .password(password)
        .username(user)
        .build();

    ReactorCloudFoundryClient cloudFoundryClient = ReactorCloudFoundryClient.builder()
        .connectionContext(connectionContext)
        .tokenProvider(tokenProvider)
        .build();

    DefaultCloudFoundryOperations operations = DefaultCloudFoundryOperations.builder()
        .cloudFoundryClient(cloudFoundryClient)
        .organization(org)
        .space(space)
        .build();

    PushApplicationRequest pushAppRequest = PushApplicationRequest.builder()
                    .application(new ClassPathResource(nameFile).getFile().toPath())
                    .name(nameApp).buildpack(buildPack).instances(instance).memory(memory)
                    .command(command).noStart(flagStart).stagingTimeout(Duration.ofMinutes(2))
                    .startupTimeout(Duration.ofMinutes(2)).build();
            
            operations.applications().push(pushAppRequest)
                    .doOnSuccess(x -> System.out.println("Push application success")).block();

When i execute, now calls to the Cloud Foundry instance, authenticate and execute to action push app?

Thanks, 
Van

**Comment by nebhale** [comment]
@ngocvanho Yes, you're exactly write.  Whenever the client needs a token (because it doesn't have one or because it's reached it's 5m expiration), it will renegotiate a token for usage in the request.  You might want to try a run with the `cloudfoundry-client` logger configured to `DEBUG`.  When you do, you'll see:

```
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/info
cloudfoundry-client.token             Negotiating using token provider
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/info
cloudfoundry-client.operations        START  Push Application
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/organizations?q=name:bhale&page=1
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/info (406 ms)
cloudfoundry-client.request           POST   https://login.run.pivotal.io:443/oauth/token
cloudfoundry-client.response          200    https://login.run.pivotal.io:443/oauth/token (726 ms)
cloudfoundry-client.token             Refresh Token: [REDACTED]
cloudfoundry-client.token             Refresh Token Issued At:  2017-04-18T13:31:10 UTC
cloudfoundry-client.token             Refresh Token Expires At: 2017-04-25T13:31:10 UTC
cloudfoundry-client.token             Access Token: [REDACTED]
cloudfoundry-client.token             Access Token Issued At:  2017-04-18T13:31:10 UTC
cloudfoundry-client.token             Access Token Expires At: 2017-04-18T13:41:10 UTC
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/info (1.7 s)
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/organizations?q=name:bhale&page=1 (1.1 s)
cloudfoundry-client.compatibility     Client supports API version 2.75.0 and is connected to server with API version 2.78.0. Things may not work as expected.
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/spaces?q=name:development&q=organization_guid:066210ab-1e72-4561-b6b5-1032753adde0&page=1
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/spaces?q=name:development&q=organization_guid:066210ab-1e72-4561-b6b5-1032753adde0&page=1 (500 ms)
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/spaces/8c84b5d3-d73d-413f-841c-c8b301bd6608/apps?q=name:test-application&page=1
cloudfoundry-client.request           PUT    https://api.run.pivotal.io:443/v2/resource_match
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/spaces/8c84b5d3-d73d-413f-841c-c8b301bd6608/apps?q=name:test-application&page=1 (330 ms)
cloudfoundry-client.request           PUT    https://api.run.pivotal.io:443/v2/apps/9735b25d-a425-48bf-ae5d-43fcb8bab534
cloudfoundry-client.response          201    https://api.run.pivotal.io:443/v2/apps/9735b25d-a425-48bf-ae5d-43fcb8bab534 (477 ms)
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/resource_match (4.8 s)
cloudfoundry-client.resource-matching 41 resources matched totaling 23.5 MiB
cloudfoundry-client.request           GET    https://api.run.pivotal.io:443/v2/spaces/8c84b5d3-d73d-413f-841c-c8b301bd6608
cloudfoundry-client.response          200    https://api.run.pivotal.io:443/v2/spaces/8c84b5d3-d73d-413f-841c-c8b301bd6608 (331 ms)
...
```

This should give you an idea of what the client is doing for each command that you execute.

**Comment by stipx** [comment]
@nebhale You're right. It does not fail silently. Was this fixed in recent versions? If I remember correctly the operation was just hanging if the credentials were wrong before. Thanks for the hint.

And just to mention: a "next()" does not exist for "tokenProvider.getToken()"

**Comment by nebhale** [comment]
@stipx It would have changed in [2.3.0.RELEASE](https://github.com/cloudfoundry/cf-java-client/releases/tag/v2.3.0.RELEASE) about three months ago.  And yes you're right, it's a `Mono`, not a `Flux` which means that you can go even simpler:

```
tokenProvider
    .getToken(connectionContext)
    .block(timeout);
```

**Comment by ngocvanho** [comment]
@nebhale,
I have a comment on issue #687, please response for me if you know this problem.
Thanks,
Van

**Comment by nebhale** [comment]
@ngocvanho That issue has been closed and I won't be commenting on it.  If you have new questions that are not related to this or another open issue, please open an issue dedicated to it.  If you are finished with this line of questioning, please close this issue out as complete.

**Comment by ngocvanho** [comment]
@nebhale 
Thank you very much for your help. I will close this issue.
