### ISSUE TITLE
What am I missing???? Please help!

### ISSUE THREAD

**Issue by jonbuck16** [cloudfoundry/cf-java-client#736]
I have followed the example of printing out a list of organization names as shown in the Readme.md file and my code literally does nothing.. it executes... but no output or exceptions, when I debug I can see it running over the code to list the organizations but it does nothing, no output, no exceptions, it doesn't matter if I put valid or invalid credentials into the token provider, nothing.....   So I don't get it, now unfortunately as my code is internal I cannot share it so I am really hoping that someone can provide with some pointers of what and where to check to ensure that I have this configured correctly as I would really like to use the library...

**Comment by twoseat** [comment]
Hi @jonbuck16 - clearly it's a little tricky without code, but I'd suggest you start by looking at #635, in particular the part about `CountdownLatch`, and see if that helps. Let me know how you get on!

**Comment by jonbuck16** [comment]
@twoseat Thank you very much, that link was very useful and I now have some working code

**Comment by twoseat** [comment]
Good to hear!
