### ISSUE TITLE
Allow setting if chunkedTransfer should be used on API calls

### ISSUE THREAD

**Issue by stipx** [cloudfoundry/cf-java-client#739]
Hi!

IBM has changed something in their login service that causes Gateway Timeouts when the "Transfer-Encoding: chunked" header is set on the token request for Bluemix. I already created a support request on IBM side to get that fixed. But in order to be able to workaround this (in case it will not be fixed or happens again) it would be highly appreciated to have the possibility to just set the chunked transfer to false on all REST calls (like it is when using the cf cli).

Thanks!

**Comment by nebhale** [comment]
When you saw this, were you able to determine if it happened on all requests or only on the token negotiation step?  BlueMix has always had an odd authentication/authorization system that differs from nearly every other CF instance in the world.

**Comment by stipx** [comment]
@nebhale I will check that again tomorrow in detail, but as I see it it's only a problem with the token negotiation. The info call to get the oauth URL seems to work fine. Else it would never get to the step where the negotiation is done. So it might help to just do not use chunked transfer for that one.

**Comment by stipx** [comment]
As promised I checked today and it is really just the token negotiation. Anyway I think that your solution (disabling it entirely) makes absolutely sense to be compatible to the cf-cli.

**Comment by stipx** [comment]
Can confirm that 2.10.0.RELEASE fixes the problem.

**Comment by nebhale** [comment]
Thanks for the update.
