### ISSUE TITLE
Disposing ChannelOperation from a channel

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry/cf-java-client#740]
Hi All,
I am constantly getting this error when i execute my action. Although it doesn't stop the program but this error appears many times into log. I don't know how to fix it.
Please help me fix it if you know this problem.
Below is my code: 

        pushAppRequest = PushApplicationRequest.builder()
                .application(new ClassPathResource(nameFile).getFile().toPath())
                .name(nameApp).buildpack(buildPack).instances(instance).memory(memory)
                .command(command).noStart(flagStart).stagingTimeout(Duration.ofMinutes(2))
                .startupTimeout(Duration.ofMinutes(2)).build();
        operations.applications().push(pushAppRequest)
                .retry()
                .doOnSuccess(x -> System.out.println("Push application success")).block();

The error was attached file below.

[log.txt](https://github.com/cloudfoundry/cf-java-client/files/953779/log.txt)

Thanks,
Van

**Comment by nebhale** [comment]
Per @smaldini, this is an intentional dump of the stack when a connection is disposed. It only exists at `TRACE` because it is useful for tracing. This is not a bug.
