### ISSUE TITLE
fuzzy query on select apps list

### ISSUE THREAD

**Issue by liuxg123** [cloudfoundry/cf-java-client#741]
The api can provide fuzzy query to get apps lists by app's name?

**Comment by nebhale** [comment]
The Java Client is a language binding on top of existing APIs; the `*Client` on top of the Cloud Controller, Doppler, Routing, and UAA APIs, the `*Operations` on top of the CF CLI APIs.  We don't introduce new behavior that does not exist in those areas.  If you'd like an API that does not yet exist, please contact those projects and have them add it.
