### ISSUE TITLE
Does the get method implement a fuzzy query?

### ISSUE THREAD

**Issue by Luyang1208** [cloudfoundry/cf-java-client#742]
the CAPI v2 get function have filter parameter  like "q=filter:value",does this sdk donot implement it? 

[http://apidocs.cloudfoundry.org/246/apps/list_all_apps.html](url)

**Comment by twoseat** [comment]
Hi @Luyang1208 - from your link the fields that can be filtered on are "name, space_guid, organization_guid, diego, stack_guid". If you look at the [equivalent request](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/_ListApplicationsRequest.java) on our api you'll see that those fields are included, allowing you to filter by their content. For example:

```
this.cloudFoundryClient.applicationsV2()
    .list(ListApplicationsRequest.builder()
        .name("test-name") //filter for apps with the name "test-name"
    .build())
```

Let me know if that doesn't answer your question!

**Comment by Luyang1208** [comment]
Thank you for your answer.
But I have tried this code. It can not accurately achieve my function.
There are three kinds of filtering logic for CAPI, namely q = filter: value, q = filter> value, q = filter IN a, b, c.
The underlying implementation of the SDK is q = filter IN a, b, c.
But it can not achieve the search, I now want to add a simple search function,
So I would like to know whether the SDK has other ways to achieve the search.
Thank you

**Comment by nebhale** [comment]
As you can see [in the documentation](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client/2.8.0.RELEASE/org/cloudfoundry/client/v2/applications/ListApplicationsRequest.Builder.html) and filter parameter that can validly take multiple arguments has the ability to do so in the API.  So for example, filtering on multiple names would look like:

```
this.cloudFoundryClient.applications()
    .list(ListApplicationsRequest.builder()
        .name("application-1")
        .name("application-2")
        .build());
```

Alternately you can use the varargs style:

```
this.cloudFoundryClient.applications()
    .list(ListApplicationsRequest.builder()
        .name("application-1", "application-2")
        .build());
```

Or even the collection style:

```
List<String> names = Arrays.asList("application-1", "application-2");

this.cloudFoundryClient.applications()
    .list(ListApplicationsRequest.builder()
        .names(names)
        .build());
```

**Comment by nebhale** [comment]
@Luyang1208 have you been able to query as you expected?

**Comment by Luyang1208** [comment]
@nebhale 
Thanks for you callback
In fact no.
I give you an example, I have application-1, application-2 two applications, in CAPI, i can use
`GET / v2 / apps? q = names: application`
`GET / v2 / apps? q = names: app`
You can query to application-1 and application-2 two applications.
I tried the API you said, but I could not get the query I needed. I tried to open the debug mode of the log and found the underlying implementation of the calling API
`GET / v2 / apps? q = names IN app`
```
this.cloudFoundryClient.applicationsV2()
    .list(ListApplicationsRequest.builder()
        .name("application-1")
        .name("application-2")
        .build());
```
The underlying call to the method is
`GET / v2 / apps? q = names IN app`

> the CAPI address : http://apidocs.cloudfoundry.org/246/apps/list_all_apps.html

Use the 'IN' method query in this case can not query my application-1 and application-2 these two applications

**Comment by nebhale** [comment]
I'm not sure exactly what you think the issue is here.  That matches what the API defines.  Given two possible application names, it searches for any application that has a name in that collection.

**Comment by Luyang1208** [comment]
@nebhale
thanks for your callback
did not let you understand what I mean because my English ability is not very good.
it is my fault.
I temporarily removed the query function, so I do not need that API now.
really thank you

**Comment by Zteve** [comment]
I believe the user was asking for wildcard support.

**Comment by nebhale** [comment]
No worries @Luyang1208.  If you are looking for wildcard support, then the answer is that we're limited by what the Cloud Controller API provides.  We only provide a language binding on top of what those APIs provide.  If you'd like to see those APIs expanded to support wild cards, then you can [open an issue](https://github.com/cloudfoundry/cloud_controller_ng/issues) with the Cloud Controller.

In lieu of that, you could do the following:

```
Pattern pattern = Pattern.compile("app.*");

PaginationUtils
    .requestClientV2Resources(page -> this.cloudFoundryClient.applicationsV2()
        .list(ListApplicationsRequest.builder()
            .page(page)
            .build()))
.filter(application -> pattern.matcher(ResourceUtils.getEntity(application).getName()).matches())
.subscribe(System.out::println);
```

**Comment by Luyang1208** [comment]
@nebhale thank you. i know that
