### ISSUE TITLE
If TokenProvider fails to get a token client doesn't recover until "invalidate()" is called

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#749]
Below is a simple test case.  To duplicate:
* Start with UAA down
* When prompted start UAA
* Notice that second call fails

```
		DefaultConnectionContext connectionContext = DefaultConnectionContext.builder().apiHost("api.cf.com")
				.build();

		TokenProvider tokenProvider = ClientCredentialsGrantTokenProvider.builder().clientId("client")
				.clientSecret("secret").build();

		CloudFoundryClient cfClient = ReactorCloudFoundryClient.builder().connectionContext(connectionContext)
				.tokenProvider(tokenProvider).build();

		try {
			cfClient.services().list(ListServicesRequest.builder().resultsPerPage(100).build()).block();
			System.out.println("Shouldn't make it this far because UAA is down. FAILING");
			System.exit(-1);
		} catch (Exception e) {
			System.out.println("First request failed as expected because UAA is down.");
		}

		System.out.println("Start UAA Now.  Waiting 60 sec.");

		Thread.sleep(60000);

		try {
			cfClient.services().list(ListServicesRequest.builder().resultsPerPage(100).build()).block();
			System.out.println("Successfully ran second time when UAA was up.  That is what I'd expect.");
			System.exit(0);
		} catch (Exception e) {
			System.out.println("Why did we fail this time?  It should succeed because UAA is now up.");
			throw e;
		}
```

Appears to be because of https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L256

According to @nebhale failures are cached "Otherwise every single subsequent request would hammer on the UAA."

Perhaps instead of caching indefinitely it could be cached for some short period like 1-5 sec?  Surely UAA won't get hammered too bad with a retry every couple of seconds?

**Comment by youngm** [comment]
This same problem exists with the cached call to the CC's /v2/info endpoint.  https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java#L148

So, this is another thing that we'd have to come up with a reasonable retry strategy for.

**Comment by nebhale** [comment]
Yep, we'd need to keep an eye on everywhere we use `.cache()`. Luckily it's not very many places (outside of test code).

**Comment by nebhale** [comment]
@youngm Any thoughts on how this should behave when the server is down?  Should it pass the error through, or just not pass along any value until success or retry timeout?

**Comment by youngm** [comment]
@nebhale I think it should pass the error through.

**Comment by nebhale** [comment]
I'm looking at this today and I'm a bit torn about how to solve it.  The problem is that there are a couple of places where we cache something derived from the previously cached thing.  The easiest example of this is that we cache both the "root" payload (which might be down) as well as the token derived from information in that root payload and the UAA.  Therefore, you'll need to configure cache durations in two places to truly solve the issue (once for the root payload, the other for the call to the UAA).  This doesn't excite me.  Let me think on it some more.

**Comment by nebhale** [comment]
@youngm I'm pretty happy with how this turned out.  The default is still cached forever, but you can override in two places.  The first is in the `ConnectionContext` which affects _nearly_ everything.  You can also affect the cached `organizationId` and `spaceId` on `CloudFoundryOperations`, but I'm not sure how much that matters for your usage.

Note that this is also only in 3.x as it's a Reactor 3.1 feature.  This is likely to mean that you're going to need to make an incompatible API upgrade as well 😬

**Comment by youngm** [comment]
@nebhale That sounds like it should work fine conceptually.  I'll try to find time to give it a try and post back.  Our code now isn't very reactive so I don't think the 3.1 upgrade should give us too much trouble.

**Comment by nebhale** [comment]
The Reactor 3.1 [release announcement](https://spring.io/blog/2017/09/28/reactor-bismuth-is-out) will help you make sense of any confusing API changes.

**Comment by youngm** [comment]
@nebhale tested it out.  Everything appears to work as expected.  If it caches a failed attempt then that failure is renewed when the dependent service (UAA or CC in this case) is back up.  So, I think you can close this issue.

That said, this may be the best solution we can provide for a reactive client like this one.  However, I think it is a sub optimal final solution.

As I was testing this I found myself wondering what a good Duration would be.  Too high a value and my service goes down for longer when it caches a bad value.  Too low a value and I am requesting more tokens from UAA than I need to and I may be exposing my users to more outages.  If UAA happens to be down when it comes time to refresh the cache the service will fail for the Duration of the cache even though the token it already had was perfectly fine.

I think that optimally the cf-java-client should be able to cache a valid oauth token until near its expiration.  But, if the last attempt to get a token failed then that should be retried every X seconds until it is successful again.

I understand that might not be possible with reactor today, but, thought I'd throw it out there for you to stew on long term.  Until then I think the fixed expiration duration is good enough to work around the problem described in the issue.

Thanks!

**Comment by nebhale** [comment]
I've begun discussions with the Reactor team about this so I'm going to close out this issue.  I'm definitely aware of the issue and will ensure that something gets done if it can be.
