### ISSUE TITLE
How to get information about the currently logged in user?

### ISSUE THREAD

**Issue by Luyang1208** [cloudfoundry/cf-java-client#752]
for example, the following information

> {
  "user_id" : "3587ef54-6361-44d2-b8a1-4937674aa2b5",
  "sub" : "3587ef54-6361-44d2-b8a1-4937674aa2b5",
  "user_name" : "yH9Avc@test.org",
  "given_name" : "PasswordResetUserFirst",
  "family_name" : "PasswordResetUserLast",
  "email" : "yH9Avc@test.org",
  "phone_number" : "+15558880000",
  "previous_logon_time" : null,
  "name" : "PasswordResetUserFirst PasswordResetUserLast"
}

**Comment by twoseat** [comment]
Hi @Luyang1208 - I believe that's a relatively new endpoint that we don't yet support. Thanks for pointing it out, we'll make it a priority now we know someone is looking for it.

**Comment by Luyang1208** [comment]
@twoseat ok,i got it.
