### ISSUE TITLE
Error OCCURRED: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by AbhishekGupta423** [cloudfoundry/cf-java-client#755]
When I am converting small PDF file (10 pages) to XML through Adobe Experience Manager, it works correctly. But when I am converting big PDF file (90 pages) to XML through Adobe Experience Manager, it gives me this error. 
 I have already added lines given below, but it is not working. 

ServerSocket serverSocket = null;
serverSocket = new ServerSocket(3333);
 serverSocket.setSoTimeout(600000);

So, can anyone help me out in this?

**Comment by nebhale** [comment]
I do not believe that this is the right project for this issue.
