### ISSUE TITLE
Creating a uaa user should allow to set passwordChangeRequired flag

### ISSUE THREAD

**Issue by Affy01** [cloudfoundry/cf-java-client#758]
The passwordChangeRequired  in uaa/account/UserAccountStatus.java can be used to force a user to change passwords on first login. Creating a user using the CreateUserRequest class does not allow to set this passwordChangeRequired variable.

**Comment by twoseat** [comment]
Hi @Affy01 - I've looked into this, and I don't think this option is available in the underlying UAA API. It's not [documented](https://docs.cloudfoundry.org/api/uaa/#create64) and trying it manually gives an `unrecognized field` error. I'm very happy to be proven wrong if you know different! In the meantime I agree it would be a sensible feature, but without the underlying support it's not something we'll implement. You may want to raise an enhancement request against [uaa](https://github.com/cloudfoundry/uaa/issues).

The good news is there is a separate endpoint just for [forcing a password expiration](https://docs.cloudfoundry.org/api/uaa/#force-user-password-to-expire), which I'll start work on shortly. Once that's implemented you can at least chain the `create` and `expire` requests to achieve your goal.
