### ISSUE TITLE
java.lang.UnsupportedOperationException 	at org.apache.http.impl.client.InternalHttpClient.getParams

### ISSUE THREAD

**Issue by abinavaraamK** [cloudfoundry/cf-java-client#760]
I am trying to connect to bluemix using cf apis and create an instance there. Before that i am trying to login 
here is the code 

`CloudCredentials cred = new CloudCredentials(user, password);
CloudFoundryClient client = new CloudFoundryClient(cred,getTargetURL(target));
client.login();`

I am getting java.lang.UnsupportedOperationException  at CloudFoundryClient client = new CloudFoundryClient(cred,getTargetURL(target)) this line. 

**The Jars i am using are** 

> cloudfoundry-client-lib-1.0.0.jar
> httpclient-4.3-beta1.jar
> httpcore-4.3.jar
> spring-security-oauth2-1.0.0.RELEASE.jar
> servlet-api-2.5.jar
> spring-aop-4.1.6.RELEASE.jar
> spring-beans-4.1.6.RELEASE.jar
> spring-context-4.1.6.RELEASE.jar
> spring-core-4.1.6.RELEASE.jar
> spring-expression-4.1.6.RELEASE.jar
> spring-security-oauth2-1.0.0.RELEASE.jar
> spring-web-4.1.6.RELEASE.jar
> spring-webmvc-4.1.6.RELEASE.jar

**Comment by nebhale** [comment]
The Cloud Foundry Client 1.x line has been end of life for more than a year at this point and no further changes will be made to it.  My one recommendation is that you at least upgrade to 1.1.4 as it's the latest release that we will have made on that line.
