### ISSUE TITLE
ChangeUserPasswordRequest builder insists on 'oldPassword' being set, but it really is optional and needed for a 'reset password' operation.

### ISSUE THREAD

**Issue by james-fitzgerald** [cloudfoundry/cf-java-client#761]
The REST API for changing a users password can also be used to reset the password if the user has appropriate credentials (i.e. `uaa.admin` + `password.write`). However the `ChangeUserPasswordRequest` builder insisted on the `oldPassword` value being specified and that needs to be omitted when resetting another users password.

**Comment by nebhale** [comment]
@james-fitzgerald The [documentation](https://docs.cloudfoundry.org/api/uaa/#change-user-password) states it as `required`.  If you believe this is incorrect, can you please open an issue against the UAA and link it here?  Once they agree, we'll do the work to change it.
