### ISSUE TITLE
Trying to create a service, throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by abinavaraamK** [cloudfoundry/cf-java-client#763]
Hi,
 
I am using cloud foundry client lib jar for contacting Bluemix. I am trying to create a service in the bluemix using 
` CloudService service = new CloudService();
        service.setLabel("ClearDB");
        service.setName("Mydb");
        service.setPlan("Spark DB");
        client.createService(service);`

The error is thrown on createSerive line stating  java.lang.IllegalArgumentException Service plan Standard not found.
Bluemix shows the plan .I am attaching the screen shot of the page. 

![image](https://cloud.githubusercontent.com/assets/24788244/26721006/d872d3c2-47a7-11e7-81f8-f34788418f39.png)

I am using the following jars 

> cloudfoundry-client-lib-1.1.4.RELEASE.jar
> spring-core-4.1.6.RELEASE.jar
> httpclient-4.3-beta1.jar
> spring-web-4.1.6.RELEASE.jar
> commons-io-1.2.jar
> commons-logging-1.0.4.jar
> httpcore-4.3.jar
> spring-beans-4.1.6.RELEASE.jar
> jackson-core-2.4.1.jar
> jackson-databind-2.4.1.1.jar
> jackson-annotations-2.4.0.jar
> com.google.protobuf-2.4.0.jar
> javax.websocket-api-1.0-rc4.jar
> spring-security-crypto-3.1.0.RELEASE.jar

Am i doing anything wrong.
I tried various google links for a good example but i am not finding one. If there is any link please share.

**Comment by nebhale** [comment]
he Cloud Foundry Client 1.x line has been end of life for more than a year at this point and no further changes will be made to it.  This certainly appears as if some change has been made to CloudFoundry or BlueMix and it is now incompatible with the library.  We won't be fixing this incompatibility, so you'll either need to move to the currently developed 2.x line of the library or convince BlueMix to re-instate compatibility.

**Comment by abinavaraamK** [comment]
Ok Thanks .I tried various google links for a good example but i am not finding one. If there is any link please share.

**Comment by abinavaraamK** [comment]
I searched for 2.x jar, but cannot find one. Please provide a link for the jar.

**Comment by nebhale** [comment]
The [documentation](https://github.com/cloudfoundry/cf-java-client#dependencies) provides the Maven coordinates for the project's binaries.  The [usage](https://github.com/cloudfoundry/cf-java-client#usage) and [examples](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-apis) show how the API works.

**Comment by abinavaraamK** [comment]
Thank you. :-)
