### ISSUE TITLE
ReactorTasks ListTaskRequest getCommand() always null

### ISSUE THREAD

**Issue by amaline** [cloudfoundry/cf-java-client#773]
The following always fails since getCommand() is always returning null:

`    	
ReactorTasks rt=new ReactorTasks(context,Mono.just("api.fr.cloud.gov"),tp);

ListTasksResponse resp=rt.list(ListTasksRequest.builder().page(1).build()).block();
assertTrue(resp.getPagination().getTotalResults() > 0);

TaskResource task=resp.getResources().get(0);
assertTrue(task.getCommand() != null);
`

**Comment by amaline** [comment]
Figured out that the TaskResource returned by list does not contain the command, an additional "get" with a GetTaskRequest needs to be done for each task.  Is there a way from the ReactorTasks to easily get all of the tasks for an application?

**Comment by nebhale** [comment]
@amaline This is also an inappropriate way to use the API.  Please see [the documentation](https://github.com/cloudfoundry/cf-java-client#usage) about building and using the top-level types.
