### ISSUE TITLE
CreateUserRequest for LDAP

### ISSUE THREAD

**Issue by grossth** [cloudfoundry/cf-java-client#784]
According to https://docs.pivotal.io/pivotalcf/1-9/opsguide/external-user-management.html only `origin`, `externalId`, `username` and one email is required for adding a user from a ldap. But `CreateUserRequest` always requires password and name and the request will fail with the following error:

```
Exception in thread "main" java.lang.IllegalStateException: Cannot build CreateUserRequest, some of required attributes are not set [name, password]
	at org.cloudfoundry.uaa.users.CreateUserRequest$Builder.build(CreateUserRequest.java:522)
```

**Comment by nebhale** [comment]
@sreetummidi The [documentation](https://docs.cloudfoundry.org/api/uaa/#create64) indicates that `name` and `password` are required.  Is this a doc issue?

**Comment by grossth** [comment]
I used the "uaac curl" command from https://docs.pivotal.io/pivotalcf/1-9/opsguide/external-user-management.html without password and name and it worked perfectly.  I assume, that the [documentation ](https://docs.cloudfoundry.org/api/uaa/#create64) is only refering to the case "origin=uaa"

A CreateUserRequest with name and password doesn't make sense, because I only want to create a reference to the user in the LDAP. The password might also be hashed in the LDAP, so with a required password, there is no possibility to add a LDAP user through the api.

**Comment by Priyata25** [comment]
@nebhale @grossth The documentation is only referring to the `origin=uaa` case. For external users `password` and `name` are not required.

**Comment by nebhale** [comment]
@Priyata25 Since the API docs are just "Create User" (not Create UAA User), can you please open an issue to update the docs to remove the required from those entries?

**Comment by Priyata25** [comment]
@nebhale https://www.pivotaltracker.com/story/show/148708665

**Comment by nebhale** [comment]
Great.  @twoseat You're good to go.

**Comment by grossth** [comment]
Thank you for working on this issue. But I assume that the change is not sufficient to fix the problem. There is an additional check in the class CreateUserRequest.Builder:


    public CreateUserRequest build() {
      if (initBits != 0) {
        throw new IllegalStateException(formatRequiredAttributesMessage());
      }
      return CreateUserRequest.validate(new CreateUserRequest(this));
    }

    private String formatRequiredAttributesMessage() {
      List<String> attributes = new ArrayList<String>();
      if ((initBits & INIT_BIT_NAME) != 0) attributes.add("name");
      if ((initBits & INIT_BIT_PASSWORD) != 0) attributes.add("password");
      if ((initBits & INIT_BIT_USER_NAME) != 0) attributes.add("userName");
      return "Cannot build CreateUserRequest, some of required attributes are not set " + attributes;
    }

**Comment by twoseat** [comment]
@grossth The code you quote is in a generated class. Once the project is rebuilt you'll find that code has changed. If you still see the problem behaviour please let me know!
