### ISSUE TITLE
Open Files Issue

### ISSUE THREAD

**Issue by jonbuck16** [cloudfoundry/cf-java-client#785]
I am using version 2.14 and I am seeing an issue where it looks like the client is generating a large number of open files and connections which never clear down, therefore over time the server hits it's open files limit and forces the restart of the server..  In my tests just the process of creating a client, and in particular creating a connection context 8-10 FIFO/pipe files are created plus a couple of TCP connections are created which never clear and that is even before we start making api calls for data..

Is there anyway to get the library to clear down the connection, disconnect or logout or any ideas as to why theses files would remain as open files and not cleared down?

**Comment by jonbuck16** [comment]
I should have probably mentioned that I am using the ReactorCloudFoundryClient

**Comment by jonbuck16** [comment]
If I use the 'lsof' command to look at open files, I see the following output after a connection context is established and these files never clear, and more appear after every request...

<img width="851" alt="openfiles" src="https://user-images.githubusercontent.com/16204568/28061685-536fea26-6623-11e7-9a38-a59446450f57.png">

**Comment by jonbuck16** [comment]
To be clear, when I say server has to restart,  I am talking about the Jenkins Server the java code is running on and not the PCF server

**Comment by nebhale** [comment]
@jonbuck16 Creating of a `ConnectionContext` is supposed to create all of the threads and connections expected to be used by the application.  Connections that are used generally are kept alive based on the `Keep-Alive` response from the server and therefore won’t clear down until that time period has elapsed. In addition, on startup connections are made to resolve SSL certificates, Client root endpoints (extracted via the `/v2/info` endpoint) and things like that.  So creation of a set of `*Client`s and `CloudFoundryOperations` would be expected to open a number of connections and those connections would be expected to be cached for some time, as specified by the server.

Would you characterize your experience as different from that?

**Comment by jonbuck16** [comment]
Hi @nebhale Yes my experience is different to that but that was purely my fault as I was essentially creating a ConnectionContext for every "transaction" that was being executed. After speaking with one of our contacts in Pivotal who pointed this out to me and I changed my code to use a shared ConnectionContext across all transactions it is unsurprisingly no longer continually generating these open files and that now makes sense..  As an aside we are not using and not able to use Spring therefore we are not benefiting from any of its magic so to speak so my question is do I need to do anything to correctly shut down the ConnectionContext/Client or do I not need to worry about it?

**Comment by nebhale** [comment]
Since you're now using a single `ConnectionContext` (you're supposed to have one per CF target, so typically one per application for most people), you probably don't need to have any shutdown behavior; you're VM shutdown and pool shutdown happen together.  But if you want to be explicit about it [`DefaultConnectionContext#dispose`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client-reactor/2.15.0.RELEASE/org/cloudfoundry/reactor/DefaultConnectionContext.html#dispose--) is what you're looking for.

**Comment by cwesdorp** [comment]
@jonbuck16 We had the same issue. Calling DefaultConnectionContext.dispose will resolve the issue but you can reuse it. Perhaps [issue 775](https://github.com/cloudfoundry/cf-java-client/issues/775) contains some background information which is also useful for you.
