### ISSUE TITLE
Pushing manifests fails when `disk_quota` is specified with units

### ISSUE THREAD

**Issue by sworisbreathing** [cloudfoundry/cf-java-client#792]
According to [Deploying with Application Manifests](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#disk-quota),

> This attribute requires a unit of measurement: `M`, `MB`, `G`, or `GB`, in upper case or lower case.

However when `disk_quota` is specified in this manner in the manifest file (for example: `disk_quota: 1024M`), `org.cloudfoundry.operations.applications.Applications.pushManifest()` fails with the following error:

```
org.cloudfoundry.client.v2.ClientV2Exception: CF-AppInvalid(100001): The app is invalid: disk_quota too little disk requested (must be greater than zero)
	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$0(ErrorPayloadMapper.java:47)
	at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$10(ErrorPayloadMapper.java:108)
	at reactor.core.publisher.MonoThenMap$ThenMapMain.onNext(MonoThenMap.java:120)
        ...
```

I've stepped through the code in a debugger and I can see that when the manifest is parsed by `org.cloudfoundry.operations.applications.ApplicationManifestUtils.read()`, it sets `disk` to 0 instead of the value in the manifest file. Looks like it's caused by calling `asInteger` instead of `asMemoryInteger` when parsing the `disk_quota` field in [ApplicationManifestUtils.toApplicationManifest](https://github.com/cloudfoundry/cf-java-client/blob/v2.16.0.RELEASE/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L241).

I'll open a PR shortly

This issue was originally reported by @sergiofm in [JENKINS-46049](https://issues.jenkins-ci.org/browse/JENKINS-46049).

**Comment by nebhale** [comment]
Closed in lieu of #793
