### ISSUE TITLE
Handle 170001 StagingError from CC when fetching application instance information

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-java-client#798]
The current implementation of `getApplicationInstances` handles errors like `CF_BUILDPACK_COMPILED_FAILED` and `CF_INSTANCES_ERROR` that can be returned from CC if the staging previously failed. However, the general `StagingError` (error code 170001) is not handled and will throw an exception when fetching application instances.

https://github.com/cloudfoundry/cf-java-client/blob/754d054b8bb1da82d291423b084f844dfc14f0d0/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L727

**Comment by justin-braathen** [comment]
I was able to confirm and verify that this resolves deployment issues ( _CF-StagerError(170011)_ )  when making the following API call.


**API Request**
```
GET /v2/apps/<APP-GUID>/instances HTTP/1.1
host: api.pdc.np.sys.paas.lmig.com
authorization: bearer
user-agent: CloudFoundryJavaClient/unknown (Java; Oracle Corporation/1.8.0_131) ReactorNetty/unknown (Netty/unknown)
accept: application/json
content-length: 0
```


**API Response**
```
HTTP/1.1 400 Bad Request
Content-Length: 133
Content-Type: application/json;charset=utf-8
Date: Tue, 15 Aug 2017 21:29:40 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: <ID>
X-Vcap-Request-Id: <ID>
Connection: Keep-alive

{
  "description": "Staging error: cannot get instances since staging failed",
  "error_code": "CF-StagingError",
  "code": 170001
}
```



**Code Change**
```
public final class DefaultApplications implements Applications {


+  private static final int CF_STAGING_ERROR = 170001;


    private static Mono<ApplicationInstancesResponse> getApplicationInstances(CloudFoundryClient cloudFoundryClient, String applicationId) {
-       return requestApplicationInstances(cloudFoundryClient, applicationId)
        		.onErrorResume(ExceptionUtils.statusCode(CF_BUILDPACK_COMPILED_FAILED, CF_INSTANCES_ERROR, CF_STAGING_NOT_FINISHED, CF_STAGING_TIME_EXPIRED),
        
+       return requestApplicationInstances(cloudFoundryClient, applicationId)
        		.onErrorResume(ExceptionUtils.statusCode(CF_BUILDPACK_COMPILED_FAILED, CF_INSTANCES_ERROR, CF_STAGING_NOT_FINISHED, CF_STAGING_TIME_EXPIRED, CF_STAGING_ERROR),
                t -> Mono.just(ApplicationInstancesResponse.builder().build()));
}

```


There is a related issue with the Bamboo Cloud Foundry Plugin (https://gaptap.atlassian.net/browse/CFBAMBOO-236) that is dependent on this change.

The cf-java-client:2.17.0 doesn't have a target release date, would it be possible to cut a patch-level release of cf-java-client:2.16.1?  

I do not currently have a CLA (individual or corporate) with Cloud Foundry on file so I am attaching the Java source and a GIT patch file.

[cf-java-client-pr-798.zip](https://github.com/cloudfoundry/cf-java-client/files/1235537/cf-java-client-pr-798.zip)

- cf-java-client.patch

- DefaultApplications.java (https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java)

**Comment by nebhale** [comment]
@justin-braathen We (almost) never set release dates ahead of time as we release quickly and flexibly.  So once we get this change in and determine that we’ve got a critical mass of improvement, we’ll just release.  There won’t be a 2.16.1, but 2.17 will come soon enough.

Any code that you contribute must be governed by a CLA; submitting patches won’t get around that unfortunately.  Now that we’ve reviewed your PR (polluting our knowledge), we’ll have to wait for a CLA on your contribution before this change can be included.

Finally, as there is now code submitted, PR #799 will supersede this issue and discussion will be moved there.
