### ISSUE TITLE
Add support for events endpoint

### ISSUE THREAD

**Issue by gberche** [cloudfoundry/cf-java-client#80]
The /v2/spaces/:guid/events CC REST endpoint provides useful information to list events related to an app such as start/stop by HM, or cause of an app stop/crash:

```json
 {
      "metadata": {
        "guid": "85edc0bd-6898-4d83-8be7-5b127ef49fff",
        "url": "/v2/events/85edc0bd-6898-4d83-8be7-5b127ef49fff",
        "created_at": "2013-09-03 10:08:29 +0000",
        "updated_at": null
      },
      "entity": {
        "type": "app.crash",
        "actor": "3d1ea022-ab7c-4f92-9a03-67ebd70f3d4f",
        "actor_type": "app",
        "actee": "3d1ea022-ab7c-4f92-9a03-67ebd70f3d4f",
        "actee_type": "app",
        "timestamp": "2013-09-03 10:08:29 +0000",
        "metadata": {
          "instance": "7ac29c442b4cdf80fb8125e2148b4ff2",
          "index": 0,
          "exit_status": 255,
          "exit_description": "out of memory",
          "reason": "CRASHED"
        },
        "space_guid": "2e5aee21-45fe-4032-a4d5-72e09035e170",
        "space_url": "/v2/spaces/2e5aee21-45fe-4032-a4d5-72e09035e170"
      }
    },

```

Note that the  /v2/apps/:guid/events is also exposed, but returned nothing when I tested it on api.run.pivotal.io

I'm proposing to add support for events into the vcap_java_client with a new domain.ApplicationEvent class returned by the following new methods:
* ```List<ApplicationEvent> CloudFoundryOperations.getEvents(int eventOffset, int maxEvents, long starttimestemps, long endtimestamp) ```
* and a shorter version ```List<ApplicationEvent> CloudFoundryOperations.getEvents() ```

The event endpoint is documented into https://github.com/cloudfoundry/cloud_controller_ng/blob/b8b8397922ed632ec59a0d4502a5a3f290afe02b/spec/controllers/core/app_events_controller_spec.rb

Anyone planning such contrib already or has suggestions for different API ?

**Comment by scottfrederick** [comment]
Fixed in #262
