### ISSUE TITLE
How to estimate the connection timeout

### ISSUE THREAD

**Issue by lijie-advantech** [cloudfoundry/cf-java-client#802]
I want to get some information from cloud foundry, first  i will connect to cloud foundry and obtain DefaultCloudFoundryOperations object, later i will use this object do something,  after a while, some operation will throw exception, i want to know how to estimate the connection timeout and i will connect  again.

**Comment by nebhale** [comment]
I’m not really sure what the question is here.  There shouldn’t need to be any estimation of a connection time out.  The Java Client is responsible for pooling and opening and closing connections as needed.  Configuring a connection timeout is almost certainly unnecessary except in extreme cases where network latencies are so so long that it takes multiple seconds to even *initiate* a connection.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
