### ISSUE TITLE
support for cf curl against /v2 or /v3 endpoints

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry/cf-java-client#804]
nice to have;

support for cf curl against /v2 or /v3 endpoints

allow one to hit various endpoints like https://apidocs.cloudfoundry.org/268/app_usage_events/list_all_app_usage_events.html

**Comment by twoseat** [comment]
@phopper-pivotal I'm sure you'll be pleased to learn that the endpoint you mentioned is already available (https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applicationusageevents/ApplicationUsageEvents.java#L32).

More generally, having a `cf curl` equivalent in the client would only be useful where we hadn't made specific provision for a desired endpoint. Given that we're working to match the CF API I'd rather spend the time filling specific gaps than creating a 'curl' fallback. If you have specific endpoints that you need please open issues for them and we'll make them a priority - to the best of my knowledge we've covered most of the popular ones, so feedback like that is really useful!

**Comment by nebhale** [comment]
Agreed.  At the moment, our priority is more or less random, so requests for specific APIs are useful as they help us move things up in the delivery list for you as you need them.  Since we can turn a new API in a couple of hours pretty reliably, I don’t think having `cf curl` to bridge the gap until implementation is useful for us to implement.

**Comment by phopper-pivotal** [comment]
@twoseat thank you for the details and understand the necessity to map to the specific CAPI endpoints.

@nebhale agree, see my statement above. maybe the ask then would be to provide a mapping of underlying call stack as it maps to CAPI. i searched all over to find this detail in the github repository. but not a priority.

**Comment by nebhale** [comment]
@phopper-pivotal I’m not sure what you mean by the underlying mapping.  [Each of the methods](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client/2.16.0.RELEASE/org/cloudfoundry/client/v2/applications/ApplicationsV2.html) maps onto an [API endpoint](http://apidocs.cloudfoundry.org/268/).  You’ll see [App Usage Events -> List All App Usage Events](http://apidocs.cloudfoundry.org/268/app_usage_events/list_all_app_usage_events.html) maps to [`ApplicationUsageEvents.list()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client/2.16.0.RELEASE/org/cloudfoundry/client/v2/applicationusageevents/ApplicationUsageEvents.html#list-org.cloudfoundry.client.v2.applicationusageevents.ListApplicationUsageEventsRequest-).  The documentation describes this as:

> Interfaces, request, and response objects mapping to the [Cloud Foundry REST APIs](https://apidocs.cloudfoundry.org/latest-release/).

In addition if there is any ambiguity, the Javadoc for each method links to the API that it implements:

![08151f2f-2490-4076-b88f-937d22aeccd1](https://user-images.githubusercontent.com/60754/29572102-1724c75e-8710-11e7-89c4-2908f0ab97d1.jpeg)

What more would you be looking for?

**Comment by phopper-pivotal** [comment]
@nebhale maybe provide a doc link in the javadoc to the respective API call as in

[API Usage Events -> List All App Usage Events](http://apidocs.cloudfoundry.org/268/app_usage_events/list_all_app_usage_events.html)

until a reference was provided it was not easy to find.

**Comment by twoseat** [comment]
Isn't that what https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applicationusageevents/ApplicationUsageEvents.java#L35 does?

**Comment by phopper-pivotal** [comment]
@twoseat yes. sorry been up since wee hours this AM.

**Comment by twoseat** [comment]
No worries, I'm working on some serious jet lag myself at the moment! And do let us know if there are particular endpoints you need, we have operators standing by!
