### ISSUE TITLE
Service plans

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#807]
Hi,

Is there a difference between `DefaultServiceAdmin.getServicePlans` and using `CloudFoundryClient.servicePlans()`?

Is it using a different CF rest API? does the second return ALL service plans?

Thanks,
Andrea.

**Comment by twoseat** [comment]
Hi @andreaAlkalay! The java client works at two levels, the client level, which provides direct access to the CF REST API, and the operations level, which replicates the functionality of the CF CLI.

So anything in `DefaultServiceAdmin` provides the functionality of [the CLI](https://docs.cloudfoundry.org/cf-cli/cf-help.html#service-admin), while `servicePlans()` provides access to [the REST API](https://apidocs.cloudfoundry.org/268/#service-plans).

Beyond this, however, `DefaultServiceAdmin.getServicePlans` is a private method and you shouldn't use it!

**Comment by twoseat** [comment]
If you haven't already, you should check out the readme for examples of using the [client](https://github.com/cloudfoundry/cf-java-client#cloudfoundryclient-apis) and [operations](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-apis) level APIs.

I suggest always starting at the operations level, only dropping down to the client level if you can't find what you need.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
