### ISSUE TITLE
How to authenticate with federated account?

### ISSUE THREAD

**Issue by ScottChapman** [cloudfoundry/cf-java-client#808]
My bluemix account is federated to W3. How am I able to login?

**Comment by twoseat** [comment]
Hi @ScottChapman - I'm not familiar with W3, is that an internal IBM SSO-type thing?

**Comment by ScottChapman** [comment]
Yea, sorry. Using with bluemix. I can use the cf login --sso from the command line, but that would have issues with this wouldn't it?

**Comment by nebhale** [comment]
@ScottChapman The answer lies in the `TokenProvider` interface.  We have a [number of implementations](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client-reactor/2.17.0.RELEASE/org/cloudfoundry/reactor/TokenProvider.html) but all are centered on using the UAA and it acting as a delegate to other systems.  If you have a grasp on how to negotiate at token with W3, we'd be happy to take a PR for it.  If not, and you have documentation, we could take a look at implementing it ourselves, but make no promises (especially if we can't get an account to test with).

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
