### ISSUE TITLE
Container to Container Networking Administration Operations Support

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cf-java-client#811]
Add operations support for container to container networking administration.  API described [here](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/ADC7OZBU6JG4YRIXFK3WTTLWYZ7EW3ZS/).

**Comment by cah-andrewfitzgerald** [comment]
Should I close #801 in favor of this?

**Comment by twoseat** [comment]
@cah-andrewfitzgerald They're actually different levels of operation - this is the operations layer, equivalent to the CLI. #801 (whether you meant it to be or not!) we're using as the client layer, i.e. the basic REST API. So we're using them both.

**Comment by cah-andrewfitzgerald** [comment]
cool cool, thanks
