### ISSUE TITLE
DefaultConnectionContext.dispose() Creates New Items to Dispose

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cf-java-client#815]
Currently, when `DefaultConnectionContext.dispose()` is called, it creates new instances of the connection pool and thread pool and then disposes them instead of the ones that were configured and used earlier.  The originally created connection pool and thread pool should be cached and disposed properly.

**Comment by chlam4** [comment]
@nebhale Thanks for fixing this so quickly!  When will 2.19 be released?

**Comment by nebhale** [comment]
I'd like you to give the snapshot a try and tell me if it fixes your issue.  Once I have that, I'll do the release.

**Comment by chlam4** [comment]
@nebhale Just tested it - it works perfectly for me!  Thank you so much again!
