### ISSUE TITLE
DefaultConnectionContext.dispose() does not destroy reactor-http-nio threads

### ISSUE THREAD

**Issue by chlam4** [cloudfoundry/cf-java-client#816]
Here is a simple program that tracks the number of reactor http nio threads before and after calling`dispose()`, and the results as I run it.  The thread count doesn't go back to 0 after calling `dispose()`.  I'm using `2.19.0.RELEASE`.

Program:
```
    public static void main(String[] args) throws InterruptedException {
        trackThreads("reactor-http-nio");
    }

    private static void trackThreads(final String threadPrefix) throws InterruptedException {
        System.out.println(threadPrefix + " THREAD COUNT");
        System.out.println("  (start) " + getThreadCount(threadPrefix));

        final DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
                .apiHost("api.run.pivotal.io")
                .build();
        System.out.println("  (after build) " + getThreadCount(threadPrefix));

        connectionContext.dispose();
        System.out.println("  (after dispose) " + getThreadCount(threadPrefix));

        Thread.sleep(10000);
        System.out.println("  (after 10 seconds) " + getThreadCount(threadPrefix));
    }

    private static long getThreadCount(final String threadPrefix) {
        return Thread.getAllStackTraces().keySet().stream()
                .filter(thread -> thread.getName().startsWith(threadPrefix)).count();
    }
```

Result:
```
reactor-http-nio THREAD COUNT
  (start) 0
  (after build) 8
  (after dispose) 8
  (after 10 seconds) 8
```

**Comment by nebhale** [comment]
Yep, pretty sure that this is a `reactor-netty` bug.  If you look at the [code](https://github.com/reactor/reactor-netty/blob/5881705f26cee5a85ed56a6e141cee9d92a2a9ea/src/main/java/reactor/ipc/netty/http/client/HttpClient.java#L81) a thread pool and a connection pool are both created before the options `Consumer` is executed.  When those pools are overridden by the options `Consumer`, they end up orphaned with no way to clean up after them.

/cc @violetagg @smaldini

**Comment by chlam4** [comment]
Any ETA for 2.21.0.RELEASE?

**Comment by nebhale** [comment]
Still waiting on a `0.6.6.RELEASE` from `reactor-netty`.

**Comment by chlam4** [comment]
I see - thanks.  Didn't realize the reactor-netty fix will be ported to the 0.6.x release.

**Comment by nebhale** [comment]
Yep, it's already there, just waiting on some other fixes to be backported and then it'll be released, allowing us to release as well.  The CFCJ 2.x/`reactor-netty` 0.6.x line will live for quite a while more, so it's important to have these fixes backported to it.

**Comment by nebhale** [comment]
@chlam4 Just conferred with the Reactor team and we're all aiming for a release at the end of this week.

**Comment by chlam4** [comment]
@nebhale Thanks for the update!
