### ISSUE TITLE
Client doesn't work with Stackato 3.6.2 since 2.17.0.RELEASE

### ISSUE THREAD

**Issue by chlam4** [cloudfoundry/cf-java-client#817]
Since `2.17.0.RELEASE`, this client doesn't seem to work Stackato 3.6.2 (API version 2.23.0).  It returns nothing for all GETs, e.g. `/v2/info`.  But it still works with Pivotal Cloud Foundry (API version 2.82).  Is the former version not supported any more?  `2.16.0.RELEASE` works with the same Stackato version.

The latest client seems to always start with the root URI (/).  The responses from Stackato 3.6.2 (CF API 2.23) and from Pivotal Cloud Foundry (API 2.82) are different - as below.

Response from Stackato 3.6.2 (API 2.23)
```
$ curl https://api.stackato.xyz.com -kv
* Rebuilt URL to: https://api.stackato.xyz.com/
*   Trying ##.##.###.### ...
* TCP_NODELAY set
* Connected to api.stackato.xyz.com (##.##.###.###) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.stackato.xyz.com
> GET / HTTP/1.1
> Host: api.stackato.xyz.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Location: https://api.stackato.xyz.com/console/
< Date: Wed, 20 Sep 2017 02:35:24 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host api.stackato.xyz.com left intact
```

Response from Pivotal Cloud Foundry (API 2.82)
```
$ curl https://api.sys.cf.xyz.com -kv
* Rebuilt URL to: https://api.sys.cf.xyz.com/
*   Trying ##.##.###.### ...
* TCP_NODELAY set
* Connected to api.sys.cf.xyz.com (##.##.###.###) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.cf.xyz.com
> GET / HTTP/1.1
> Host: api.sys.cf.xyz.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 448
< Content-Type: application/json;charset=utf-8
< Date: Wed, 20 Sep 2017 02:38:21 GMT
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: 1d6cad93-d619-4c9c-5fc6-715b9b1beecb
< X-Vcap-Request-Id: 7005efd3-129a-4c83-530c-1060c0d93b20::d8ea8e33-4ebd-4db0-8ee8-73295898595a
< 
{
  "links": {
    "self": {
      "href": "https://api.sys.cf.xyz.com"
    },
    "cloud_controller_v2": {
      "href": "https://api.sys.cf.xyz.com/v2",
      "meta": {
        "version": "2.82.0"
      }
    },
    "cloud_controller_v3": {
      "href": "https://api.sys.cf.xyz.com/v3",
      "meta": {
        "version": "3.17.0"
      }
    },
    "uaa": {
      "href": "https://uaa.sys.cf.xyz.com"
    }
  }
* Connection #0 to host api.sys.cf.xyz.com left intact
}
```

**Comment by nebhale** [comment]
At the moment, the oldest version of the CF API that we support is `2.58.0` (March 2016) but we’re planning on bumping that to `2.65.0` (November 2016) some time this week.  At the leading edge, we’re at `2.94.0` so I’m pretty comfortable given that we support nearly 30 revisions of the API, that we’re not going to go back and support `2.23.0` (71 revisions, March 2015).  The change is definitely related to us starting to prefer the root payload (which has been around for nearly a year) so I’ll take a look at it today.  If the problem is a simple error handling issue, I’ll fix it, but if it’s any more involved than that, I probably won’t.

**Comment by chlam4** [comment]
@nebhale Thanks a lot for the fixes for this and https://github.com/cloudfoundry/cf-java-client/issues/816.  I've just tried them out with the snapshot build, which works perfectly.  Any chance/plan to cut a release build?  Thank you!

**Comment by nebhale** [comment]
It’ll be sometime soon.  I’m waiting to determine if there’s a `reactor-netty` update that we can consume quickly, but if not, it’s likely to go out today.

**Comment by chlam4** [comment]
Thank you @nebhale!!
