### ISSUE TITLE
Unable to query recent application logs with CloudFoundryOperations

### ISSUE THREAD

**Issue by sworisbreathing** [cloudfoundry/cf-java-client#818]
I'm using cf-java-client for https://github.com/jenkinsci/cloudfoundry-plugin. For cf-java-client version 2.15.0.RELEASE (the version we're currently using), we were able to query recent application logs using `CloudFoundryOperations` like so:

```
cloudFoundryOperations
  .applications()
  .logs(
    LogsRequest.builder()
      .name(appName)
      .recent(Boolean.TRUE)
      .build()
  )
```

However it appears that from version 2.17.0.RELEASE onward, the above code fails and logs an `UnknownCloudFoundryException`.

Digging into the issue (and turning on debug logging for requests and responses), it looks like the old code was requesting recent logs from https://doppler.local.pcfdev.io/apps/:appId/recentlogs while the new (2.17.0.RELEASE and above) code is trying to request logs from https://loggregator.local.pcfdev.io:443/apps/:appId/recentlogs (which returns a 502 status).

**Comment by nebhale** [comment]
At the moment, the oldest version of the CF API that we support is `2.58.0` (July 15, 2016) but we’re planning on bumping that to `2.65.0` (Nov 17, 2016) some time this week.  At the leading edge, we’re at `2.94.0` so I’m pretty comfortable given that we support nearly 30 revisions of the API, that we’re not going to go back and support `2.23.0` (71 revisions, March 11, 2015).  The change is definitely related to us starting to prefer the root payload (which has been around for nearly a year) so I’ll take a look at it today.  If the problem is something like silly error handling, I’ll go ahead and fix it, but if it’s anything more involved, I probably won’t.

**Comment by nebhale** [comment]
Sorry about that; wrong issue.

**Comment by nebhale** [comment]
I cannot replicate that using the latest version of `pcfdev`.  I don't see any references to `loggregator.local.pcfdev.io`.  What version are you using?

```plain
$: cf dev version
PCF Dev version 0.28.0 (CLI: 5cda315, OVA: 0.547.0)
$: curl -sk https://api.local.pcfdev.io/ | jq .
{
  "links": {
    "self": {
      "href": "http://api.local.pcfdev.io"
    },
    "cloud_controller_v2": {
      "href": "http://api.local.pcfdev.io/v2",
      "meta": {
        "version": "2.82.0"
      }
    },
    "cloud_controller_v3": {
      "href": "http://api.local.pcfdev.io/v3",
      "meta": {
        "version": "3.17.0"
      }
    },
    "uaa": {
      "href": "https://uaa.local.pcfdev.io"
    }
  }
}
$: curl -sk https://api.local.pcfdev.io/v2/info | jq .
{
  "name": "pcfdev",
  "build": "4af54097fef22734d857410ddfb89ee979087911",
  "support": "pcfdev@pivotal.io",
  "version": 0,
  "description": "",
  "authorization_endpoint": "https://login.local.pcfdev.io",
  "token_endpoint": "https://uaa.local.pcfdev.io",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "api_version": "2.82.0",
  "app_ssh_endpoint": "ssh.local.pcfdev.io:2222",
  "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
  "app_ssh_oauth_client": "ssh-proxy",
  "routing_endpoint": "https://api.local.pcfdev.io/routing",
  "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443"
}
```

**Comment by sworisbreathing** [comment]
I'm running PCF Dev version 0.26.0:

```
$ cf dev version
PCF Dev version 0.26.0 (CLI: 1eef0f1, OVA: 0.461.0)
$ cf curl /v2/info
{
   "name": "pcfdev",
   "build": "a7463f020805516a312ba23414bcb0adcf73d455",
   "support": "pcfdev@pivotal.io",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://login.local.pcfdev.io",
   "token_endpoint": "https://uaa.local.pcfdev.io",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.75.0",
   "app_ssh_endpoint": "ssh.local.pcfdev.io:2222",
   "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
   "app_ssh_oauth_client": "ssh-proxy",
   "routing_endpoint": "https://api.local.pcfdev.io/routing",
   "logging_endpoint": "wss://loggregator.local.pcfdev.io:443",
   "doppler_logging_endpoint": "wss://doppler.local.pcfdev.io:443"
}

**Comment by nebhale** [comment]
Yep, and I didn't make the migration successfully, choosing the wrong endpoint.  I'll make sure there's a fix in the next release.
