### ISSUE TITLE
UserInfoResponse.previous_logon_time's value out of range of int

### ISSUE THREAD

**Issue by ziay420** [cloudfoundry/cf-java-client#822]
After update Cloud Foundry, the previous_logon_time seems to change to 64bit value.

**Comment by ziay420** [comment]
The reason caused this bug is UAA API returns a millisecond timestamp instead of a second timestamp. So previous_logon_time  can't handle the value.

**Comment by twoseat** [comment]
Thanks for the research, @ziay420, working on this now.
