### ISSUE TITLE
Create shared domain hangs if user doesn't have rights to read router groups

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-java-client#826]
FYI, it appears that if you try to create a shared domain with a router group and your user doesn't have access to read the router groups, the request will never complete.
```
        CreateSharedDomainRequest createSharedDomainRequest = CreateSharedDomainRequest.builder()
                .domain(domain.getName())
                .routerGroup(domain.getRouterGroup())
                .build();
        cf.domains().createShared(createSharedDomainRequest).block();
```
I turned on netty logging and could confirm that the client enters an infinite loop of trying to connect  to the routing api. I also confirmed that the response from the routing API is a 401. I would expect this to fail as soon as the 401 is encountered or at least after a few tries. This was tested with 2.20.0.RELEASE.

My problem was that the client id I was running with didn't have the correct scope to be able to read the router groups. I just thought I would report this in case someone runs into the same issue.

**Comment by nebhale** [comment]
Man that sounds like a bug in the CAPI API.  `401 Unauthorized` is used as an indicator that you need to present a token.  But you are presenting a token, it's just insufficient.  In that case the API is supposed to return a `403 Forbidden` that you aren't allowed to access this API given your current identity.  The client specifically depends on this 401/403 split in order to know when to re-negotiate an expired token.  I'm guessing that in your logging you saw repeated token refresh as well?

**Comment by forbushbl** [comment]
It seems like all the traffic was going to /routing/v1/router_groups so I don't think it was doing token refreshes.

**Comment by forbushbl** [comment]
Also, I just confirmed that adding routing.router_groups.read to my client's authorities causes the call to complete successfully.

**Comment by forbushbl** [comment]
@nebhale FYI, I opened https://github.com/cloudfoundry-incubator/routing-api/issues/14

**Comment by nebhale** [comment]
Looks good.  Thanks.

**Comment by nebhale** [comment]
@twoseat I’m somewhat surprised that this ends up in a loop rather than retrying negotiating a token a couple of times and then failing out.  You should take a look at why this is.

**Comment by nebhale** [comment]
@forbushbl We've identified some improvements that can be made on our side around some better caching of responses, but this isn't going to be solvable (it will continue to look like a hang) without a change from the routing side.  Once that change is made, it will happen transparently under the client, so no new release will be needed.  What's your opinion on us closing this out once we've got our improvements in place.  Would you prefer that we keep this open until the routing team fixes theirs or are you OK tracking the fix from their side alone?

**Comment by forbushbl** [comment]
@nebhale It sounds like you guys are all ready to take advantage of a routing api fix so feel free to close the issue. Thanks for the quick fix! I'm fine with tracking this on the routing api side.

**Comment by nebhale** [comment]
Sounds great.  Thanks for the flexibility.

**Comment by forbushbl** [comment]
@nebhale Is this fix going to find its way into the 3.x line?

**Comment by nebhale** [comment]
Already there.  All changes* are done in the 2.x line and brought forward into the 3.x line until Reactor 3.0 ages out.

![screen shot 2017-10-30 at 14 31 46](https://user-images.githubusercontent.com/60754/32196805-1bc27612-bd7f-11e7-8d6a-127b33ac209d.png)

*where those changes aren't [Reactor 3.1 specific](https://github.com/cloudfoundry/cf-java-client/issues/749#issuecomment-340574410).

**Comment by forbushbl** [comment]
@nebhale Awesome! We're going to move to the 3.x line shortly so It's great to know all this goodness will be there waiting for us
