### ISSUE TITLE
please provide sample example to create Application

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#828]
in version one ,explicitly we are providing buildpack and memory, uris, service names.
but now how to provide them.
please provide some reference guide for latest modifications.

createApplication(String appName, Staging staging, Integer memory, List<String> uris,
								  List<String> serviceNames)

**Comment by twoseat** [comment]
Hi @parasuramln - I believe `Push` and `PushManifest` are the features you're looking for. The push [request](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_PushApplicationRequest.java) lets you specify the same level of detail as the CF CLI, and the push manifest [request](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_PushApplicationManifestRequest.java) adds in manifest file handling if that suits your case better (see the [application manifest utils](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L71) if you have actual manifests you want to bring in).

**Comment by nebhale** [comment]
A good place to start for examples of all different kinds of things you might want to do is our [Integration Tests](https://github.com/cloudfoundry/cf-java-client/tree/master/integration-test/src/test/java/org/cloudfoundry).  For example, creating an application can be found [here](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java#L890-L901).

**Comment by parasuramln** [comment]
thank you so much Ben Hale.

it helped me alot.


​


‌
