### ISSUE TITLE
Feature Request: Blue Green Deployment

### ISSUE THREAD

**Issue by sworisbreathing** [cloudfoundry/cf-java-client#830]
There has been some recent discussion on jenkinsci/cloudfoundry-plugin#10 regarding blue-green deployment capabilities. I gave an opinion on that PR yesterday, that it would be much better if blue-green deployments were made part of the core Cloudfoundry libraries rather than third-party integration modules such as the Jenkins plugin.

So I'm raising this as a feature request, similar to #111, #129, #172, and #235, but as a core capability instead of via a plugin.

Currently the two main plugins linked from the official [Blue-Green deployment guide](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html) are [bluemixgaragelondon/cf-blue-green-deploy](https://github.com/bluemixgaragelondon/cf-blue-green-deploy) and [contraband/autopilot](https://github.com/contraband/autopilot).

### cf-blue-green-deploy
This is a plugin for CF CLI which (as I understand) implements pretty closely to the described blue-green deployment workflow, which optionally executes smoke tests prior to re-mapping the routes

### autopilot
This is a plugin for CF CLI which (as I understand) renames the old application, then pushes the manifest.

### My thoughts

Both approaches have their merits, and tbh I'm not terribly fussed which approach is adopted, so long as there is an extensive set of automated test cases to cover not only the happy flows (successful end-to-end blue-green deployment, including tearing down the old version) but also the unhappy flows (failure at any given stage of the process), and that the failure modes are well-documented and well understood.

For automation tooling to integrate with this feature, it will need to be well-documented how the core libraries handle failures during this process, and what sort of information can be passed back to the caller about both the nature of the failure as well as which step of the process failed. Idempotence would be greatly welcomed but it could be difficult to implement reliably.

**Comment by dweidele** [comment]
@sworisbreathing do you want to evaluate this with me to see if we can extend the plugin for this functionality?

**Comment by bijukunjummen** [comment]
Sorry for the self-promotion - I had created a gradle plugin using cf-java-client which does both blue-green style and auto-pilot style deploys. The plugin is available here - https://github.com/pivotalservices/ya-cf-app-gradle-plugin

**Comment by sworisbreathing** [comment]
@dweidele - I'd prefer to have the functionality available in the "core" cloudfoundry libraries. Once that's done, a plugin would simply need to expose the underlying functionality instead of trying to maintain its own logic.

@bijukunjummen thanks for that. I'll have a look. Hopefully that's something which could be easily incorporated into this repo.

**Comment by sworisbreathing** [comment]
@nebhale - considering there are two major versions of cf-java-client being developed in parallel, is there a particular branch you'd recommend we use as a starting point for this? In other words, is it better to start from either the `2.x` or `3.x` branch instead of `master` in order to be able to more easily merge the code back in via pull request?

**Comment by dweidele** [comment]
@nebhale ----^

**Comment by sworisbreathing** [comment]
I've pushed up the first working example in my fork: https://github.com/sworisbreathing/cf-java-client/tree/zero-downtime-deployments. This is still a *long* way from being ready to open pull request, but you can see the progress now.

I'm using Cucumber to define BDD tests. The plan is to have specific scenarios for happy paths as well as errors occurring at each stage of the deployment, for both autopilot and blue-green strategies. Right now I'm focusing on the integration tests using PCF Dev, but eventually I want to have copies of the same BDD scenarios being tested during the module build by mocking out the calls.

**Comment by twoseat** [comment]
Following up on some discussions elsewhere, this is a great idea for an extension to the Client, but it's not something that belongs _in_ the client. We map closely to the CF APIs for the `client` layer, and the CLI for the `operations` layer. To keep that mapping clean this should be a separate project that builds on the java client in the same way that the CLI has a plugin to do this. If anyone does take on that project we're here to answer questions, but in the meantime I'm closing this issue.
