### ISSUE TITLE
problem facing while pushing code

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#832]
hi i am using following code snippet to push my code to Cf.

```
try {   
  File artefactFile=new File("D:/PROVIDER COCKPIT/DEPLOYING JARS/SpringBootRestApp-0.0.1-SNAPSHOT.jar");
  File metaDataFile=new File("D:/PROVIDER COCKPIT/DEPLOYING JARS/sample.yml");
  YamlConfigDetails ymlBean = new YamlConfigDetails();
  Map<String, Object> yamlConfigDetails = ymlBean.getYamlConfigDetails(metaDataFile);
  @SuppressWarnings("unchecked")
  LinkedHashMap<String, Object> apps = (LinkedHashMap<String, Object>) yamlConfigDetails.get("applications");
  Integer memory = Integer.parseInt(apps.get("memory").toString());
  Integer instances = Integer.parseInt(apps.get("instances").toString());
  String buildpack = (String) apps.get("buildpack");
  String command = null;
  String domain = (String) apps.get("domain");
  String appName = 12345 + "_" + 12345+ "_" + 0.1;
  try {
    LOGGER.info("creating application starting:---");
    Mono<Void> push = defaultCloudFoundryOperations.applications()
        .push(PushApplicationRequest.builder().
        name(appName).
        path(artefactFile.toPath()).
        memory(memory).
        command(command).
        domain(domain).
        buildpack(buildpack).
        instances(instances).
        randomRoute(true).
        noRoute(false).
        noStart(false).
        build());
    LOGGER.info("creating application completed:---");
    push.doOnSuccess(x -> System.out.println("deployed succesfully !!")).subscribe();
    push.doOnError(x -> System.out.println("deployment failed !!")).subscribe();
    LOGGER.info("pushing application completed:---");
  } catch (Exception e) {
    LOGGER.error(e.getMessage());
  }
} catch (Exception e1) {
  LOGGER.error(e1.getMessage());
}
```

i am using this service in my controller. when i invoke that endpoint. it is **JUST** creating application in CF.
![deploy issue](https://user-images.githubusercontent.com/22343548/32488040-58f50240-c3d1-11e7-926d-737cba82c802.JPG)

but there is no route binded to application & application is always in stop condititon.

**Comment by nebhale** [comment]
Looking over your code there are a couple of areas for improvement that will push your application properly.

1.  There is no need for you to parse your manifest directly.  The project provides both [the tools](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.1.0.RELEASE/org/cloudfoundry/operations/applications/ApplicationManifestUtils.html#read-java.nio.file.Path-) and [the APIs](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.1.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#pushManifest-org.cloudfoundry.operations.applications.PushApplicationManifestRequest-) for using a reference to a manifest directly.

2.  `.subscribe()`-ing twice to a reactive flow causes the flow to be triggered twice.  Therefore, in your code, you're telling the application to push twice in close succession leading to one (but which one is undefined) to fail.

3.  The entire API is asynchronous and non-blocking.  Therefore, once you've subscribed to your flow, control is returned to the calling method which promptly completes, before even the first response (`push` is an orchestration of ~13 network requests) has returned.  Therefore, your application has completed before the flow has completed.  Some environments like Servlet containers have a long enough lifecycle that even if your calling method returns, the execution can still complete before the container closes.  If you are running your application in an environment where the method lifecycle is dictates the application lifecycle, you'll need to ensure that your method is kept alive until the flow is complete.

An example of improving all of these issues would be as follows:

```
CountDownLatch latch = new CountDownLatch(1);

this.cloudFoundryOperations.applications()
    .pushManifest(PushApplicationManifestRequest.builder()
        .manifests(ApplicationManifestUtils.read(Paths.get("D:/PROVIDER COCKPIT/DEPLOYING JARS/sample.yml")))
        .build())
    .doOnSubscribe(s -> this.logger.info("Deployment Started"))
    .doOnError(t -> this.logger.error("Deployment Failed", t))
    .doOnSuccess(v -> this.logger.info("Deployment Successful"))
    .subscribe(System.out::println, t -> latch.countDown(), latch::countDown);

latch.await();
```

**Comment by parasuramln** [comment]
**if i am getting jar file and yml file by an external service as shown below**
File artefactFile = fileClient.getArtefactFile(provideID, applicationID, version, artefactExtension, false,false);
LOGGER.info("fetching meta data file :---");
File metaDataFile = fileClient.getArtefactFile(provideID, applicationID, version, metaFileExtension, false,true);
**then what is the path i have to provide in yml file.**
![yml](https://user-images.githubusercontent.com/22343548/32535829-ba921e10-c481-11e7-9159-0f1475fada60.JPG)

**Comment by parasuramln** [comment]
**to resolve this issue i am parsing yml file as below**
```
Map<String, Object> yamlConfigDetails = ymlBean.getYamlConfigDetails(metaDataFile);
			@SuppressWarnings("unchecked")
			List<LinkedHashMap<String,Object>> apps = (List<LinkedHashMap<String,Object>>) yamlConfigDetails.get("applications");
			for (LinkedHashMap<String, Object> app : apps)
		{
			String mem = app.get("memory").toString();
			Integer memory=null;
			if(mem.contains("M")||mem.contains("MB")){
				String intMem = mem.replaceAll("[^0-9]", "");
				memory=(Integer.parseInt(intMem));
			}
			if(mem.contains("G")||mem.contains("GB")){
				String intMem = mem.replaceAll("[^0-9]", "");
				memory=(Integer.parseInt(intMem))*1024;
			}
			Integer instances = Integer.parseInt(app.get("instances").toString());
			String buildpack = (String) app.get("buildpack");
			String domain = (String) app.get("domain");
			String componentName=(String) app.get("name");
			String appName = provideID + "_" + applicationID + "_" + version+"_"+componentName;
			String host =(String) app.get("host");
			List<ServiceInstance> services=(List<ServiceInstance>) app.get("services");
			CountDownLatch latch=new CountDownLatch(1);
			this.defaultCloudFoundryOperations.applications()
			.pushManifest(PushApplicationManifestRequest.builder()
					.manifest(ApplicationManifest.builder()
							.name(appName)
							**.path(artefactFile.toPath())**    
							.host(host)
							.instances(instances)
							.domain(domain)
							.buildpack(buildpack)
							.memory(memory)
							.build())
					.noStart(false)
					.build())			
					.doOnSubscribe(s -> LOGGER.info("Deployment Started"))
					.doOnError(t -> LOGGER.error("Deployment Failed", t))
					.doOnSuccess(v -> LOGGER.info("Deployment Successful"))
					.subscribe(System.out::println, t -> latch.countDown(), latch::countDown);
			latch.await();
			}
```

if i use as above ,again same issue i am facing.
for testing purspose i replaced
**.path(artefactFile.toPath())**  -----with------**.path(Paths.get("test-apps/SpringBootRestApp-0.0.1-SNAPSHOT.jar"))** 
then its working fine...

**i would like to use downloaded `jar file` instead of testfile to push**

**Comment by nebhale** [comment]
You still shouldn't be manually parsing the manifest for anything, you should be reusing the manifest that we parsed and only overriding the bits you need to.  All of our builder APIs provide a `from()` method to do just this:

```java
CountDownLatch latch = new CountDownLatch(1);

this.cloudFoundryOperations.applications()
    .pushManifest(PushApplicationManifestRequest.builder()
        .manifest(ApplicationManifest.builder()
            .from(ApplicationManifestUtils.read(Paths.get("D:/PROVIDER COCKPIT/DEPLOYING JARS/sample.yml")).get(0))
            .path(Paths.get("D:/PROVIDER COCKPIT/DEPLOYING JARS/SpringBootRestApp-0.0.1-SNAPSHOT.jar"))
            .build())
        .build())
    .doOnSubscribe(s -> this.logger.info("Deployment Started"))
    .doOnError(t -> this.logger.error("Deployment Failed", t))
    .doOnSuccess(v -> this.logger.info("Deployment Successful"))
    .subscribe(System.out::println, t -> latch.countDown(), latch::countDown);

latch.await();
```

**Comment by parasuramln** [comment]
thank you nebhale.
is it possible to use` zip file `**(which contains manifest file and supporting jar files)** for deployment purpose.

for example, in my project classpath itself if  i have **libs/supportingfiles.zip**  then how to use it.
is it neccessary to unzip & using it.???

**Comment by nebhale** [comment]
Yes you must unzip that.  Cloud Foundry's APIs facilitate pushing an application.  A ZIP file with manifest and application artifacts _is not_ an application.  So you need to unzip the contents of that file, and use the API to push the application artifact and the use the manifest for metadata about the application artifact being pushed.

**Comment by parasuramln** [comment]
@nebhale 
how to replace  System.out::println with logger.
in
 **.subscribe(System.out::println, t -> latch.countDown(), latch::countDown);**
