### ISSUE TITLE
questions regarding CF 

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#837]
**1**. is it possible to Rename Application After deployment .
**2**is it possible to deploy individual Apps if Multiple apps are defined in Manifest by using ApplicationManifest Utils.

**Comment by twoseat** [comment]
1) [Yup](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/_UpdateApplicationRequest.java#L153)

2) I'm not entirely clear on what you're trying to do. So if the manifest contains apps A, B and C, you'd like to be able to deploy only B? You may be able to work something out using [read](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/_UpdateApplicationRequest.java#L153), which returns a `List` of `ApplicationManifest`s, and then filter the list according to your criteria.

**Comment by Zteve** [comment]
@twoseat  Do you mean [read](https://github.com/cloudfoundry/cf-java-client/blob/fca1ef0d75ba9671b91c41fe7aa57304cfc359d1/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L71)?

**Comment by twoseat** [comment]
I did indeed @Zteve, correcting link now, thanks...
