### ISSUE TITLE
Unable to update request using associateAuditorByUsername & associateAuditor reactive api

### ISSUE THREAD

**Issue by sundarsrini** [cloudfoundry/cf-java-client#838]
Hi, 

I am trying to associate a user as an auditor to my space using the below reactor api code. 

#### `associateAuditorByUsername`
```
cloudFoundryClient.spaces()
    .associateAuditorByUsername(AssociateSpaceAuditorByUsernameRequest.builder()
        .spaceId(spacename)
        .username(userData.getUserId())
        .build());
```
		
#### `associateAuditor`
```
cloudFoundryClient.spaces()
    .associateAuditor(AssociateSpaceAuditorRequest.builder()
        .spaceId(userData.getSpaceGuid())
        .auditorId(userData.getUserId())
        .build());
```

I have tried with both space guid and space name. But the api is not updating my system with the association. 
Can you please help! 

Note: cf-java-client version 3.2.0.

**Comment by sundarsrini** [comment]
It looks like cf cli is updating the org with the user info before associating with the space which is not happening via reactive api / rest api. 

It seems expected behaviour. Please confirm.

**Comment by twoseat** [comment]
Hi @sundarsrini. The code you're using is at the client layer, which is where we replicate the [Cloud Foundry API](https://apidocs.cloudfoundry.org/280/). When working at that level it's up to you to put together all the calls needed to achieve your aim.

We have a separate operations layer that replicates the functionality of the CLI, and where we take care of making all the required calls for you. Unfortunately we haven't added user admin yet, but I'll make it a priority (though I can't guarantee when it will be ready).

In the meantime you can use the CLI as a model for the calls you need to make, and also take a look at the [test](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/client/v2/SpacesTest.java#L174-L179) we have for this functionality at the client level.

**Comment by twoseat** [comment]
Will be available in the next release, coming soon...
