### ISSUE TITLE
Is there any way to get the check sum details of an application binary.

### ISSUE THREAD

**Issue by georgian3590** [cloudfoundry/cf-java-client#843]

**Comment by nebhale** [comment]
I’m not sure what exactly you’re asking here.  What do you mean by an application binary (possibly you mean something that we use another name for) and what kind of checksum are you looking for?  A good start would be to look at the [REST API documentation](https://apidocs.cloudfoundry.org/280/) and determine if the Cloud Controller returns the information you’re looking for.

**Comment by georgian3590** [comment]
With application binary means, the deployed application in cloud foundry. 
I was searching any API or any method in the java client jar, to get the checksum of the deployed application.

" https://en.wikipedia.org/wiki/Checksum"

**Comment by twoseat** [comment]
@georgian3590 If you take a look at the documentation @nebhale provided you'll find that the Cloud Controller doesn't return an 'application binary checksum', hence we can't. In the later v3 API they do provide a [buildpack droplet checksum](http://v3-apidocs.cloudfoundry.org/version/3.35.0/index.html#get-a-droplet) and a [package checksum](http://v3-apidocs.cloudfoundry.org/version/3.35.0/index.html#get-a-package), either of which may be what you're looking for. We have a corresponding method for both [droplets](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/droplets/Droplets.java#L41-L47) and [packages](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/packages/Packages.java#L59-L65)

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
