### ISSUE TITLE
ReactiveException and  TimeoutException when using CF client

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#847]
Hi,

We are using cf java client with the following versions:

cf-client-version: 2.23.0.RELEASE
reactor-core-version: 3.0.7.RELEASE
reactor-netty-version: 0.6.6.RELEASE

We are using the cf client in order to retrieve the organization name by its GUID:
![image](https://user-images.githubusercontent.com/6083902/34933191-988933f2-f9de-11e7-9fc6-ee9260c425b3.png)

And from time to time we get the following exception:
```
reactor.core.Exceptions$ReactiveException: java.io.IOException: Connection closed prematurely
  at reactor.core.Exceptions.propagate(Exceptions.java:219)
  at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:85)
  at reactor.core.publisher.Mono.block(Mono.java:1301)
  at ***.hcp.cf.onboarding.cfclient.CFClient.getOrgNameByGuid(CFClient.java:309)
```

Also, we get this other exception:

```
java.util.concurrent.TimeoutException: Acquire operation took longer then configured maximum time, at io.netty.channel.pool.FixedChannelPool.<init>(...)(Unknown Source), Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:, Assembly trace from producer [reactor.core.publisher.MonoPeek] :, reactor.core.publisher.Mono.checkpoint(Mono.java:1400), org.cloudfoundry.reactor.client.v2.applications.ReactorApplicationsV2.list(ReactorApplicationsV2.java:156), ***.hcp.cf.onboarding.cfclient.CFClient.stopAppsForOrg(CFClient.java:591)
```

When trying to get the list of applications for a service.

This is not always failing but we notice a lot of failures when the load on our application is bigger and there are a lot of requests processed.

Thanks a lot,
Andrea.

**Comment by nebhale** [comment]
The error seems to indicate that all of the connections in the connection pool are occupied (e.g. waiting for a response) that further incoming requests are timing out just trying to get a hold of a connection to begin their work.  The default number of connections is variable (`max(number of processors, 8) * 2`, so probably 8 or 16 for you) but you can [enlarge that pool](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client-reactor/2.23.0.RELEASE/org/cloudfoundry/reactor/DefaultConnectionContext.Builder.html#connectionPoolSize-java.lang.Integer-) as you see fit.

**Comment by asherbar** [comment]
What's the rationale for configuring the default number of connections as a function of the number of processors? I would think the number of connections could be much larger.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.

**Comment by robachmann** [comment]
Sorry for grave-digging, but could we possibly have a flag to use an `elastic PoolResources` as outlined here?
https://github.com/spring-projects/spring-framework/issues/21167#issuecomment-453469254

I would gladly raise a new request if desired.
