### ISSUE TITLE
Add origin field to set/unset role requests

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-java-client#848]
It looks like capi-release v1.45.0 (API v2.99.0) introduced an "experimental" origin field to several APIs including [PUT v2/organizations/:guid/users](https://apidocs.cloudfoundry.org/280/organizations/associate_user_with_the_organization_by_username.html). Despite being "experimental", these changes make it absolutely necessary for someone to include the origin field in all requests which operate on users which are in multiple origins (e.g. local UAA and LDAP), otherwise the API request will fail because CAPI can't disambiguate the user.

Please see [tracker #3704323](https://www.pivotaltracker.com/epic/show/3704323).
Also, see the [Slack conversation](https://cloudfoundry.slack.com/archives/C08SKSMG8/p1512499327000621)

**Comment by nebhale** [comment]
@twoseat I believe it's the following APIs:

* http://apidocs.cloudfoundry.org/280/organizations/associate_auditor_with_the_organization_by_username.html
* http://apidocs.cloudfoundry.org/280/organizations/associate_billing_manager_with_the_organization_by_username.html
* http://apidocs.cloudfoundry.org/280/organizations/associate_manager_with_the_organization_by_username.html
* http://apidocs.cloudfoundry.org/280/organizations/associate_user_with_the_organization_by_username.html
* http://apidocs.cloudfoundry.org/280/organizations/remove_auditor_from_the_organization_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/organizations/remove_billing_manager_from_the_organization_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/organizations/remove_manager_from_the_organization_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/organizations/remove_user_from_the_organization_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/spaces/associate_auditor_with_the_space_by_username.html
* http://apidocs.cloudfoundry.org/280/spaces/associate_developer_with_the_space_by_username.html
* http://apidocs.cloudfoundry.org/280/spaces/associate_manager_with_the_space_by_username.html
* http://apidocs.cloudfoundry.org/280/spaces/remove_auditor_from_the_space_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/spaces/remove_developer_from_the_space_by_username_experimental.html
* http://apidocs.cloudfoundry.org/280/spaces/remove_manager_from_the_space_by_username_experimental.html

**Comment by nebhale** [comment]
Confirmation from @zrob:

```
PUT /v2/organizations/:guid/auditors
PUT /v2/organizations/:guid/billing_managers
PUT /v2/organizations/:guid/managers
PUT /v2/organizations/:guid/users
PUT /v2/spaces/:guid/auditors
PUT /v2/spaces/:guid/managers
PUT /v2/spaces/:guid/developers

POST /v2/spaces/:guid/auditors/remove
POST /v2/spaces/:guid/managers/remove
POST /v2/spaces/:guid/developers/remove
POST /v2/organizations/:guid/auditors/remove
POST /v2/organizations/:guid/billing_managers/remove
POST /v2/organizations/:guid/managers/remove
POST /v2/organizations/:guid/users/remove
```
