### ISSUE TITLE
Summary batch retrieval 

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#854]
Hi,

Thorugh CF CLI there is a capability to query using IN.
Are the cf java client APIs supporting this? Can I, for example, query on several summary objects of organization ids?
If so, how is this achieved?

Or it the CLI call eventually interpreted as two API calls? :/

Thanks,
Andrea.

**Comment by twoseat** [comment]
Hi Andrea - can you give me an example of a CLI command that does what you expect? Something like `cf org <example params>`, and the output it produces.

**Comment by nebhale** [comment]
I’m not precisely sure which API you’re looking at, but if you look at the builder for [`ListOrganizationsRequest`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-client/3.5.0.RELEASE/org/cloudfoundry/client/v2/organizations/ListOrganizationsRequest.Builder.html), you’ll notice that nearly all of the things you could configure and query against are configurable as collections (vargs, `addAll()`, `Iterable`, etc.).  These are all in support of `IN` queries.  You configure multiple `IN` values but calling multiple times, using vargs, calling `addAll`, etc. with all of the values you’d like to be in the collection and the result builds the query you want.  If you have any questions as to what query is being made, you can set the `cloudfoundry-client.request` logger to `DEBUG` to see the entire URI (including query) of the request being made.

**Comment by nebhale** [comment]
Since there’s been no response on this issue in a couple of weeks, I’m going to close it.  If you’d like to see it re-opened, please comment on the issue and I’ll reopen it.
