### ISSUE TITLE
"Parallel" threads not getting cleaned up after use of the client

### ISSUE THREAD

**Issue by chlam4** [cloudfoundry/cf-java-client#856]
Here is a simple program that instantiates a v2 client and uses it to get the info from Cloud Foundry.  It has some code that tracks the number of threads with the `parallel` prefix.

The results are at the bottom. The thread count doesn't go back to 0 after use.  I'm using 3.3.0.RELEASE.

The "parallel" threads seem being created during the get info call, but they stay after the call finishes.  Is there a way to dispose these `parallel` threads after use?

Program (please note that the api endpoint, username and password are fake):
```
    public static void main(String[] args) throws InterruptedException {
        trackThreads("parallel");
    }

    private static void trackThreads(final String threadPrefix) throws InterruptedException {
        System.out.println(threadPrefix + " THREAD COUNT");
        System.out.println("  (start) " + getThreadCount(threadPrefix));

        final DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
                .apiHost("api.x.y.z").skipSslValidation(true).build();

        final TokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
                .password("secret").username("admin").build();

        final CloudFoundryClient client = ReactorCloudFoundryClient.builder()
                .connectionContext(connectionContext).tokenProvider(tokenProvider).build();
        System.out.println("  (after client instantiation) " + getThreadCount(threadPrefix));

        client.info().get(GetInfoRequest.builder().build()).block();
        System.out.println("  (after get info) " + getThreadCount(threadPrefix));

        connectionContext.dispose();
        System.out.println("  (after dispose) " + getThreadCount(threadPrefix));

        Thread.sleep(TimeUnit.SECONDS.toMillis(10));
        System.out.println("  (after 10 seconds) " + getThreadCount(threadPrefix));
    }

    private static long getThreadCount(final String threadPrefix) {
        return Thread.getAllStackTraces().keySet().stream()
                .filter(thread -> thread.getName().startsWith(threadPrefix)).count();
    }
```

Result:
```
parallel THREAD COUNT
  (start) 0
  (after client instantiation) 0
  (after get info) 2
  (after dispose) 2
  (after 10 seconds) 2

```

**Comment by nebhale** [comment]
We struggled with this previously (Reactor created a set of threads we couldn't prevent from being created), but this seems to imply that there's another set somewhere that we need to track down.

/cc @smaldini

**Comment by smaldini** [comment]
parallel comes from Schedulers.parallel() or any timed operator. If you want a clear shutdown you can use Schedulers.shutdownNow() to reset all reactor schedulers. Otherwise you might want to use your own scheduler to control the lifecycle manually and exclusively.

**Comment by chlam4** [comment]
Thanks @nebhale and @smaldini.  `Schedulers.shutdownNow()` works for me.

**Comment by nebhale** [comment]
@chlam4 I was thinking about adding that call to the `dispose()` method but I’ve decided that it’s not correct to do so.  Since it has the ability to close `Scheduler`s used by user code (not just our client), the call would be destructive outside of our boundary.  Because of this, I’m going to leave the currently behavior as-is.

**Comment by chlam4** [comment]
@nebhale I agree too, though thanks for considering that!
