### ISSUE TITLE
CreateQuotaRequest applicationInstanceLimit

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#858]
Hi,

Is there a reason that creating a quota with applicationInstanceLimit through CreateQuotaRequest.builder() is not exposed?

Thanks a lot,
Andrea.

**Comment by twoseat** [comment]
Hi @andreaAlkalay - it's one of a number of new fields that have been added to that request since we implemented it. Thanks for highlighting it, I should get to it soon.
