### ISSUE TITLE
Need an API or any way to constantly monitor CF Application

### ISSUE THREAD

**Issue by divya-bhat** [cloudfoundry/cf-java-client#859]
Hi,

Is there any client API or any other solution to subscribe to application health event?
Need constant monitoring of CF App in order to perform _some actions._
For eg. _some action_ has to be performed whenever an **application gets crashed** or **memory cpu usage exceeds 70%**.

Thanks!

**Comment by nebhale** [comment]
The [operations level](https://javadoc.io/doc/org.cloudfoundry/cloudfoundry-operations/3.5.0.RELEASE) of the API is an analog to the CLI and the [client level](https://javadoc.io/doc/org.cloudfoundry/cloudfoundry-client/3.5.0.RELEASE) is a direct mapping to the CAPI API.  You should be able to translate the actions you currently take to get this information back to our API and both provided the same inputs and get the same outputs.

As a quick example, `cf events` might be what you’re looking for, and you can find the equivalent in our [`Applications.getEvents()` API](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.5.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#getEvents-org.cloudfoundry.operations.applications.GetApplicationEventsRequest-).

**Comment by nebhale** [comment]
Since there’s been no response on this issue in a couple of weeks, I’m going to close it.  If you’d like to see it re-opened, please comment on the issue and I’ll reopen it.
