### ISSUE TITLE
Service brokers with a schema

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#864]
Hi,

We have several service brokers which are registered with a catalog containing a schema object according to the open broker API spec.
Even though these service brokers are successfully registered, when using the get service plans API we get the following error:

`Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: [B@1b0f58c2; line: 31, column: 31] (through reference chain: org.cloudfoundry.client.v2.serviceplans.Json["resources"]>java.util.ArrayList[0]>org.cloudfoundry.client.v2.serviceplans.Json["entity"]>org.cloudfoundry.client.v2.serviceplans.Json["schemas"]>org.cloudfoundry.client.v2.serviceplans.Json["service_instance"]>org.cloudfoundry.client.v2.serviceplans.Json["create"]>org.cloudfoundry.client.v2.serviceplans.Json["parameters"]->java.util.LinkedHashMap["properties"])`

Any ideas? Is schema fully supported according to the open broker API spec?

Thanks,
Andrea.

**Comment by twoseat** [comment]
Hi Andrea - we aim to support everything the cloud controller returns, and clearly as this is being returned we should support it! I'm working on this now.

**Comment by andreaAlkalay** [comment]
Thank you very much, this is very urgent for our use case.
When is the planned release of 2.27.0.RELEASE?

**Comment by twoseat** [comment]
A snapshot build should be available shortly containing the changes you need. Because I'm effectively working from two specs it's possible I'm missing some other fields, so please try out the snapshot to make sure it works for you. Once you're happy I'll look at getting a release out for you.

**Comment by andreaAlkalay** [comment]
Great! Just let me know when and which snapshot I should download and I'll test it.

Thanks a lot,
Andrea.

**Comment by twoseat** [comment]
Unfortunately I made a mistake on the fix (requiring some fields that should be optional) that has caused CI failures. A revised (working!) version should await you when you start work tomorrow.

**Comment by twoseat** [comment]
So I'm not terribly good at guessing people's time zones, and hence this is probably not your morning! Nonetheless, the latest 3.7 snapshot is ready for your testing (cloudfoundry-java-client-3.7.0.BUILD-20180314.153438-2). Let me know how it goes.

**Comment by andreaAlkalay** [comment]
Hi,

Thank you! Schema works perfectly.

When should the next version be released?

Thanks,
Andrea.

**Comment by nebhale** [comment]
I'll chime in to let @twoseat know that he's doing the release tomorrow 😉.

**Comment by twoseat** [comment]
Agreed - it should be ready for _somebody's_ tomorrow morning!

**Comment by andreaAlkalay** [comment]
Haha :) That's super! Thanks a lot!

**Comment by twoseat** [comment]
Fixed in latest releases (2.27.0.RELEASE and 3.8.0.RELEASE)

**Comment by twoseat** [comment]
@andreaAlkalay After delays that weren't entirely down to us, `3.8.0.RELEASE` is now available in the usual places for your enjoyment!
