### ISSUE TITLE
Firehose doesn't appear to correctly decode HttpStartStop ApplicationId

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#867]
Every app guid I get from from firehose HttpStartStop events doesn't appear to equate to a real app guid in my system.  Perhaps the applicationId is not getting decoded correctly?

Sorry for being lazy, I don't yet have a test case.  I'll create one soon if it is not simple for you to confirm.

**Comment by nebhale** [comment]
The code is pretty straight forward.

1.  [Get Dropsonde UUID](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/doppler/_HttpStartStop.java#L36)
2.  [Convert UUID](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/doppler/UuidUtils.java#L29)

Not saying there isn't a bug there, just that there's isn't a whole lot of room for a bug 😄 Most likely is that the most/least significant are reversed, but I've got no reason to believe that they are.

**Comment by youngm** [comment]
ok I'll try to put together a test case tomorrow.  It never is that easy. 😀

**Comment by youngm** [comment]
@nebhale  Here is my non-idiomatic testcase. :)  Hopefully you see the issue in your environment too.

```
		File pushFile = File.createTempFile("cfnozzle", "app");
		Path pushPath = pushFile.toPath();
		try {
			final BlockingQueue<UUID> loggedAppGuid = new ArrayBlockingQueue<>(1);
			final BlockingQueue<UUID> actualAppGuid = new ArrayBlockingQueue<>(1);

			System.out.println("Starting firehose");
			doppler.firehose(FirehoseRequest.builder().subscriptionId("test").build()).doOnNext(envelope -> {
				if(envelope.getEventType().equals(EventType.HTTP_START_STOP)) {
					if(envelope.getHttpStartStop().getUri().contains("randomPath.html")
							&& envelope.getHttpStartStop().getApplicationId() != null) {
						loggedAppGuid.offer(envelope.getHttpStartStop().getApplicationId());
					}
				}
			}).subscribe();

			pushFile.delete();
			pushFile.mkdir();
			Files.createFile(pushPath.resolve("Staticfile"));
			Files.createFile(pushPath.resolve("randomPath.html"));

			System.out.println("Pushing Application...");

			cfOperations.applications().push(PushApplicationRequest.builder().name("testnozzleapp").path(pushPath).build())
				.thenMany(cfOperations.applications().list())
				.flatMap(summary -> {
					if(summary.getName().equals("testnozzleapp")) {
						actualAppGuid.offer(UUID.fromString(summary.getId()));
						return Mono.just(summary.getUrls().get(0));
					}
					return Mono.empty();
				})
				.flatMap(uri -> HttpClient.create().get("https://"+uri+"/randomPath.html"))
				.subscribe(response -> System.out.println("Request Status: "+response.status()));


			System.out.println("Waiting to get actual app guid...");
			UUID actualUuid = actualAppGuid.poll(5, TimeUnit.MINUTES);
			System.out.println("Waiting to get guid from firehose...");
			UUID loggedUuid = loggedAppGuid.poll(5, TimeUnit.MINUTES);
			if(loggedUuid.equals(actualUuid)) {
				System.out.println("Yay! They're the same!");
			} else {
				System.out.println("They're different :(");
				System.out.println(loggedUuid);
				System.out.println(actualUuid);
			}
			

		} finally {
			Files.deleteIfExists(pushPath.resolve("Staticfile"));
			Files.deleteIfExists(pushPath.resolve("randomPath.html"));
			Files.deleteIfExists(pushPath);
		}
```

**Comment by youngm** [comment]
@nebhale Small update.  This example code snippet appears to corrects the UUID provided by the firehose:

```
new java.util.UUID(Long.reverseBytes(firehoseUUID.getLeastSignificantBits()), Long.reverseBytes(firehoseUUID.getMostSignificantBits()))
```

**Comment by twoseat** [comment]
@youngm Thanks for your persistence on this - I see the problem* too, and agree with your solution. I'm working on some more idiomatic :) tests, and will then include this in the next release.

*(Ultimately caused by a Lilliputian dispute between Java and Go about which end of an egg to break open)
