### ISSUE TITLE
Need all the exceptions which ClientV2Exception can throw

### ISSUE THREAD

**Issue by divya-bhat** [cloudfoundry/cf-java-client#868]
Hi,

We need to handle all error details thrown by  org.cloudfoundry.client.v2.ClientV2Exception as part of our project.
It will be really helpful if we get list of all exception messages with error codes thrown by ClientV2Exception?

Thanks!

**Comment by twoseat** [comment]
`ClientV2Exception` doesn't 'create' exceptions, it just lets us handle the exceptions thrown by the cloud controller. [This list](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/vendor/errors/v2.yml) is the best source I know of for what those might be, though I can't vouch for its completeness.

**Comment by twoseat** [comment]
Since there’s been no response on this issue in a couple of weeks, I’m going to close it. If you’d like to see it re-opened, please comment on the issue and I’ll reopen it.
