### ISSUE TITLE
push reports 'The app package is invalid'

### ISSUE THREAD

**Issue by i7c** [cloudfoundry/cf-java-client#877]
The API documentation is kinda challenging and I cannot find the root cause for my issue, hoping you can help me out.

First I used these versions:
```
    compile('org.cloudfoundry:cloudfoundry-client-reactor:3.5.0.RELEASE')
    compile('org.cloudfoundry:cloudfoundry-operations:3.5.0.RELEASE')
    compile('io.projectreactor:reactor-core:3.1.5.RELEASE')
    compile('io.projectreactor.ipc:reactor-netty:0.7.5.RELEASE')
```

leading to
```
Exception in thread "main" org.cloudfoundry.client.v2.ClientV2Exception: CF-AppPackageInvalid(150001): The app package is invalid: bits have not been uploaded
        at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$0(ErrorPayloadMapper.java:46)
        at org.cloudfoundry.reactor.util.ErrorPayloadMapper.lambda$null$9(ErrorPayloadMapper.java:98)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115)
        at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:345)
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:104)
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:469)

[...]
```

Then I updated to

```
    compile('org.cloudfoundry:cloudfoundry-client-reactor:3.9.0.RELEASE')
    compile('org.cloudfoundry:cloudfoundry-operations:3.9.0.RELEASE')
    compile('io.projectreactor:reactor-core:3.1.6.RELEASE')
    compile('io.projectreactor.ipc:reactor-netty:0.7.6.RELEASE')

```

which changes the error to
```
Exception in thread "main" org.cloudfoundry.client.v2.ClientV2Exception: CF-AppPackageInvalid(150001): The app package is invalid: Unzipping had errors
 STDOUT: ""
 STDERR: "warning [/var/vcap/data/cloud_controller_ng/tmp/local_bits_packer20180311-29372-lgonqg/copied_app_package.zip]:  8013 extra bytes at beginning or within zipfile
  (attempting to process anyway)
"
        at org.cloudfoundry.util.JobUtils.getError(JobUtils.java:103)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:97)
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)

[...]
```

The relevant bit of code:
```
operations
        .applications()
        .pushManifest(
            PushApplicationManifestRequest.builder()
                .manifest(
                    ApplicationManifest.builder()
                        .from(manifestWithoutPath)
                        .path(artifactFile.toPath())
                        .build())
                .build())
        .blockOptional(Duration.ofMinutes(10));
```

I was suspecting some v2/v3 API issues here, but I really have no idea. I tried this with PCF Dev version 0.29.0 (CLI: 49405ec, OVA: 0.548.0) and another private CF. Do I have to configure v3 somewhere to make this work?

any help appreciated.

**Comment by twoseat** [comment]
It's not clear from your description - have you tried this using the CLI? If `cf push` fails with the same error then I'd assume the error is correct and there's something wrong with your zip file (at least as far as CF is concerned). Let me know the result of that.

**Comment by i7c** [comment]
I only have issues with the client lib, CLI works!

Here is how I build the operations object:

```
    DefaultConnectionContext connectionContext =
        DefaultConnectionContext.builder()
            .apiHost("api.local.pcfdev.io")
            .skipSslValidation(true)
            .build();

    PasswordGrantTokenProvider tokenProvider =
        PasswordGrantTokenProvider.builder()
            .password("admin")
            .username("admin")
            .build();

    ReactorCloudFoundryClient cloudFoundryClient =
        ReactorCloudFoundryClient.builder()
            .connectionContext(connectionContext)
            .tokenProvider(tokenProvider)
            .build();

    ReactorDopplerClient dopplerClient =
        ReactorDopplerClient.builder()
            .connectionContext(connectionContext)
            .tokenProvider(tokenProvider)
            .build();

    ReactorUaaClient uaaClient =
        ReactorUaaClient.builder()
            .connectionContext(connectionContext)
            .tokenProvider(tokenProvider)
            .build();

    operations =
        DefaultCloudFoundryOperations.builder()
            .cloudFoundryClient(cloudFoundryClient)
            .dopplerClient(dopplerClient)
            .uaaClient(uaaClient)
            .organization("pcfdev-org")
            .space("pcfdev-space")
            .build();

```

**Comment by twoseat** [comment]
I don't see anything obviously wrong with your setup. Can you try a basic 'hello world' app to make sure something works ([this test app](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/resources/test-application.zip) should work for example)

**Comment by i7c** [comment]
Ah, thank you for that hint, that comparison was important! Your help is already greatly appreciated! Pushing the example app worked.

The issue seems to be that I’m trying to push a Spring Boot Jar, that has this executable script part at the beginning of the file. The error reported by cf is the same as the *warning* the the zip util writes to stderr when extracting the jar:

```
unzip myapp-1.1.0-SNAPSHOT.jar
Archive:  myapp-1.1.0-SNAPSHOT.jar
**warning [myapp-1.1.0-SNAPSHOT.jar]:  8013 extra bytes at beginning or within zipfile**
  (attempting to process anyway)
```

If I extract the zip file myself and specify the directory as .path() (instead of the spring boot jar) it works!

I leave it up for you to decide if this is a shortcoming of the cf-java-client lib or not.

Thanks! :+1:

**Comment by twoseat** [comment]
Interesting! Glad to hear it's working for you. I'll leave the issue open while I investigate this more to decide if we should handle this.

**Comment by nebhale** [comment]
This is the use of a non-standard extension to the ZIP format.  The error is generated by CF (not the client), so you’ll want to open an issue against the [cloud controller](https://github.com/cloudfoundry/cloud_controller_ng/) in order to get them to support this ZIP format.

**Comment by i7c** [comment]
@nebhale I suppose Cloudfoundry CLI handles it somehow as well, probably unzips it client-sided before zipping again?

**Comment by nebhale** [comment]
They use the Go ZIP library which unzips it without a problem (or suppresses the warning) and then _does not add the script back_ when recompressing. I’d argue that this is actually a bug but only a very minor one. I suspect if you tried to push to a fresh CF instance (one where there were no matched resources and the client short circuits to sending the original JAR) you’d experience the same thing. But the bug/deficiency is actually on the Cloud Controller (it should be resilient to this kind of ZIP) and there’s no requirement for clients to sanitize archives before upload.

**Comment by twoseat** [comment]
Following the logic of the last comment I'm going to close this issue as not a problem with the client.
