### ISSUE TITLE
ApplicationUsageEventEntity.getMemoryInMbPerInstances() naming

### ISSUE THREAD

**Issue by JohannesRudolph** [cloudfoundry/cf-java-client#878]
`ApplicationUsageEventEntity.getMemoryInMbPerInstances()` is declared as follows: 

```java
  /**
   * The memory in mb by instances
   */
  @JsonProperty("memory_in_mb_per_instance")
  @Override
  public @Nullable Integer getMemoryInMbPerInstances() {
    return memoryInMbPerInstances;
  }

```

It would make more sense if the field would drop the plural "s" from the end and expose the field under the expected name.

**Comment by twoseat** [comment]
Thanks @JohannesRudolph - you're absolutely right, I'm just hesitating because it's a (admittedly trivial) breaking change to rename it, and we're very careful about introducing those. I'll make a decision for the next release!
