### ISSUE TITLE
App bits download results in different size 

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/cf-java-client#879]
Hi Team ,

The CF 'api /v2/apps/guid/download' downloads app bits of app . However , when I download app bits for same app twice and calculate checksum of file, it results in different checksum . What are the contents of appbits exactly ? Does it include app specific information ( may be like route or some metadata) ?

**Comment by twoseat** [comment]
Hi @gowriln - The app bits you download should be exactly the same as the app bits you uploaded, with no route or other config included. I've just verified that downloading the same app twice gives exactly the same thing, so I'm not sure what's going on for you. Are you accidentally using the `downloadDroplet` endpoint instead, which I imagine might give you different things at different times?
