### ISSUE TITLE
Discussion what should Doppler client do when traffic controller is shutdown?

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-java-client#884]
Today if drinking from the firehose when the traffic controller is shutdown (server closed) the subscription is silently closed.  Is that expected behaviour?

Some other possible options:
* Report an error?
* Attempt to auto reconnect?
* Is there some kind of reactive api thing I can do to reconnect?

Here is some sample code.  To duplicate current behaviour of silently ending, run the code and `monit stop` the traffic controller.

```
ReactorDopplerClient doppler = ReactorDopplerClient.builder()
		.tokenProvider(tokenProvider)
		.connectionContext(context)
		.build();

    doppler.firehose(FirehoseRequest.builder()
        .subscriptionId("subscription")
        .build())
        .doOnSubscribe(s -> System.out.printf("Connecting to the firehose"))
        .doOnNext(e -> System.out.print("."))
        .blockLast();
```

**Comment by nebhale** [comment]
I believe that our behavior, quietly treating the termination of a websocket as `onComplete()` (as opposed to `onError()`) is correct but I am open to being persuaded.

The idiomatic way to resubscribe after `onComplete()` would be to nest `.repeat(...)` in the flow (you can decide which variant makes sense to use).  You'd place it above `.doOnSubscribe()` if you want it to happen quietly (without your log statement) or above `.blockLast()` if you want logging.

**Comment by youngm** [comment]
@nebhale I think you're right.  Current functionality makes sense and thanks for pointing out `.repeat(...)` I'll give that a try.
