### ISSUE TITLE
Want to access CF service from outside of CF from K8s

### ISSUE THREAD

**Issue by itnilesh** [cloudfoundry/cf-java-client#888]
Scenario - 
We have rabbitMQ deployed in CF but our compute  happens in  kubernettes .
If I have workers in k8s and want to access this queue how to make access from k8s to CF rabbitMQ?

Is ssh tunnel is only option ? is it only and efficent option ?

**Comment by twoseat** [comment]
I'm afraid that's not something the java client has anything to do with, and I'm not sure where to direct you. I'll leave this open for now in case anyone else has suggestions...

**Comment by nebhale** [comment]
The Java Client is a project for orchestrating Cloud Foundry, and doesn’t have any direct relationship with the services and application that run upon on.  I’d recommend asking this question of the [`cf-dev` mailing list](https://lists.cloudfoundry.org/g/cf-dev).

**Comment by itnilesh** [comment]
Nobody is relying on that mailing list thanks pivotal !
