### ISSUE TITLE
Incorrect & Invalid metadata Id format with v2.spaces.ListSpaceServicesRequest in ListSpaceServicesResponse

### ISSUE THREAD

**Issue by pandeyar** [cloudfoundry/cf-java-client#892]
Hi,
I am querying a service within a space using v2.spaces.ListSpaceServicesRequest , but for some reason the metadata id I am getting is incorrect . The format of id I am receiving is not guid it has comma and underscores in it.
ID string comes as   "ser_someguid,org_someguid"

Code snippet what i am using to retrieve  the service id is below 
```
ListSpaceServicesResponse serviceResponse = cloudFoundryClient.spaces()
               .listServices(ListSpaceServicesRequest.builder()
               .label("<someService>").spaceId("<spaceId>").build()).block();
String serviceId = serviceResponse.getResources().stream()
               .filter(s -> "someService".equalsIgnoreCase(s.getEntity().getLabel()))
              .findFirst().getMetadata().getId();
```
Using Java Client 3.9.0.RELEASE

Whereas when used with cf cli - cf curl v2/services returns correct response and has proper guid format. 

Any suggestions,  what's going wrong here?

**Comment by twoseat** [comment]
Try the following:

```
String serviceId = PaginationUtils.requestClientV2Resources(page -> this.cloudFoundryClient.spaces()
    .listServices(ListSpaceServicesRequest.builder()
        .label("<someService>")
        .page(page)
        .spaceId("<spaceId>")
        .build()))
    .filter(resource -> "someservice".equalsIgnoreCase(ResourceUtils.getEntity(resource).getLabel()))
    .next()
    .map(ResourceUtils::getId)
    .block();
```

**Comment by pandeyar** [comment]
Thanks for the quick response.  Here is whats happening now - both (yours & mine) code snippets are returning correct service Id.  It turns out, there was a CF issue when I tried earlier so code returned incorrect id.   I believe the same thing would have happen with PaginationUtils also, as it appears internally its invoking the same thing. 
 
At point the CF issue is resolved,  so i cannot replicate the issue I reported.  But The question still remains the same why would metadata Id returns incorrect Id, instead of throwing  error ?

**Comment by twoseat** [comment]
Thanks for the update @pandeyar - the main reason for the alternate code was just to remove that as a possible cause, not because I thought it was that (though I do recommend using that style if you can!).

Can you describe the error CF was generating? Broadly speaking we don't sanitise return values, so as long as it's well-structured we'll just pass it on, 'valid' or not. If it was returning an actual error then we should have passed that on.
