### ISSUE TITLE
Get app list return error:Connection closed prematurely (part 2)

### ISSUE THREAD

**Issue by eaglerainbow** [cloudfoundry/cf-java-client#893]
As apparently nobody is looking at the advertised re-opening at #833, I want to create an own new issue for it, providing the following further details:

[Promregator](https://github.com/promregator/promregator) is an application that uses the cf-java-client. @dschroe reported [an issue at Promregator](https://github.com/promregator/promregator/issues/59), which I believe is very similar to #833. He is capable of reproducing it quite regularly; I was able to reproduce it having debugging mode enabled once by chance. I am [attaching the log file](https://github.com/cloudfoundry/cf-java-client/files/2041846/promregator-closedprem.log), which I could get hold of. 
The coding which is executed can mainly be reviewed at https://github.com/promregator/promregator/blob/c7f1613d9f332cb2ce1a1c562c18328e03aec2f5/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java:
* The setup procedure of the connection can be found at https://github.com/promregator/promregator/blob/c7f1613d9f332cb2ce1a1c562c18328e03aec2f5/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L175
* The issue happens already with the first business call, which is triggered by https://github.com/promregator/promregator/blob/c7f1613d9f332cb2ce1a1c562c18328e03aec2f5/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L231. The latter mainly consists of
   ```
   ListOrganizationsRequest orgsRequest = ListOrganizationsRequest.builder().name(orgName).build();
   this.cloudFoundryClient.organizations().list(orgsRequest);
   ```
* Based on the result returned, further operations would be requested (based the that Mono) afterwards. In sum, we can expect that roughly 12 operations will be triggered.
* The `IOException` is raised on the response of `this.cloudFoundryClient.organizations().list(or)`. You can verify this due to the error message `Retrieval of retrieveOrgId with key ibm@schmoigl-online.de raised a reactor error` which you find in the log, which is triggered by https://github.com/promregator/promregator/blob/c7f1613d9f332cb2ce1a1c562c18328e03aec2f5/src/main/java/org/cloudfoundry/promregator/cfaccessor/ReactiveCFAccessorImpl.java#L212

I tried to understand what is happening based on the verbose logs attached. What makes me wondering are the log messages at 2018-05-26 16:44:38.566 and later, which read: egistering close event to pool release: 
```
Acquired [id: 0x691802ab, L:/192.168.1.130:58972 - R:api.eu-gb.bluemix.net/2.23.183.41:443], now 15 active connections
[...]
Acquired [id: 0x3a462b0e, L:/192.168.1.130:58973 - R:api.eu-gb.bluemix.net/2.23.183.41:443], now 16 active connections
[...]
Released [id: 0xdc193d2b, L:/192.168.1.130:58958 ! R:api.eu-gb.bluemix.net/2.23.183.41:443], now 15 active connections
Released [id: 0x2afce4a0, L:/192.168.1.130:58960 ! R:api.eu-gb.bluemix.net/2.23.183.41:443], now 14 active connections
Released [id: 0x2ae976b1, L:/192.168.1.130:58961 ! R:api.eu-gb.bluemix.net/2.23.183.41:443], now 13 active connections
```
This makes me puzzled, because we even did not receive an answer from `this.cloudFoundryClient.organizations().list(or);` yet - even worse, we even did not send the request, yet! The only request which was sent, was the API standard request, which reads `GET / HTTP/1.1`.

Oh, before I forget: Version of `cloudfoundry-client` in use is 3.3.0.RELEASE.

Could you please assist in looking at the logs and help understanding what is going wrong here?

Thanks!

**Comment by twoseat** [comment]
My apologies for missing your earlier comment - I'll look at this today.

**Comment by eaglerainbow** [comment]
No problem 😄 Apologies accepted.
We are currently simply clueless from where the problem is coming (perhaps it's also some mistake from our side). So some hints or debugging pointers where to look at would be appreciated. We'll then also try to feed you with further information to get to the root cause.

**Comment by twoseat** [comment]
I've just published v3.11.0.RELEASE, which should be making its way to a repo near you shortly. I think the first thing to do is update to that version, as there have been a few changes in reactor that _might_ address your problem. And if not at least I can't use an outdated version as an excuse!

**Comment by eaglerainbow** [comment]
Ok, we will do and report back once we have data which is up-to-date.
(Unfortunately, I can't make it to bump the version today... that implies to do some more work...)

**Comment by eaglerainbow** [comment]
For the record: Source code as of state of `promregator:0.4.0-rc3` can be reviewed [here](https://github.com/promregator/promregator/tree/v0.4.0-rc3/src/main/java/org/cloudfoundry/promregator).

**Comment by eaglerainbow** [comment]
I tried several times now reproducing the previous issue, but without success. However, this does not mean much, as in the past I also had problems reproducing it in my environment (finding it locally with debug logging enabled was more or less by chance). 

@dschroe: You said that you could reproduce the issue quite easily. Could you please give it a try on next occasion? I suggest to set the following config options:
```yaml
promregator:
  reactor:
    debug: true

logging:
  level:
    org:
      cloudfoundry:
         promregator: DEBUG
    reactor:
      mono:
        OnAssembly: INFO
      ipc:
        netty: DEBUG
```
in addition to your other configuration options you have made.
**WARNING** Setting these options is dangerous: They may log data, which are sensitive such as passwords or internal URLs. Therefore, don't post the logs without cleansing!

**Comment by eaglerainbow** [comment]
@dschroe: Could you reproduce this issue in the meantime somehow? Or was that fixed together with https://github.com/promregator/promregator/issues/59#issuecomment-399710269?
