### ISSUE TITLE
[Feature Enquiry] is it possible to use remotely located JAR files in manifest file.?

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#894]
my requirement is deploying an app into CF using API call.

if i have upload my jARs files to s3 bucket.
& given S3 file path in manifest.yml file .

my query is when i use this manifest while pushing by CFOperations, will it download app bits from S3 and push code to CF ?

Like docker Image ?

**Comment by parasuramln** [comment]
@nebhale  can you answer it please

**Comment by nebhale** [comment]
The Java Client operations layer `CloudFoundryOperations` behaves exactly as the CF CLI does, so no it will not.  You'll notice that the [`path()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.12.0.RELEASE/org/cloudfoundry/operations/applications/PushApplicationRequest.html#getPath--) argument uses the Java filesystem `Path` abstraction, so local only.

It is possible for you to write code, in conjunction with the [aws-sdk](https://aws.amazon.com/sdk-for-java/) that can automate this.
