### ISSUE TITLE
Unable to Stop the Application  using StopApplicationRequest

### ISSUE THREAD

**Issue by dasguptaeesudipto** [cloudfoundry/cf-java-client#895]
Hi  ,

Please help on   how to stop a cf application using cf java client  . How to implement it ?
How can it be  done using StopApplicationRequest ?

**Comment by nebhale** [comment]
[`Applications#stop`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.12.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#stop-org.cloudfoundry.operations.applications.StopApplicationRequest-)

**Comment by dasguptaeesudipto** [comment]
Hi , This is not working . it is not a cf command . It should work with cf java client . I have already tested it .

**Comment by dasguptaeesudipto** [comment]
It seems not  to be stopping app.is it for logs?

**Comment by nebhale** [comment]
You can see in the output (2nd line from the end) that the application has been stopped.  This is tested dozens of times a day as part of development and quite definitely works.  Again, I suggest you learn about [how Reactive Programming works](https://projectreactor.io/learn) and ensure that your code follows the same patterns as the example above.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of months, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
