### ISSUE TITLE
Unable to pull cf application Recent Log

### ISSUE THREAD

**Issue by dasguptaeesudipto** [cloudfoundry/cf-java-client#896]
How to pull  the recent log of a cf application  using cf java client ?  Is there any API to do that ?

**Comment by nebhale** [comment]
[`Applications#logs`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.12.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#logs-org.cloudfoundry.operations.applications.LogsRequest-)

**Comment by dasguptaeesudipto** [comment]
I know that . But how to implement it ? When i am trying to use it using cf java client it is not working . Can you please suggest ?

**Comment by nebhale** [comment]
Please see the [Usage Documentation](https://github.com/cloudfoundry/cf-java-client#usage) for creation and basic usage of the API.  [This webinar](https://www.youtube.com/watch?v=Q1ZKpQ58omI) from a couple of years ago goes into a bit more depth.

**Comment by dasguptaeesudipto** [comment]
The Recent Log  pulling is not there . can you please validate ? I need the Api  which helps to invoke the Recenet log . How to do that using cf client ?

**Comment by dasguptaeesudipto** [comment]
Can you please  help in getting the recent logs using c.f. java client?

**Comment by nebhale** [comment]
The API is there, you'll notice it on the [`LogsRequest` builder type](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.12.0.RELEASE/org/cloudfoundry/operations/applications/LogsRequest.Builder.html#recent-java.lang.Boolean-).  Please look over the [documented examples](https://github.com/cloudfoundry/cf-java-client#cloudfoundryclient-apis) and [example code](https://github.com/cloudfoundry/cf-java-client/tree/master/integration-test/src/test/java/org/cloudfoundry/operations) to ensure you understand the programming paradigms and patterns before asserting that APIs are not available.

**Comment by dasguptaeesudipto** [comment]
I am very  sorry to say but there is no recent logs request handled in the example code.can you please check?
Also I have tried implementing the apis already that you shared.It did not help.

**Comment by dasguptaeesudipto** [comment]
Can you please help
