### ISSUE TITLE
When listening on the firehose I randomly get "Required field not set: method" error and Wavefront PCF nozzle stops working and needs to manually restarted.

### ISSUE THREAD

**Issue by sushantdewan123** [cloudfoundry/cf-java-client#901]
This is related to 

https://github.com/cloudfoundry/cf-java-client/issues/880

I am seeing the exact same issue for Wavefront PCF nozzle
https://github.com/wavefrontHQ/cloud-foundry-nozzle

We recently updated the client to 3.11.0.RELEASE

org.cloudfoundry
cloudfoundry-client-reactor
3.11.0.RELEASE

Do we need to change anything in our code to handle this? We want to avoid reconnecting if we see this issue and hoping the cf-java-client handles this for us (which was the ask in the original ticket).

See https://github.com/cloudfoundry/cf-java-client/issues/880#issuecomment-404387824
for more details.

Any help/pointers on this appreciated! 
@nebhale and @twoseat  - Unfortunately, this is a blocker issue for us :(

**Comment by sushantdewan123** [comment]
Any update on this?

**Comment by twoseat** [comment]
Hi @sushantdewan123 (and @youngm). It seems that the issue isn't in the client code - after the fix mentioned in #880 we don't require this field, but it's still a required field in the [Dropsonde protocol](https://github.com/cloudfoundry/dropsonde-protocol/blob/master/events/http.proto#L70), which the client has no control over. It appears, therefore, that Cloud Foundry is emitting messages that don't meet this requirement. The @cloudfoundry/cf-loggregator team may be able to help more.

**Comment by twoseat** [comment]
@youngm I started work on v2 today, though I'm new to this area so don't know enough to make predictions about when it will be complete. #904 is the relevant issue.

**Comment by youngm** [comment]
That's great @twoseat !  As long as there is a steady effort to add v2 support then that is good enough for me.  I can survive with the way things are now and will plan to move to v2 when it is available for a more solid fix.  I cannot speak for @sushantdewan123 though.  Thanks!

**Comment by sushantdewan123** [comment]
Ah looks like I will switch to v2 when it's GA but for now I might have to catch IllegalStateException with message prefix - "Required field not set: method" and reconnect :(
I don't see any other workaround.
