### ISSUE TITLE
CLI push & CF java Client deploy are giving different app bits 

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#906]
hi,
**case 2)** 
i pushed a java app using CLI & downloaded app bits 
 **case 1)**
i pushed same java app using CF java client (operations) and downloaded app bits.

in both cases same binary & manifest used .
but in case 1 manifest is not ignored by java client & it  is downloaded in appbits.
PF screenshots.
 
![cf bug](https://user-images.githubusercontent.com/22343548/44344745-126a7980-a4af-11e8-9d42-dc6639b2fde1.png)

**Comment by parasuramln** [comment]
observation:
**in case1(CLI)** ,in downloaded app bits **there is no manifest.yml file which is there in my WAR**

**Comment by twoseat** [comment]
Hi @parasuramln - can I clarify that in your description 1 is the CLI, 2 is the java client, but in the diagram 1 is the java client and 2 is the CLI?

**Comment by parasuramln** [comment]
observation:
in **case2** **(CLI)** ,in downloaded app bits there is no manifest.yml file which is there in my WAR

**Comment by twoseat** [comment]
How are you downloading the app bits?

**Comment by parasuramln** [comment]
cf app **appname** --guid
cf curl /v2/apps/**d4861f56-cef3-42e4-8ab0-e13e48c04b58**/download -i --output ram123.zip

**Comment by parasuramln** [comment]
hi @twoseat  is there anyway to avoid this problem ?

**Comment by twoseat** [comment]
I've been unable to reproduce this so far. Are you able to share your app? And what version of CF are you running against?

**Comment by parasuramln** [comment]
please use this app for testing. i am able to reproduce it with this app
[testapp.zip](https://github.com/cloudfoundry/cf-java-client/files/2314895/testapp.zip)

![image](https://user-images.githubusercontent.com/22343548/44531894-755a4b80-a70f-11e8-9059-afa2040def6b.png)

**Comment by twoseat** [comment]
Thanks for the example, that made things much clearer. The cli does some filtering before upload, including removing `manifest.yml`. For various reasons, including practical issues such as disk space, and the different use case it's intended for, the java client doesn't do that, relying on the user to only upload the files they want. As a result I don't plan to change this behaviour unless I see a lot of demand.

**Comment by parasuramln** [comment]
Is there any way to avoid uploading of manifest while uploading app to Cf through to java client
