### ISSUE TITLE
[Question] GetServiceInstance doesnt contain credentials map

### ISSUE THREAD

**Issue by BarathArivazhagan** [cloudfoundry/cf-java-client#907]
Does ServiceInstance/ ServiceInstanceSummary doesn`t fetch credentials map ? 
or am I missing something ? 

```
code: 
cfOperations.services().getInstance(request);

response:

     {
        "applications": [],
        "id": "4d709501-1b88-4135-97db-cf15ebcf8ed7",
        "lastOperation": "",
        "name": "auto-scalar",
        "plan": "standard",
        "service": "app-autoscaler",
        "type": "managed_service_instance"
      }

```
Questions is how to get full details of the cups including credentials based on service name ?

**Comment by nebhale** [comment]
Correct.  If you look at the CLI analog for the operation you're calling, you'll notice that it is not exposed:

```
$: cf service redis-test
Showing info of service redis-test in org [REDACTED] / space [REDACTED] as [REDACTED]...

name:            redis-test
service:         rediscloud
tags:            
plan:            100mb
description:     Enterprise-Class Redis for Developers
documentation:   
dashboard:       https://cloudfoundry.appdirect.com/api/custom/cloudfoundry/v2/sso/start?serviceUuid=[REDACTED]

Showing status of last operation from service redis-test...

status:    create succeeded
message:   
started:   2017-09-19T20:06:29Z
updated:   2017-09-19T20:06:29Z

bound apps:
name                        binding name   status      message
web-servlet-2-application                  succeeded  
```

**Comment by BarathArivazhagan** [comment]
@nebhale  ok. But API does provide an option of retrieving the credentials while retrieving the user defined services as mentioned here 

[Cloud foundry API- user-provided-service-instances](https://apidocs.cloudfoundry.org/3.6.0/user_provided_service_instances/retrieve_a_particular_user_provided_service_instance.html)

I could see create and update cups services takes credentials as part of the request. Would it be a better idea to enhance it for the users or do you foresee security constraints ?

**Comment by nebhale** [comment]
The Client API ([lower-level matched 1:1 to the CF APIs](https://github.com/cloudfoundry/cf-java-client#cloud-foundry-java-client)) does, the Operations API (higher-level matched 1:1 to the CLI) does not.

**Comment by BarathArivazhagan** [comment]
cool @nebhale . Thanks for the clarification.
