### ISSUE TITLE
SSLEngine and NPE failures under high load

### ISSUE THREAD

**Issue by tareqhs** [cloudfoundry/cf-java-client#908]
Hi,

I am experiencing TLS-related inconsistencies if a given ``ConnectionContext`` is used by a high number of CF operations frequently. This is what I do:
1. Create a singleton ``ConnectionContext`` with default configuration
1. Create a singleton ``CloudFoundryClient`` with default configuration
1. list organizations: ``client.organizations.list(...).block()`` 1000 times
1. wait 30 seconds and repeat (3)

After two-three iterations, I start getting exceptions:
* javax.net.ssl.SSLException: SSLEngine closed already
* java.lang.NullPointerException: while trying to invoke the method io.netty.handler.codec.http.HttpMethod.name() of a null object loaded from local variable 'method'

**Comment by violetagg** [comment]
Might be related to https://github.com/reactor/reactor-netty/issues/413

**Comment by mheath** [comment]
I don't think this is related to reactor/reactor-netty#413, I have updated to reactor-netty 0.7.14.RELEASE and I still see this issue.

**Comment by dmikusa-pivotal** [comment]
This is a very old issue and I'm not sure if this still applies to recent versions so I'm going to close this out. 

If you are experiencing this or a similar issue using the latest 4.x or 5.x release of the cf-java-client, then please open a new issue and include the [suggested troubleshooting information](https://github.com/cloudfoundry/cf-java-client#troubleshooting). Thanks!
