### ISSUE TITLE
Cloudfoundry Operations : Enable service access enabling access for all plans even with plan name specified

### ISSUE THREAD

**Issue by arghya88** [cloudfoundry/cf-java-client#913]
Cloudfoundry Operations "enable service access"  API enabling access for all plans even with plan name specified

**Comment by arghya88** [comment]
@twoseat if you have not started already I can start on it.

**Comment by twoseat** [comment]
Haven't started yet, and always happy to accept a PR!

**Comment by arghya88** [comment]
@twoseat..can you prioritize this

**Comment by twoseat** [comment]
@arghya88 Can you clarify what the exact problem is? Specifically do you mean that if you have serviceA and serviceB, and enable service access for serviceA by name, it will enable service access for serviceB?
