### ISSUE TITLE
Getting error in get_user_summary request

### ISSUE THREAD

**Issue by mohneeshdamade** [cloudfoundry/cf-java-client#917]
the response results in error while parsing UserOrganizationEntity

the quota definition is expected to be an array but it actually is not an array in the json

https://apidocs.cloudfoundry.org/5.4.0/users/get_user_summary.html

Please find the error below:

```
feign.codec.DecodeException: JSON parse error: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
```

**Comment by twoseat** [comment]
Thanks for the report @mohneeshdamade - after extensive investigation I have no idea why I did it as a list (or included a quota id as a top-level field). A fix will follow shortly...

**Comment by mohneeshdamade** [comment]
Thanks for the quick fix @twoseat  👍
