### ISSUE TITLE
Connection timeout when connecting to CF API

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#922]
Recently we are getting a lot of io.netty.channel.ConnectTimeoutException exceptions while trying to connect to the CF client.
After restarting the instance the issue resolves which made us think that this has something to do with caching the connections.
Is there a configuration that can prevent this caching? What should be done in such cases?

Best Regards,
Andrea.

**Comment by dmikusa-pivotal** [comment]
This is a very old issue so I'm going to close this out. If you are experiencing this or a similar issue using the latest 4.x or 5.x release of the cf-java-client, then please open a new issue and include the [suggested troubleshooting information](https://github.com/cloudfoundry/cf-java-client#troubleshooting). Thanks!
