### ISSUE TITLE
--origin flag to login request

### ISSUE THREAD

**Issue by andreaAlkalay** [cloudfoundry/cf-java-client#923]
Hi,

Currently, I can't see an option to add an origin flag to the login request.

This flag was introduced in v6.39.0 of the CLI and currently, we don't have a way to use it.

Can you please help?

Thanks,
Andrea.

**Comment by andreaAlkalay** [comment]
Currently, the cf-java-client is unusable to us because of this issue, would appreciate a fix for this to allow passing the origin flag.

**Comment by twoseat** [comment]
To aid my understanding, @andreaAlkalay, is the `login_hint` field in https://docs.cloudfoundry.org/api/uaa/version/4.24.0/index.html#authorization-code-grant (and a number of other methods there) what you're looking for?

**Comment by andreaAlkalay** [comment]
Hi,

Yes, this is the field I was referring to.
I don't see a way to pass it currently when building the PasswordGrantTokenProvider.

Thanks,
Andrea.

**Comment by pavellom** [comment]
Hi @twoseat,

Actually, I believe @andreaAlkalay is referring to login_hint field in 
[https://docs.cloudfoundry.org/api/uaa/version/4.24.0/index.html#password-grant](https://docs.cloudfoundry.org/api/uaa/version/4.24.0/index.html#password-grant)

I've prepared a [PR](https://github.com/cloudfoundry/cf-java-client/pull/924) to add the missing field
