### ISSUE TITLE
Changing logging level

### ISSUE THREAD

**Issue by cstevandy** [cloudfoundry/cf-java-client#934]
Is there a way to change the logging level in the cf-java-client library?

**Comment by twoseat** [comment]
You can set an environment variable of `CLIENT_LOGGING_LEVEL` to your choice of level (by default it's `INFO`, for internal development we set it to `DEBUG`

**Comment by cstevandy** [comment]
Thanks for your answer.

**Comment by nebhale** [comment]
This is not correct.  We configure Logback to honor that environment variable [in our tests](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/resources/logback-test.xml#L26) but only _your_ logging configuration could do the same.  The key point is that all loggers in the project are children of `cloudfoundry-client`.  So use _your_ logging framework to configure that and it's children to the levels you require.
