### ISSUE TITLE
Demo app not up-to-date Need example

### ISSUE THREAD

**Issue by webbbret** [cloudfoundry/cf-java-client#937]
Following directions here: https://docs.pivotal.io/pivotalcf/2-4/buildpacks/java/java-client.html#sample-code

The example application references imports that appear to not exist. In addition, the pom dependencies seem outdated compared to the readme file for this project. 

Can someone please point me to a reliable up-to-date example for using this lib? Many thanks in advance.

**Comment by dominikmueller** [comment]
Hi @webbbret,
my colleague and me (as non-java-developers) also had problems using the examples provided.
What helped us to understand how this client is meant to be used was an introduction on youtube.

Maybe it might help you as well:
[Introducing the Cloud Foundry Java Client 2.0
](https://youtu.be/Q1ZKpQ58omI)
What helped us most was the part starting at 10:18 ([same video, starting at 10:18](https://youtu.be/Q1ZKpQ58omI?t=618))

Nevertheless we also would be happy when the examples would be up to date.

**Comment by nebhale** [comment]
The only sanctioned examples are the ones found [in the documentation](https://github.com/cloudfoundry/cf-java-client#usage).  Our webinars, as documented above would also work.
