### ISSUE TITLE
Incompatibility with Spring WebFlux 5.1 WebClient

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry/cf-java-client#938]
When CF Java Client is used in an application that also uses `WebClient` from Spring WebFlux `2.1.x.RELEASE`, exceptions are thrown from Netty and connections to CF fail. 

The relevant exception is: 
```
Caused by: java.lang.IllegalArgumentException: 'httpRedirects' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:113) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:95) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at reactor.netty.http.client.HttpClientOperations.<clinit>(HttpClientOperations.java:720) ~[reactor-netty-0.8.3.RELEASE.jar:0.8.3.RELEASE]
```

The root of the issue is clashing versions of `reactor-netty`. 

* CFJC `3.x` depends on `io.projectreactor.ipc:reactor-netty:0.7.x.RELEASE` (via `spring-boot-dependencies:2.0.x`). 
* Spring WebFlux `2.1.x` depends on `io.projectreactor.netty.reactor-netty:0.8.x.RELEASE`. 

These versions of `reactor-netty` both have a class with a static initializer that registers a "constant" with Netty: 

* `reactor-netty:0.7.x.RELEASE`: [reactor.ipc.netty.http.client.HttpClientOperations](https://github.com/reactor/reactor-netty/blob/0.7.x/src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java#L929-L930)
* `reactor-netty:0.8.x.RELEASE`: [reactor.netty.http.client.HttpClientOperations](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L738-L739)

Whichever of these initializers runs first wins, and the second one fails. When the `HttpClientOperations` used by CFJC fails to initialize, the exception above appears in stdout but the app will start. Subsequent calls to CFJC result in long delays followed by a timeout.

**Comment by scottfrederick** [comment]
Thanks @twoseat! I did a quick version update in `pom.xml` along with a search-and-replace on exports just to see what the upgrade would look like, and I got scared :-). It does look like a big change to take on. I figured you were aware of the need to upgrade but I thought an issue with the exception would be useful in case anyone else tries to use the same combination of dependencies.

**Comment by idantr** [comment]
@twoseat can the 0.8.x be later than 0.8.6 this will fix additional bug we have that is still not reflected in cf-java-client 
https://github.com/reactor/reactor-netty/issues/413
Cheers
Idan.
