### ISSUE TITLE
Incorrect apps.pushManifest behavior when using custom private domain route

### ISSUE THREAD

**Issue by vshetty001** [cloudfoundry/cf-java-client#940]
We have developed our own implementation of zero downtime restage. We are using java client api version 3.14.0 RELEASE. As part of that 

(1) we retrieve the ApplicationManifest from the old application {old name} that we need to restage using Applications.getApplicationManifest
(2) Create a new app {app name} using the Applications.pushManifest using the manifest from previous step. 
(3) Copy the bits using Applications.copySource from {old name} to {new name}

However, if I am using custom domains - then the step (2) creates a {app name} which has incorrect routes. Instead of the route being {custom domain}/{path}, the route associated with the new app is {app name}.{custom domain}/{path}. The {app name} is incorrectly added to the route as hostname whereas it should have been empty. 

This seems like a bug.  Is there any workaround for this ?

**Comment by twoseat** [comment]
Thanks for the report @vshetty001 - digging through the code shows that, if we don't have host information from anywhere else, we default to using the app name as the host. That used to be a correct assumption, but clearly it isn't any more. I don't see a workaround for it, but I've made this an issue for the next release.

**Comment by vshetty001** [comment]
Thanks for looking into this @twoseat. I will await the 3.16.RELEASE. For now, I have created a powershell script which uses the CF Client commands and they seem to work correctly. 

I will raise another issue, but it looks like the Applications.pushManifest  has an issue with docker images as well. Step (2)  throws an issue when we are trying to restage a docker image instead of buildpack. CF client command works fine.

**Comment by vshetty001** [comment]
For the docker problem, i created issue #942

**Comment by nictas** [comment]
@vshetty001 The behavior you describe is consistent with `cf push`. If you have the following manifest:
```
applications:
  - name: my-app
    path: my-app.zip
    domain: my-domain.com
```
`cf push` would create a route called `my-app.my-domain.com` and not just `my-domain.com`. If you want the latter, then you'll have to use the `no-hostname` attribute:
```
applications:
  - name: my-app
    path: my-app.zip
    domain: my-domain.com
    no-hostname: true
```
Have you tried this?

@twoseat Please correct me if I'm wrong here.

**Comment by dmikusa-pivotal** [comment]
I agree with the previous comment. The cf cli will add a default route based on the application name unless it's told otherwise. That sounds consistent with what the cf-java-client is doing. If you don't want that default route, then it needs to be disabled.

You have additional controls here given that you're using a programmable client instead of the cf cli. If you want different routes, just set `no-route` and set up the routes you do need.

Closing as this is a very old issue.
