### ISSUE TITLE
How to push Application from private Docker Registry

### ISSUE THREAD

**Issue by harald-luebeck** [cloudfoundry/cf-java-client#941]
I want to push an Application from a Private Docker Registry. The "push" works but the app fails during staging. It seems that the Docker Registry Authorization Data is not correct.

Here is my Code:

public void deployApplication( final String applicationUId, final String dockerImage, final String dockerUserName, final String dockerPassword )
	{
		final DefaultCloudFoundryOperations cloudFoundryOperations = DefaultCloudFoundryOperations.builder().cloudFoundryClient( cloudFoundryClient ).dopplerClient( dopplerClient ).uaaClient( uaaClient ).organization( organization ).space( space ).build();

		final PushApplicationRequest.Builder pushApplicationRequestBuilder = PushApplicationRequest.builder().dockerImage( dockerImage ).name( applicationUId ).noStart( true );

		if( dockerUserName != null )
		{
			pushApplicationRequestBuilder.dockerUsername( dockerUserName ).dockerPassword( dockerPassword );
		}

		final PushApplicationRequest pushApplicationRequest = pushApplicationRequestBuilder.build();

		final Object application = cloudFoundryOperations.applications().push(pushApplicationRequest).doOnSuccess(v -> System.out.println("Done")).doOnError(e -> System.out.println("Error creating app was " + e)).block(Duration.ofMinutes(30));
		System.out.println( "STOP" );
	}

What is my mistake ? 

Thanks

**Comment by twoseat** [comment]
Hi @harald-luebeck. Can you post the error you get from the fail? Don't forget to remove any passwords etc. if they're in there. Also, do the same credentials work if you use the cli (`cf push --docker-username`)?
