### ISSUE TITLE
Support v3 Metadata

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cf-java-client#946]
[Metadata][m] is out of experimental status. Customer request.

[m]:  https://v3-apidocs.cloudfoundry.org/version/3.66.0/index.html#metadata

**Comment by cjett-pivotal** [comment]
I too have a customer asking for this functionality.

**Comment by dmikusa-pivotal** [comment]
Support for metadata has been added in several places. [Apps](https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/applications/Application.java#L41), [Spaces](https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/spaces/Space.java#L34), [Orgs](https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/organizations/Organization.java#L33), etc...

I'm going to close out this issue. If you missing metadata on a [CAPI resource that supports it](https://v3-apidocs.cloudfoundry.org/version/3.66.0/index.html#resources) please open a new issue fo that specific resource and we can address it. Thanks.
