### ISSUE TITLE
Is it possible to use URLs returned by REST API to create another REST calls to Cloud Foundry?

### ISSUE THREAD

**Issue by ShevaDavid** [cloudfoundry/cf-java-client#961]
For example I've got the following response 
`        "service_instance_url": "/v2/service_instances/bde206e0-1ee8-48ad-b794-44c857633d50",
`
and I want to use this URL to fetch this Service Instance using ReactorCloudFoundryClient

**Comment by twoseat** [comment]
You shouldn't need to. `GetServiceInstanceRequest` takes the `service_instance_guid` (that's the long string at the end of that url) and returns the service instance details. While I don't know what request has given you that url, it should have also given you the `service_instance_guid` directly (see for example https://apidocs.cloudfoundry.org/1.1.0/service_keys/retrieve_a_particular_service_key.html)

**Comment by ShevaDavid** [comment]
Thanks, I've found what I was looking for
`reactorCloudFoundryClient.serviceInstances().listServiceBindings(ListServiceInstanceServiceBindingsRequest.builder().build())`
