### ISSUE TITLE
Is it possible to get the date of the last push of the application?

### ISSUE THREAD

**Issue by ShevaDavid** [cloudfoundry/cf-java-client#962]
Any ways to do it with java-client or CLI?

**Comment by twoseat** [comment]
I don't think a push is an event that's tracked directly. You can see the available information [here](http://v3-apidocs.cloudfoundry.org/version/3.70.0/index.html#the-app-object)} or [here](https://apidocs.cloudfoundry.org/8.0.0/apps/get_app_summary.html) (deprecated, but still active).
