### ISSUE TITLE
Support for filterable label requests on applications

### ISSUE THREAD

**Issue by eaglerainbow** [cloudfoundry/cf-java-client#967]
In https://github.com/promregator/promregator/issues/110#issuecomment-497084164 we currently discuss, whether Promregator wants to make use of labels attached to applications. This would require that querying for labels was supported by cf-java-client. As of now, I don't see support for this feature, yet (please correct me, if I was wrong). 

Details on handling of metadata (i.e. labels and annotations) can be found at https://docs.cloudfoundry.org/adminguide/metadata.html .
The documentation remains unclear whether labels/annotations are only supported for v3 applications or also for v2 applications. A brief test on a CF API 2.128.0 gives indication that it is only supported for v3 applications.

Support for labels on org and/or space level could also be interesting (but details haven't been sketched out so far).

Do you see a chance to support querying and retrieving labels for v3 applications in one of the next versions?

**Comment by eaglerainbow** [comment]
Could be related to #946

**Comment by dmikusa-pivotal** [comment]
Metadata is supported in many of the CAPI resources (possibly all, I haven't validated). If you're seeing it missing from a resource that can support it, please open an issue and we'll address that.

In terms of querying, there are a number of resources that support the `label_selector` which is how you query the labels through the API. For example, [ListApplicationsRequest](https://github.com/cloudfoundry/cf-java-client/blob/190f26a296789b2b7928877b318c33981dbe8707/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/applications/_ListApplicationsRequest.java#L43). If there is a resource that's missing a label selector where it could be supported, please open a specific issue for that and we'll address it.

>The documentation remains unclear whether labels/annotations are only supported for v3 applications or also for v2 applications. A brief test on a CF API 2.128.0 gives indication that it is only supported for v3 applications.

My understanding is that it's a v3 API feature only.

>Support for labels on org and/or space level could also be interesting (but details haven't been sketched out so far).

Organizations and Spaces have metadata available, but not the label selector. If this feature is still of interest, please open a new issue specific for the resource to add label selectors & we can add those.

This is a pretty old issue, so I'm going to close it out. Again, if there are specific areas where were you'd like us to enhance the metadata support, just open up a new issue and we can discuss further. Thanks!
