### ISSUE TITLE
How to provide operators to an events list query? 

### ISSUE THREAD

**Issue by nakulvr** [cloudfoundry/cf-java-client#971]
As per the Events API documentation: [https://apidocs.cloudfoundry.org/9.5.0/events/list_all_events.html](url)
we can provide comparison operators as part of the query parameters (q=filter>value)

From the API I am able to provide two timestamp values for providing a range using comparison operators (validated that it successfully fetches the events between the provided range).

```
/v2/events?q=timestamp>=2019-07-09T14:40:25Z&q=timestamp<=2019-07-11T14:40:25Z
```

I used the below cloudfoundry java client call to fetch **all** the events occurred **after** "2019-07-10T18:00:00Z"
```
cloudFoundryClient.events().list(ListEventsRequest.builder().timestamps("2019-07-10T18:00:00Z").build()).flatMapMany(ResourceUtils::getResources)
```

But I am not sure how to provide these comparison operators (to obtain events between a range of timestamps) using the cloudfoundry java client. 

I have used the same versions of all the packages as mentioned in README.

**Comment by dmikusa-pivotal** [comment]
You can do this with the API, but I don't think that the cf-java-client exposes this capability. 

The [ListEventsRequest](https://github.com/cloudfoundry/cf-java-client/blob/190f26a296789b2b7928877b318c33981dbe8707/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/events/_ListEventsRequest.java#L56) object has a FilterParameter annotation on it and that annotation contains the operation. That operation is statically set in the code to greater than or equal to. I don't believe you can change this as a consumer of the client, as you cannot modify the annotation.

The best you could do would be to provide the lower of the two timestamps and then filter client-side to remove those greater than what you care about.

This is an old issue, so I'm closing. If there is any further feedback, please feel free to reopen.
