### ISSUE TITLE
Support "ports" application attribute via update

### ISSUE THREAD

**Issue by GFriedrich** [cloudfoundry/cf-java-client#975]
Currently one can only set the "ports" attribute via `CreateApplicationRequest`.
It's neither possible to use `UpdateApplicationRequest` to update the ports nor to hand over the ports via the `ApplicationManifest` e.g. when using the `PushApplicationManifestRequest`.
Would be awesome if that could be added.
Thanks in advance!

**Comment by GFriedrich** [comment]
@twoseat Do you have any objections if I open a PR for this?

**Comment by twoseat** [comment]
No objection at all!

**Comment by twoseat** [comment]
Reopened after discussion on planned CAPI changes

**Comment by GFriedrich** [comment]
The scope of this issue has been reduced to adding the app ports only to the update of an application until the usage of app ports within the app manifest has been clarified.

**Comment by twoseat** [comment]
Resolved in dc1c25d134adb1ad7c9997569c4fc5df38d29527
